// Un recorrido: cada actividad muestra su consigna junto a las herramientas que necesita.
// Los tiempos, las entregas y la práctica opcional siguen en DEEP_CURRICULUM.
// «compare» siempre compara versiones propias; no introduce los modelos del curso.
const ACTIVITY_FOCUS = [
  [
    {title:'Encontrá el pulso',instruction:'Elegí una velocidad entre 75 y 95 BPM. Escuchá los pulsos y marcá cuatro por vuelta: en la grilla empiezan en 1, 5, 9 y 13. Todavía no escribas notas.',why:'Un compás de 4/4 tiene cuatro pulsos; acá cada pulso ocupa cuatro pasos.',tools:['tempo','play','grid']},
    {title:'Escribí tus dos primeras notas',instruction:'Elegí duración 1, seleccioná el paso 1 y pulsá Do. Elegí otro comienzo de pulso —5, 9 o 13— y poné allí otro Do. Activá «repetir» y escuchá cuatro vueltas, siguiendo el pulso también en los huecos.',why:'Cada Do dura un paso: el espacio que queda hasta el siguiente es un silencio real.',tools:['play','grid','keys','length']},
    {title:'Mové una nota y compará',instruction:'Conservá tu versión actual. Seleccioná el segundo Do y movelo con las flechas hasta otro comienzo de pulso: 5, 9 o 13. Alterná tu versión guardada y tu composición; escuchá cuánto esperás entre los dos ataques.',why:'Mover el ataque cambia cuándo empieza la nota; la duración y el tempo se mantienen.',tools:['play','grid','move','compare']},
    {title:'Elegí cuánto aire dejar',instruction:'Elegí entre las dos posiciones; recuperá la versión guardada si la preferís. Probá un tercer Do en un paso vacío y quitálo volviendo a pulsar Do en ese paso. Quedate con dos o tres ataques según cuál haga más reconocible tu ritmo.',why:'Más notas ocupan más espacio; menos notas dejan más aire sin cambiar la velocidad.',tools:['play','grid','keys','compare']},
    {title:'Reconocé tu ritmo sin mirar',instruction:'Activá «repetir», ocultá las notas y escuchá cuatro vueltas. Marcá los cuatro pulsos e intentá recordar tu ritmo. Si te perdés, volvé a mostrar las notas, quitá el último ataque añadido y probá otra vez.',why:'Reconocer el gesto durante el silencio te permite recordarlo y desarrollarlo después.',tools:['play','blind','grid','keys']},
    {title:'Dejá listo el próximo paso',instruction:'Tu composición se guarda mientras editás. Anotá las posiciones de tus notas, el tempo y una razón para elegirlas; terminá con «La próxima vez conservaré este compás y le inventaré una respuesta». Si trabajaste también en el OP–XY, guardá allí el proyecto.',why:'Anotar una decisión te permite retomar la canción sin empezar de cero.',tools:['reflection','close']}
  ],
  [
    {title:'Recuperá tu motivo',instruction:'Antes de abrir la grilla, marcá el ritmo que recordás del capítulo anterior. Pulsá «continuar mi C» y escuchá para comprobarlo.',why:'Recuperar de memoria una idea fortalece lo que vas a usar para componer.',tools:['continue','play','blind']},
    {title:'Repetí el compás',instruction:'Seleccioná el compás 1 y copialo al 2. Escuchá los dos juntos: por ahora la segunda mitad repite exactamente la primera.',why:'Una repetición te da una referencia para escuchar después qué aporta un cambio.',tools:['play','bar','copy']},
    {title:'Inventá una respuesta',instruction:'Conservá tu versión actual. En el compás 2, seleccioná el último ataque y movelo con las flechas a un paso libre, sin cambiar su duración. Alterná las dos versiones y escuchá si el final responde al comienzo.',why:'Una respuesta puede conservar el inicio de una idea y transformar sólo su final.',tools:['play','bar','grid','move','compare']},
    {title:'Probá cuánto dura el final',instruction:'En el compás 2, seleccioná esa última nota. Probá duración de un paso y después una mayor, sin mover su inicio; dejá que termine antes de la barra. Elegí la duración que deje el aire que querés.',why:'El ataque indica cuándo empieza un sonido; su duración indica cuánto sigue sonando.',tools:['play','bar','grid','length']},
    {title:'Elegí tu pregunta y respuesta',instruction:'Activá «repetir» y escuchá cuatro vueltas de los dos compases. Compará tu respuesta con la repetición guardada y elegí; si se perdió la relación, conservá el comienzo y simplificá el final. Comprobá que quede un hueco audible en la respuesta.',why:'Cambiar una sola parte ayuda a escuchar parentesco entre pregunta y respuesta.',tools:['play','bar','grid','keys','length','compare']},
    {title:'Dejá preparada la melodía',instruction:'Anotá qué conserva tu respuesta y qué cambia. Tu versión queda guardada aquí; en el capítulo 3 vas a ponerle distintas alturas sin reemplazar su ritmo.',why:'Separar ritmo y altura permite desarrollar una idea sin perder su identidad.',tools:['reflection','close']}
  ],
  [
    {title:'Elegí tres notas',instruction:'Recordá la pregunta y la respuesta; después continuá tu composición del capítulo 2. Escuchá y elegí tres notas entre Do, Re, Mi, Sol y La: serán tu material melódico.',why:'Una paleta pequeña deja espacio para decidir cómo se mueve tu melodía.',tools:['continue','play','reflection']},
    {title:'Dale alturas a tu ritmo',instruction:'En la comparación de intervalos, probá Do→Mi y Mi→Fa: contá nombres y semitonos desde cada partida. Seleccioná un ataque, pulsá Do para quitarlo y pulsá la nueva nota; repetí en los demás ataques sin sumar acordes. Probá subir, bajar o repetir, manteniendo posiciones y duraciones.',why:'Un intervalo cuenta nombres desde su partida; los semitonos miden su tamaño y el contorno muestra si la frase sube, baja o repite.',tools:['interval','play','bar','grid','keys']},
    {title:'Construí cuatro compases',instruction:'Copiá el compás 1 al 3 y el 2 al 4. Escuchá los cuatro juntos: el gesto vuelve en 3 y, por ahora, 4 repite la respuesta conocida.',why:'Presentar, responder y regresar da forma a una frase con el material que ya compusiste.',tools:['play','bar','copy']},
    {title:'Probá dos finales',instruction:'Conservá tu versión. En el compás 4 cambiá sólo la última altura o quitá el último ataque. Escuchá cada versión completa, atendiendo a 3–4; dejá silencio al final y elegí cuál completa mejor tu gesto.',why:'El final se entiende por lo que lo prepara y por el silencio que deja después.',tools:['play','bar','grid','keys','compare']},
    {title:'Escuchá tu primera pieza entera',instruction:'Escuchá los cuatro compases una sola vez y detené la reproducción antes del reinicio. Ubicá qué vuelve y dónde termina; si parece una vuelta más, acortá la última respuesta o ampliá su silencio. Volvé a escuchar.',why:'Una pieza puede usar un motivo repetido y aun así tener un final deliberado.',tools:['play','bar','grid','keys','length']},
    {title:'Nombrá tu primera miniatura',instruction:'Poné un nombre a la pieza. Anotá una decisión que resolviste sin mirar un ejemplo y cómo inventarías otra respuesta. La próxima pieza empezará con material nuevo.',why:'Transferir un procedimiento significa reutilizar cómo decidís para crear otra música.',tools:['reflection','close']}
  ],
  [
    {title:'Empezá una melodía nueva',instruction:'Empezás la pieza 2 en un espacio vacío. Recordá cómo inventaste pregunta y respuesta y elegí un tempo cómodo; vas a usar la pista 5 para una melodía nueva.',why:'La habilidad que recuperás es organizar una frase; las notas y el ritmo serán nuevos.',tools:['tempo','reflection']},
    {title:'Inventá otra pregunta y respuesta',instruction:'En el compás 1 escribí dos o tres ataques con Do, Re, Mi, Sol o La. Usá un comienzo rítmico distinto al de tu primera pieza. Copiá al compás 2 y cambiá su última nota.',why:'Conservar algo y cambiar el final crea relación entre dos frases nuevas.',tools:['play','bar','grid','keys','length','copy']},
    {title:'Llevá la melodía a cuatro compases',instruction:'Copiá 1 a 3 y 2 a 4. En el compás 4 dejá aire después de la última nota para preparar un final. Escuchá la melodía completa, todavía sin acompañamiento.',why:'La duración y el silencio pueden indicar un cierre antes de agregar acordes.',tools:['play','bar','grid','keys','length','copy']},
    {title:'Compará llegar a Do o a La',instruction:'Conservá una versión que termine en Do y probá cambiar sólo esa última nota por La. Escuchá ambos finales con el mismo ritmo y lo que viene antes. Si añadís una referencia grave, usá el mismo Do bajo ambos finales; luego retiralo y reescuchá.',why:'Cambiar sólo la última altura permite escuchar su efecto sin confundirlo con un cambio de bajo.',tools:['play','bar','grid','keys','track','octave','compare']},
    {title:'Prepará la llegada elegida',instruction:'Volvé a pista 5 y octava base. Elegí el final que sirva a tu frase, aunque sea provisional. Escuchá los cuatro compases; si necesitás más dirección, cambiá sólo la nota anterior a ese final y volvé a escuchar.',why:'El centro de una frase se construye con apoyos y contexto; su última nota sola no demuestra la tonalidad.',tools:['play','track','bar','grid','keys','octave','compare']},
    {title:'Ubicá una nota en la escala',instruction:'Anotá la nota final y otra que dure bastante. Ubicá esa nota en Do mayor: Do=1, Re=2, Mi=3, Fa=4, Sol=5, La=6, Si=7. En la comparación de intervalos, mantené Mi y cambiá la partida: su grado en Do mayor sigue siendo 3.',why:'El grado se cuenta desde el inicio de la escala; un intervalo se mide desde la nota que elegís como partida.',tools:['interval','reflection','close']}
  ],
  [
    {title:'Recuperá tu llegada',instruction:'Continuá tu composición del capítulo 4 y escuchá la melodía. Recordá la nota de llegada elegida; ahora vas a acompañarla en la pista 4, conservando la pista 5.',why:'Mantener la melodía te deja escuchar qué aporta el acompañamiento.',tools:['continue','play','track']},
    {title:'Construí dos acordes',instruction:'En pista 4, compás 1, ingresá Do–Mi–Sol en un mismo paso y escuchá: ese acorde se llama C. Conservá la versión y probá La–Do–Mi en su lugar: Am. Mantené Mi como referencia y contá desde cada raíz: es tercera de Do y quinta de La.',why:'Una tríada tiene raíz, tercera y quinta: mayor = 0/4/7 semitonos desde la raíz; menor = 0/3/7.',tools:['interval','triad','play','track','bar','grid','keys','length','compare']},
    {title:'Elegí el apoyo de tu melodía',instruction:'Localizá una nota larga o final y escuchá ese momento con C y con Am: atendé a si descansa, roza o pide seguir. Elegí un acorde provisional y escribí un acompañamiento al inicio de cada compás; podés repetirlo. Si no distinguís, usá la escucha guiada de abajo y dejá la elección provisional.',why:'Mi pertenece a C y Am; Sol pertenece a C pero queda fuera de Am, así que cada nota puede relacionarse de otra manera con el acompañamiento.',tools:['listening','play','track','bar','grid','keys','length','compare']},
    {title:'Cambiá un solo acorde',instruction:'Conservá tu versión. Sustituí únicamente el acorde del compás 2 o 3 por el otro color y alterná las dos versiones. Escuchá tu nota importante y cómo sigue la frase, manteniendo melodía, tempo y duraciones.',why:'Cambiar un solo acorde permite atribuirle lo que escuchás en el recorrido.',tools:['play','track','bar','grid','keys','compare']},
    {title:'Elegí y probá construir sin copiar',instruction:'Escuchá los cuatro compases y elegí el acompañamiento; si aún dudás, conservá el original como provisional. Si tapa la melodía, acortá sus notas y reescuchá. En los últimos dos minutos, construí Re menor en el ejercicio de abajo sin copiar sus notas y usá la comprobación.',why:'La fórmula menor funciona desde otra raíz: practicarla sin copiar muestra qué entendiste.',tools:['triad','play','track','bar','grid','length','compare']},
    {title:'Dejá una duda bien localizada',instruction:'Anotá los cuatro acordes elegidos y completá «En el compás…, la nota… tiene apoyo / roza / todavía no distingo». Registrá también si construiste Re menor solo o después de corregir: Re–Fa–La. El próximo capítulo retoma esa relación musical.',why:'Una duda localizada indica qué escuchar después; no hace falta fingir una diferencia que todavía no percibís.',tools:['reflection','close']}
  ],
  [
    {title:'Elegí una nota para revisar',instruction:'Continuá tu composición del capítulo 5 y escuchá la duda que anotaste. Localizá una nota larga, acentuada o final y nombrá la nota y el acorde que suena debajo.',why:'Una nota destacada permite escuchar con claridad su relación con la armonía.',tools:['continue','play','track','bar','grid','reflection']},
    {title:'Probá cambiar la melodía',instruction:'Conservá tu versión y comprobá si la nota elegida pertenece al acorde; nombrá la raíz desde la que contás. Cambiá sólo esa altura por una nota cercana del acorde, manteniendo inicio y duración. Alterná las versiones: escuchá primero apoyo o roce y después cómo sigue la frase.',why:'Mi es grado 3 de Do mayor, tercera de C y quinta de Am: escala y acorde usan referencias distintas.',tools:['play','track','bar','grid','keys','compare']},
    {title:'Probá cambiar el acorde',instruction:'Anotá qué produjo la variante melódica y recuperá el original. En ese mismo compás, probá cambiar el acorde por el otro conocido sin tocar la melodía. Elegí entre cambiar la nota, cambiar el acorde o conservar lo anterior.',why:'Una tensión puede resolverse de distintas maneras o mantenerse si cumple tu intención.',tools:['play','track','bar','grid','keys','compare','reflection']},
    {title:'Dejá oír la melodía',instruction:'Escuchá los cuatro compases. Si un acorde tapa la llegada, quitá una de sus notas o acortá su duración en ese lugar. Reescuchá antes de modificar otra pista.',why:'El acompañamiento puede dar apoyo y dejar espacio al mismo tiempo.',tools:['play','track','bar','grid','keys','length']},
    {title:'Elegí el final de la pieza',instruction:'Conservá tu versión y probá otra última altura o una respuesta final más corta. Escuchá una pasada de cada versión, detenela antes del reinicio y elegí el cierre sin consultar una frase resuelta.',why:'Escuchar el final dentro de la pieza permite decidir si completa el recorrido que querías.',tools:['play','track','bar','grid','keys','length','compare']},
    {title:'Contá qué mejoraste',instruction:'Poné un nombre a tu segunda miniatura y anotá «qué escuché → qué cambié → qué pasó». Indicá si decidiste solo o con ayuda. La próxima pieza usará material nuevo y una llegada armónica.',why:'Relacionar una observación con una prueba convierte una corrección en un método que podés repetir.',tools:['reflection','close']}
  ],
  [
    {title:'Elegí un recorrido nuevo',instruction:'Empezás la pieza 3 en un espacio vacío. Recordá una decisión de llegada de la pieza anterior y escribí una intención nueva para cuatro compases: presentar, alejarte y volver.',why:'Definir una intención te da un criterio para elegir entre recorridos armónicos.',tools:['tempo','reflection']},
    {title:'Escribí el recorrido de acordes',instruction:'En pista 4, escribí un acorde al principio de cada compás: C, F, G y C. Sus notas son Do–Mi–Sol; Fa–La–Do; Sol–Si–Re; Do–Mi–Sol. Usá una duración simple dentro de cada barra y escuchá el recorrido.',why:'En Do mayor, C es I, F es IV y G es V: estos números nombran acordes construidos sobre grados de la escala.',tools:['play','track','bar','grid','keys','length']},
    {title:'Inventá una melodía sobre el recorrido',instruction:'En pista 5, inventá dos o tres ataques en el compás 1. Reescribí ese gesto en 2 y 3 cambiando una llegada; en 4 respondé con menos ataques y aire. Escribí sólo en pista 5 para conservar los acordes que ya elegiste.',why:'El mismo gesto melódico puede tomar otro sentido sobre cada acorde.',tools:['play','track','bar','grid','keys','length']},
    {title:'Compará volver o quedar abierto',instruction:'Conservá tu versión. En el compás 4 cambiá sólo el acorde C por G, manteniendo la melodía. Escuchá completas las dos versiones, atendiendo a 3–4, y describí cuál parece dejar más continuidad.',why:'Volver de V a I puede afirmar una llegada; quedarse en V puede prolongar la espera.',tools:['play','track','bar','grid','keys','compare']},
    {title:'Decidí cómo llega tu frase',instruction:'Elegí el acorde final según tu intención. Si querés reforzar la llegada, conservá la versión y probá terminar la melodía en una nota de ese acorde. Compará y quedate sólo con el cambio que ayude.',why:'La armonía propone dirección; melodía, ritmo y silencio completan el efecto del final.',tools:['play','track','bar','grid','keys','compare']},
    {title:'Anotá tu dirección elegida',instruction:'Escribí el recorrido de acordes y qué escuchás en los dos últimos compases. Tu borrador queda guardado; en el capítulo 8 conservarás sus acordes y melodía para revisar el registro.',why:'Separar qué acorde elegís de cómo distribuís sus notas permite revisar una decisión por vez.',tools:['reflection','close']}
  ],
  [
    {title:'Encontrá un salto para revisar',instruction:'Continuá tu composición del capítulo 7 y escuchá sin editar. Elegí un cambio de acorde cuyo salto de registro te distraiga y conservá tu versión antes de modificarlo.',why:'Una comparación necesita un punto concreto y una referencia recuperable.',tools:['continue','play','track','bar','compare','reflection']},
    {title:'Redistribuí el mismo acorde',instruction:'En pista 4, probá mover una o dos notas del acorde elegido a otra octava: quitá la nota, cambiá la octava y volvé a ingresarla. Conservá sus nombres, ataques y duraciones. Compará las dos disposiciones con la misma melodía.',why:'Una octava cambia el registro de una nota; el acorde conserva sus clases de altura.',tools:['play','track','bar','grid','keys','octave','compare']},
    {title:'Seguí una voz',instruction:'Escuchá primero la nota más baja de cada disposición y después las superiores. Buscá una nota compartida con el acorde anterior o un movimiento corto. Elegí si esa continuidad ayuda a tu frase.',why:'La conducción de voces sigue cómo cada nota de un acorde llega al siguiente.',tools:['play','track','bar','grid','compare']},
    {title:'Revisá un segundo enlace',instruction:'Elegí otro cambio de acorde y aplicá el mismo criterio: conservar una nota común o acercar una voz. Probá otra disposición manteniendo tu melodía y los nombres del acorde. Escuchá el recorrido completo, atendiendo al enlace elegido.',why:'Los movimientos cortos pueden dar continuidad; un salto también sirve si su efecto es deliberado.',tools:['play','track','bar','grid','keys','octave']},
    {title:'Elegí por continuidad y espacio',instruction:'Alterná la versión heredada y tu arreglo actual, escuchando los cuatro compases. Si un acorde tapa la melodía, probá otro registro. Restaurá el original si el cambio pierde claridad.',why:'La disposición que menos se mueve sólo conviene si también deja escuchar lo que querés destacar.',tools:['play','track','bar','grid','keys','octave','compare']},
    {title:'Describí una línea real',instruction:'Escribí cómo se mueve una voz de tu arreglo, por ejemplo «Do permanece y Mi sube a Fa». Señalá la llegada que querés revisar en el próximo capítulo; tu versión queda guardada.',why:'Nombrar un movimiento que existe en tu pieza muestra qué decisión musical tomaste.',tools:['reflection','close']}
  ],
  [
    {title:'Elegí el acorde que prepara el final',instruction:'Continuá tu composición del capítulo 8 y recordá su llegada antes de escucharla. Elegí el G que prepara el final; vas a conservar la melodía y los demás acordes.',why:'Probar un color en una transición concreta deja escuchar para qué sirve.',tools:['continue','play','track','bar','grid']},
    {title:'Añadí una séptima',instruction:'En ese G, añadí Fa para formar G7: Sol–Si–Re–Fa. Conservá una referencia y compará quitando y reponiendo sólo Fa. Mantené las demás notas, ataques y duraciones.',why:'G7 añade una séptima menor a la tríada G: es una nota nueva que cambia el color del conjunto.',tools:['play','track','bar','grid','keys','octave','compare']},
    {title:'Escuchá hacia dónde va Fa',instruction:'Si después viene C, probá que su Mi quede cerca del Fa de G7 y escuchá Fa→Mi. Si tu final seguía en G, conservá la versión y probá llegar a C. Compará con el final anterior antes de elegir.',why:'En G7→C, Fa puede bajar a Mi y Si subir a Do: esas líneas pueden hacer audible la llegada.',tools:['play','track','bar','grid','keys','octave','compare']},
    {title:'Elegí color y cierre',instruction:'Elegí G o G7 y el final que sirva a tu intención. Ajustá sólo la última respuesta melódica o su silencio si hace falta terminar la frase. No sumes otro recurso durante esta prueba.',why:'Una séptima aporta una relación nueva; conservar la tríada también puede ser la mejor elección.',tools:['play','track','bar','grid','keys','octave','length','compare']},
    {title:'Escuchá la tercera pieza entera',instruction:'Reproducí una pasada completa y detenela antes del reinicio. Comprobá la dirección del final y una línea interna; si la séptima distrae, retirala y escuchá si conservás el recorrido.',why:'Un recurso queda justificado por lo que aporta a la pieza completa.',tools:['play','track','bar','grid','keys','octave']},
    {title:'Guardá tu método para probar colores',instruction:'Anotá qué hizo Fa y por qué lo conservaste o lo descartaste. Describí cómo probarías otro color sin reescribir toda la pieza. Tu tercera miniatura queda terminada.',why:'Cambiar una sola nota y comparar en contexto es un método reutilizable.',tools:['reflection','close']}
  ],
  [
    {title:'Definí un groove nuevo',instruction:'Empezás la pieza 4 en un espacio vacío. Elegí un tempo cómodo y recordá una manera de dejar aire. Escribí qué ataque o gesto te gustaría que se recuerde.',why:'Un riff gana identidad al repetirse; su espacio también forma parte del gesto.',tools:['tempo','reflection']},
    {title:'Escribí riff y respuesta',instruction:'En pista 5, inventá dos o tres ataques en el compás 1 usando Do, Mi, Sol o La. Escribí una respuesta en 2 que conserve un rasgo y deje espacio después. Usá un ritmo nuevo respecto de tus piezas anteriores.',why:'Frasear es decidir ataques, duraciones y pausas alrededor del pulso.',tools:['play','bar','grid','keys','octave','length']},
    {title:'Sumá un apoyo mínimo',instruction:'Copiá 1 a 3 y 2 a 4. Añadí una nota grave en pista 3 o un acorde conocido en pista 4 y repetilo en los cuatro compases. Escuchá si sostiene el riff sin llenar sus huecos.',why:'Un groove puede funcionar con pocas capas si cada una deja espacio a las otras.',tools:['play','track','bar','grid','keys','octave','length','copy']},
    {title:'Probá una decisión de fraseo',instruction:'Conservá tu versión y seleccioná el primer ataque del riff. Movelo un paso hacia adelante, a un paso libre y sin pasar la barra. Alterná las versiones y elegí cómo preferís que entre la frase.',why:'Entrar antes o después del pulso cambia el fraseo sin exigir más notas ni una forma de doce compases.',tools:['play','track','bar','grid','move','compare']},
    {title:'Elegí el gesto y su espacio',instruction:'Elegí la variante y escuchá los cuatro compases. Si un ataque del acompañamiento invade la respuesta, quitálo y compará. Comprobá que el riff siga reconocible y el pulso continúe durante el aire.',why:'Quitar un ataque puede hacer más clara la relación entre riff y respuesta.',tools:['play','track','bar','grid','keys','octave','compare']},
    {title:'Anotá qué vas a conservar',instruction:'Anotá el rasgo que hace reconocible tu groove: ritmo inicial, contorno o silencio. Tu versión queda guardada; en el capítulo 11 la vas a desarrollar hasta ocho compases.',why:'Elegir un rasgo de identidad te permite variar sin perder la idea original.',tools:['reflection','close']}
  ],
  [
    {title:'Recuperá la identidad del riff',instruction:'Recordá el riff y continuá tu composición del capítulo 10. Escuchá sus cuatro compases; nombrá qué aporta cada pista activa y el rasgo del riff que vas a conservar.',why:'Reconocer la función de cada capa te ayuda a desarrollar la pieza con intención.',tools:['continue','play','track','reflection']},
    {title:'Duplicá la primera mitad',instruction:'Copiá todas las pistas de 1→5, 2→6, 3→7 y 4→8. Escuchá los ocho compases y conservá esta versión. Por ahora tenés A y su repetición exacta.',why:'A ocupa cuatro compases y su repetición otros cuatro: la referencia completa suma ocho.',tools:['play','bar','copy','compare']},
    {title:'Transformá sólo la segunda mitad',instruction:'En 5–8 elegí una transformación: mover el riff una octava, acortar sus respuestas o retirar un ataque de acompañamiento. Aplicá sólo esa transformación. Conservá 1–4 y el rasgo de identidad que elegiste.',why:'A′ es una variante reconocible de A; desarrollar no exige inventar otra idea en cada compás.',tools:['play','track','bar','grid','keys','length','octave']},
    {title:'Comprobá que todavía sea tu riff',instruction:'Escuchá una pasada completa, atendiendo al paso de 4 a 5 y a la segunda mitad. Si la variación borró el riff, recuperá su comienzo en 5 y 7; si no se escucha diferencia, hacé más clara la transformación elegida.',why:'Una variación necesita parentesco y una diferencia que se pueda reconocer.',tools:['play','track','bar','grid','keys','length','octave','compare']},
    {title:'Elegí entre repetición y variación',instruction:'Compará la versión guardada A+A con tu versión A+A′, una pasada completa de cada una. Elegí por identidad y aire. Volvé a 1–4 y comprobá que esa primera mitad siga intacta.',why:'Escuchar las dos mitades juntas muestra qué función cumple el cambio en la forma.',tools:['play','bar','compare']},
    {title:'Dejá localizado el cierre',instruction:'Anotá qué conserva A′, qué cambia y dónde sentís que todavía falta terminar la frase. Tu pieza de ocho compases queda guardada; el próximo capítulo trabaja ese cierre.',why:'Localizar una necesidad musical convierte la próxima sesión en una tarea concreta.',tools:['reflection','close']}
  ],
  [
    {title:'Escuchá el recorrido completo',instruction:'Continuá tu composición del capítulo 11 y escuchá los ocho compases sin editar. Señalá cuándo entra la variación y en qué momento esperás que termine la pieza.',why:'La forma se reconoce por lo que vuelve, lo que cambia y lo que concluye.',tools:['continue','play','reflection']},
    {title:'Probá aire antes de la variación',instruction:'Conservá tu versión. Al final del compás 4, quitá un ataque de acompañamiento; si no hay uno, acortá el apoyo sostenido para dejar un pulso de aire. Escuchá una pasada completa de cada versión, atendiendo a 4→5, y elegí.',why:'Una retirada puede hacer más clara la entrada siguiente sin agregar material.',tools:['play','track','bar','grid','keys','octave','length','compare']},
    {title:'Escribí un primer final',instruction:'En el compás 8, probá menos ataques y una última nota de llegada. Escuchá una pasada completa, atendiendo a 7–8, y dejá silencio después del final. Conservá esta versión para compararla con otra.',why:'El cierre depende de cómo termina la frase y de qué espacio deja después.',tools:['play','track','bar','grid','keys','octave','length','compare']},
    {title:'Probá otro final más corto',instruction:'Desde esa respuesta, probá una frase más corta y más silencio en el compás 8. Alterná los dos finales sin cambiar 1–7. Elegí el que complete mejor el efecto que buscás.',why:'Comparar dos cierres con el mismo contexto permite escuchar qué aporta cada uno.',tools:['play','track','bar','grid','keys','octave','length','compare']},
    {title:'Terminá el groove',instruction:'Escuchá una sola pasada y detenela antes de repetir. Comprobá que el riff se reconozca y haya aire entre frases. Corregí un único ataque si todavía estorba al cierre.',why:'Un bucle que funciona y una pieza que termina cumplen funciones distintas; ahora elegís su versión con final.',tools:['play','track','bar','grid','keys','octave','move']},
    {title:'Nombrá la cuarta miniatura',instruction:'Poné un nombre a la pieza e indicá un tramo donde podrías improvisar dejando volver el riff. Anotá una decisión que resolviste sin ejemplo. La próxima composición nace de tu propio encargo.',why:'Reconocer el espacio para improvisar también ayuda a entender la función del riff.',tools:['reflection','close']}
  ],
  [
    {title:'Escribí tu propio encargo',instruction:'Empezás la pieza 5 en un espacio vacío. Elegí tema instrumental o groove, describí una intención que puedas escuchar y nombrá dos herramientas conocidas que usarás. Elegí tempo y hasta cuatro roles; podés empezar con uno o dos.',why:'Un encargo útil describe un efecto audible y sirve para evaluar tus decisiones.',tools:['tempo','track','reflection']},
    {title:'Inventá y elegí un germen',instruction:'Inventá una idea de un compás en pista 5 para melodía o pista 3 para bajo/riff. Conservála y escribí una segunda idea con ritmo o contorno nuevos. Alterná ambas y elegí por una razón vinculada a tu encargo.',why:'Elegir entre ideas propias entrena el criterio que vas a usar sin una receta.',tools:['play','track','bar','grid','keys','octave','length','compare']},
    {title:'Armá el borrador de ocho compases',instruction:'Copiá la idea elegida al compás 2 y transformala en respuesta. Copiá 1→3 y 2→4; después 1→5, 2→6, 3→7 y 4→8. Escuchá el recorrido completo.',why:'Una idea breve y su respuesta pueden sostener una forma mayor mediante repetición.',tools:['play','track','bar','grid','keys','octave','length','copy']},
    {title:'Añadí el soporte necesario',instruction:'Elegí sólo lo que necesite tu idea: armonía en pista 4, bajo en 3 o batería en 1. Escribí ese soporte en 1–2 y repetilo en los otros pares con la copia de compás. Nombrá qué aporta cada pista y dejá libre lo innecesario.',why:'Una capa tiene sentido por su función, no por completar una lista de instrumentos.',tools:['play','track','bar','grid','keys','octave','length','copy','reflection']},
    {title:'Elegí la base con más claridad',instruction:'Escuchá los ocho compases. Probá quitar un ataque de la capa nueva y reponerlo; elegí por la claridad de tu idea principal. Anotá qué te gustaría transformar en 5–8 para desarrollar el encargo.',why:'Retirar y reponer material deja comprobar qué función cumple realmente.',tools:['play','track','bar','grid','keys','octave','reflection']},
    {title:'Dejá escrito el próximo cambio',instruction:'Anotá tu encargo, los roles activos y una próxima acción con lugar: «En 5–8 voy a…». Conservá el borrador como referencia para comparar después; tu composición queda guardada aquí.',why:'Una intención se vuelve practicable cuando indica qué probar y dónde.',tools:['compare','reflection','close']}
  ],
  [
    {title:'Decidí qué conservar y qué cambiar',instruction:'Continuá tu composición del capítulo 13 y recuperá tu encargo. Escuchá las dos mitades y nombrá un rasgo de 1–4 que conservarás y una sola variable que transformarás en 5–8.',why:'El contraste funciona cuando todavía permite reconocer una relación con lo anterior.',tools:['continue','play','reflection']},
    {title:'Conservá una referencia',instruction:'Pulsá «conservar mi versión actual» antes de variar. El capítulo anterior mantiene su propia composición y acá editarás la segunda mitad de esta copia. Si también usás el OP–XY, copiá los patrones que vas a modificar y seleccioná esas copias.',why:'Una versión recuperable permite elegir por comparación y conservar el original.',tools:['compare']},
    {title:'Transformá los compases 5 a 8',instruction:'Aplicá el cambio elegido de registro, textura, ritmo o armonía únicamente a 5–8. Conservá 1–4 y el rasgo de identidad que anotaste. Escuchá antes de sumar otra transformación.',why:'Cambiar una variable hace más claro qué aporta a tu intención.',tools:['play','track','bar','grid','keys','length','move','octave']},
    {title:'Escuchá si las mitades se relacionan',instruction:'Compará la pieza completa con el borrador guardado. Si se perdió el parentesco, recuperá en 5 o 7 el ritmo inicial o una respuesta reconocible. Volvé a escuchar el mismo recorrido.',why:'Una segunda mitad puede contrastar sin convertirse en una idea desconectada.',tools:['play','track','bar','grid','keys','octave','length','move','compare']},
    {title:'Elegí según tu encargo',instruction:'Decidí si la transformación cumple la intención que escribiste. Conservá la versión nueva o recuperá la anterior. Volvé a escuchar 1–4 y comprobá que esa primera mitad siga como la elegiste.',why:'Restaurar el original también demuestra criterio si el cambio no aporta lo que buscabas.',tools:['play','bar','compare']},
    {title:'Localizá el paso entre mitades',instruction:'Completá «Se conserva…; cambia…» y describí qué escuchás al pasar de 4 a 5. Tu versión queda guardada; en el capítulo 15 decidirás si ese límite necesita preparación.',why:'Describir un límite concreto permite revisar la transición sin cambiar toda la forma.',tools:['reflection','close']}
  ],
  [
    {title:'Definí qué necesita la entrada',instruction:'Continuá tu composición del capítulo 14 y escuchá una pasada completa, atendiendo a 3–6. Escribí qué esperás al llegar a 5: una entrada más clara, más aire o continuidad. Si ya funciona, tomá esa versión como referencia.',why:'Una transición sirve a una función; no siempre necesita material nuevo.',tools:['continue','play','bar','reflection']},
    {title:'Probá una retirada',instruction:'Conservá tu versión. En el último pulso del compás 4, quitá un ataque de acompañamiento; si hay una sola voz, acortá allí su última nota. Conservá el comienzo del compás 5.',why:'Quitar material antes de una entrada puede hacerla más legible.',tools:['play','track','bar','grid','keys','octave','length','compare']},
    {title:'Elegí la transición',instruction:'Escuchá una pasada completa con y sin la retirada, atendiendo a 3–6. Elegí una versión y explicá qué cambia al entrar en 5. Recuperá el original si la prueba no mejora esa entrada.',why:'Escuchar a ambos lados del límite permite evaluar una transición en contexto.',tools:['play','bar','compare','reflection']},
    {title:'Prepará el final propio',instruction:'Conservá tu versión y prepará el cierre en 8: una llegada conocida, una respuesta más corta o un silencio posterior. Probá una alternativa y escuchá ambas completas, atendiendo a 7–8. Elegí cuál completa tu encargo.',why:'El cierre organiza la última frase y el silencio que viene después.',tools:['play','track','bar','grid','keys','octave','length','compare']},
    {title:'Escuchá transición y final juntos',instruction:'Reproducí 1–8 una sola vez y detené antes del reinicio. Comprobá que la preparación deje oír la entrada y que el final se entienda. Corregí sólo el problema más claro.',why:'Revisar el recorrido completo evita mejorar un fragmento a costa de la pieza.',tools:['play','track','bar','grid','keys','octave','length','move']},
    {title:'Dejá una revisión para otra escucha',instruction:'Anotá un punto que quieras revisar con distancia. Conservá esta versión completa: será la referencia antes/después del último capítulo.',why:'Una escucha nueva ayuda a elegir qué merece una corrección y qué ya funciona.',tools:['compare','reflection','close']}
  ],
  [
    {title:'Diagnosticá un solo problema',instruction:'Continuá tu composición del capítulo 15 y escuchá una pasada sin editar. Volvé a tu encargo y elegí un problema observable de identidad, aire, llegada, roles, forma o cierre. Localizálo en un compás y conservá la versión.',why:'«No se entiende el motivo en 6» permite una prueba; un juicio general todavía no localiza una causa.',tools:['continue','play','compare','reflection']},
    {title:'Probá una corrección propia',instruction:'Proponé una causa para ese problema. En el lugar elegido, cambiá una sola variable: ataque, duración, altura, registro o presencia de una voz. Consultá una ayuda puntual sólo si necesitás destrabarte.',why:'Una corrección se comprueba mejor cuando podés señalar exactamente qué cambiaste.',tools:['play','track','bar','grid','keys','length','move','octave']},
    {title:'Comprobá antes y después',instruction:'Escuchá completas tu versión guardada y la corregida, atendiendo al mismo tramo. Conservá el cambio si mejora tu intención. Recuperá la referencia si empeora o si todavía no reconocés una mejora.',why:'La comparación permite decidir por un efecto audible, no por haber invertido esfuerzo en editar.',tools:['play','bar','compare']},
    {title:'Cerrá la quinta miniatura',instruction:'Escuchá los ocho compases una sola vez y dejá el final en silencio. Comprobá el problema elegido y un criterio que ya trabajaste. Si queda una corrección evidente, hacela sin ampliar la pieza.',why:'Terminar también es reconocer cuándo el encargo ya está cumplido.',tools:['play','track','bar','grid','keys','octave','length','move']},
    {title:'Documentá tu pieza terminada',instruction:'Anotá nombre, intención y «qué escuché → qué cambié → qué pasó». Registrá qué pudiste decidir solo; si usaste el OP–XY, guardá allí el proyecto. Conservá esta pieza y prepará un espacio vacío aparte para una idea nueva.',why:'La autonomía consiste en elegir, probar y comprobar; consultar nombres o controles sigue permitido.',tools:['reflection','close']},
    {title:'Empezá otra idea por tu cuenta',instruction:'En la nota de abajo, inventá dos compases de pregunta, respuesta y final con material nuevo: escribí cada evento como «compás / paso / nota / duración». Cambiá el punto de partida: si antes empezaste por melodía, ahora usá ritmo o bajo; si empezaste por groove, ahora melodía. Escribí una grilla legible sin consultar frases resueltas y anotá la ayuda musical que necesitaste; tu quinta pieza queda conservada.',why:'Transferir es crear material nuevo con un procedimiento conocido; cambiar sólo tempo, sonido o tonalidad no lo demuestra.',tools:['reflection','close']}
  ]
];
