// Sixteen chapters, five finished pieces. A/B demonstrate one audible decision;
// C is the learner's composition and continues only inside its current cycle.
const cloneEvents=events=>events.map(e=>({...e,notes:[...e.notes]}));
function event(t,b,s,notes,len=4){return {t,at:b*16+s-1,notes:[...notes],len};}
const CHORDS={C:[60,64,67],Am:[57,60,64],F:[53,57,60],G:[55,59,62],Dm7:[60,62,65,69],G7:[59,62,65,67],Cmaj7:[60,64,67,71],C7:[60,64,67,70],F7:[53,57,60,63],V7:[55,59,62,65]};
const roots={C:48,Am:45,F:41,G:43,Dm7:50,G7:43,Cmaj7:48,C7:48,F7:41,V7:43};
function harmony(names,bass=false){return names.flatMap((n,b)=>[event(4,b,1,CHORDS[n],16),...(bass?[event(3,b,1,[roots[n]],16)]:[])]);}
const BLUES=['C7','C7','C7','C7','F7','F7','C7','C7','V7','F7','C7','C7'];
const STAGES=['pulso y respuesta','melodía y centro','acordes y cierre','dirección y voces','color y groove','desarrollo y forma','base y contraste','arreglo y revisión'];
const lessonPlans=[
 {title:'Inventar un ritmo y dejar aire',bars:1,tempo:75,main:5,form:['motivo y silencio'],
  goal:'Empezar la pieza 1 con una idea rítmica propia de un compás.',
  recall:'En un proyecto vacío, marcá cuatro pulsos con el pie y tocá una tecla en dos de ellos. No necesitás recordar escalas ni cantar.',
  question:'¿B va más lento o deja más espacio?',
  answer:'A y B tienen el mismo tempo y duración. B omite dos ataques; el pulso continúa. Elegí qué cantidad de espacio sirve a tu idea.',
  ideas:[['Pulso y tempo','El pulso es la referencia regular que podés seguir con el pie. El tempo indica cuántos pulsos pasan por minuto. A 75 BPM, cuatro pulsos duran 3,2 segundos aunque toques una sola vez.'],['Compás y ataque','Aquí usamos 4/4: cuatro pulsos forman un compás. Un ataque es el inicio de un sonido; no es lo mismo que un pulso. El silencio también ocupa tiempo.'],['Tu mapa temporal','En esta grilla un compás tiene 16 pasos, cuatro por pulso. Los comienzos son 1, 5, 9 y 13. Usá Do como sonido de prueba; hoy no hace falta construir un acorde.']],
  map:[['pulso','1','2','3','4'],['paso inicial','1','5','9','13']],
  task:'Con Do, elegí dos o tres de los pasos 1, 5, 9 y 13. Usá notas cortas y dejá un pulso completo de silencio. Repetí cuatro vueltas sin cambiar el tempo.',
  challenge:'En C escribí tu ritmo desde vacío. Quitá o mové un ataque, compará y conservá una versión. Ese compás será el comienzo de la pieza 1.',
  check:'Puedo seguir cuatro pulsos durante los silencios y señalar qué ataque elegí cambiar.',
  transfer:'Antes del próximo capítulo intentá tocar tu motivo sin mirar. Si no sale exacto, recuperá su gesto principal y después comprobá.',
  hint:'Si te perdés, empezá con Do corto en 1 y 9. Probá sumar 13 y escuchá el reinicio.',
  events:[1,5,9,13].map(s=>event(5,0,s,[60],2)),compare:'B / dos ataques menos',variation:e=>e.filter(x=>x.at===0||x.at===8),
  quiz:['¿Quitar un ataque cambia los BPM?',['No: cambia el ritmo.','Sí: el tempo baja.'],0,'El tempo sostiene el pulso. Los ataques deciden qué ocurre sobre él.'],
  takeaway:'Pieza 1 en proceso: un compás propio en pista 5, con un silencio audible. Guardalo para continuarlo en el capítulo 2.'},
 {title:'Darle una respuesta al motivo',bars:2,tempo:75,main:5,form:['pregunta','respuesta'],
  goal:'Continuar la pieza 1: convertir tu compás en dos compases relacionados.',
  recall:'Recuperá tu motivo del capítulo 1 antes de escuchar el modelo. Conservá sus ataques al empezar.',
  question:'¿Qué cambia cuando se mueve sólo el último ataque de la respuesta?',
  answer:'A repite el primer compás. B conserva los primeros ataques y mueve el último de 11 a 13. La pregunta sigue reconocible; cambia el lugar donde termina la respuesta.',
  ideas:[['Motivo','Un motivo es una idea breve que podemos reconocer. Puede tener una sola altura. La respuesta conserva un rasgo y transforma otro: no necesita inventar todo de nuevo.'],['Subdivisión','El paso 7 divide por la mitad el segundo pulso: 5 lo inicia y 9 inicia el siguiente. Un ataque entre pulsos cambia el ritmo sin acelerar el tempo.'],['Duración y silencio','El ataque decide cuándo comienza la nota; la duración decide hasta cuándo sigue. Un paso sin ataque puede contener una nota sostenida. Para dejar aire, escuchá el final del sonido anterior.']],
  map:[['un pulso','inicio','¼','½','¾'],['pulso 2','5','6','7','8']],
  task:'Copiá tu primer compás al segundo. Modificá sólo el último ataque o su duración. Compará la repetición exacta con esa respuesta.',
  challenge:'Guardá pregunta y respuesta de dos compases, todavía con una altura. Conservá un rasgo común y un pulso de silencio audible; explicá dónde responde la segunda parte.',
  check:'Puedo reconocer la pregunta en la respuesta y distinguir mover, alargar y quitar un ataque.',
  transfer:'Inventá una segunda respuesta sin mirar A/B. Elegí una para continuar la pieza y guardá la otra como alternativa.',
  hint:'Continuá tu C anterior y copiá el compás 1 al 2. Si no sabés qué mover, probá el último ataque más tarde y escuchá el hueco que queda.',
  events:[0,1].flatMap(b=>[event(5,b,1,[60],2),event(5,b,7,[60],2),event(5,b,11,[60],3)]),compare:'B / último ataque desplazado',variation:e=>e.map(x=>x.at===26?{...x,at:28}:x),
  quiz:['Un paso sin ataque, ¿siempre está en silencio?',['Sí.','No: puede seguir sonando una nota anterior.'],1,'Comprobá la duración del sonido que empezó antes.'],
  takeaway:'Pieza 1 en proceso: pregunta y respuesta propias de dos compases en pista 5. El capítulo 3 conserva ese ritmo y añade alturas y cierre.'},
 {title:'Poner alturas y terminar tu primera pieza',bars:4,tempo:75,main:5,form:['presentar','responder','retomar','concluir'],
  goal:'Terminar la pieza 1: una miniatura melódica de cuatro compases.',
  recall:'Continuá tu frase de dos compases. Tocá su ritmo antes de elegir alturas; ésa es la identidad que vas a desarrollar.',
  question:'¿Qué cambia al terminar la misma frase en Do o en Re?',
  answer:'A termina en Do y B cambia sólo esa última altura a Re. En esta frase que vuelve sobre Do, A puede sentirse más asentada; B deja otro grado de continuidad. Escuchá toda la frase antes de elegir.',
  ideas:[['Distancias','Un semitono es un salto entre teclas consecutivas, como Mi→Fa; un tono son dos. Para medir Do→Mi, Do empieza en 0 y contamos cuatro saltos: Do♯, Re, Mi♭, Mi. Para nombrar el intervalo contamos nombres e incluimos ambos extremos: Do (1), Re (2), Mi (3). Por eso es una tercera, de cuatro semitonos.'],['Contorno','Subir, bajar y repetir dibujan una melodía. Un salto puede destacar una nota y el movimiento por notas cercanas conectar el recorrido. Elegí tres alturas de Do, Re, Mi, Sol y La; no es necesario usar todas.'],['Cerrar una frase','Cuatro compases pueden presentar, responder, retomar y concluir. Un final puede cambiar la última nota, reducir ataques o dejar silencio. Repetir material propio también construye forma.']],
  map:[['recorrido','Do→Re','Do→Mi','Do→Sol'],['semitonos','2','4','7']],
  task:'Asigná alturas a tu ritmo sin mover sus ataques. Copiá los dos compases a 3–4 y cambiá el final. Escuchá una pasada completa con repetición desactivada.',
  challenge:'Terminá cuatro compases con un motivo reconocible, una respuesta y un final elegido. Guardá la pieza 1 y una alternativa de cierre. No necesita acordes ni batería.',
  check:'Puedo señalar qué vuelve, dónde cambia el contorno y qué hace que la última respuesta sea un final.',
  transfer:'En un patrón aparte, inventá otra respuesta con menos ayuda. En la pieza 2 usarás el procedimiento con un motivo nuevo, sin copiar estas notas.',
  hint:'Elegí tres alturas. Conservá tu pregunta, repetila en el compás 3 y dejá silencio después de la última nota del 4.',
  events:[event(5,0,1,[60],2),event(5,0,7,[64],2),event(5,0,11,[67],3),event(5,1,1,[67],2),event(5,1,7,[64],2),event(5,1,13,[62],3),event(5,2,1,[60],2),event(5,2,7,[64],2),event(5,2,11,[67],3),event(5,3,1,[64],2),event(5,3,7,[62],2),event(5,3,9,[60],4)],
  compare:'B / última nota en Re',variation:e=>e.map(x=>x.at===56?{...x,notes:[62]}:x),
  quiz:['¿Cambiar sólo la última altura obliga a cambiar el ritmo?',['Sí.','No: puedo conservar ataques y duraciones.'],1,'Altura, ataque y duración son decisiones distintas que podés comparar por separado.'],
  takeaway:'Pieza 1 terminada: cuatro compases melódicos propios en pista 5, con presentación, respuesta y cierre. Guardá una versión antes de empezar la siguiente pieza.'},
 {title:'Empezar otra melodía y elegir su centro',bars:4,tempo:75,main:5,form:['presentar','explorar','retomar','llegar'],
  goal:'Empezar la pieza 2 con material nuevo y una llegada provisional de cuatro compases.',
  recall:'Abrí una composición nueva. Recordá cómo hiciste pregunta y respuesta, pero inventá otro ritmo inicial o contorno antes de abrir el ejemplo.',
  question:'¿Qué cambia entre el final en Do y el final en La sobre el mismo bajo?',
  answer:'A termina en Do y B en La; ambos conservan el Do grave de referencia. Cambia la relación de la última nota con ese apoyo. Esto compara finales sobre Do: elegir La no convierte por sí solo la pieza en La menor.',
  ideas:[['Escala mayor','La escala mayor organiza alturas mediante tono–tono–semitono–tono–tono–tono–semitono. Desde Do obtenés Do, Re, Mi, Fa, Sol, La y Si. Son notas disponibles, no una secuencia que debas tocar entera.'],['Grados','Un grado es una posición en la escala elegida. En Do mayor contamos Do (1), Re (2), Mi (3): Mi es grado 3, a cuatro semitonos de Do. El 3 cuenta posiciones; el 4 cuenta saltos de semitono. Cambiar la nota desde la que medís un intervalo no cambia por sí solo la escala de referencia.'],['Centro tonal','Repetición, bajo y finales ayudan a sentir una altura como referencia. Usar las notas de Do mayor no establece automáticamente Do como centro. Una nota grave de apoyo permite comparar; mantené el mismo Do grave para los dos finales y después podés quitarlo.']],
  map:[['nota','Do','Re','Mi','Fa','Sol','La','Si'],['grado en Do','1','2','3','4','5','6','7']],
  task:'Inventá otro motivo con Do, Re, Mi, Sol y La, y organizalo en cuatro compases. Compará finales en Do y La manteniendo igual lo anterior. Si usás un apoyo grave, conservá Do en ambas pruebas: sólo cambia la nota final.',
  challenge:'Dejá una melodía nueva de cuatro compases y elegí su llegada provisional. Nombrá un rasgo que la diferencia de la pieza 1. Todavía podés prescindir de acordes.',
  check:'Puedo reconocer mi motivo nuevo, identificar al menos dos grados y explicar qué final elegí en su contexto.',
  transfer:'Quitá el apoyo grave y escuchá de nuevo. Si cambia la dirección que buscabas, probá modificar sólo una nota del final.',
  hint:'Si te bloqueás, cambiá el ritmo inicial de la primera pieza antes de elegir alturas. Presentá dos notas, respondé y retomá ese gesto.',
  events:[...Array.from({length:4},(_,b)=>event(3,b,1,[48],16)),...[64,67,69,67,64,62,64,60].map((m,k)=>event(5,Math.floor(k/2),k%2?9:1,[m],6))],
  compare:'B / final en La',variation:e=>e.map(x=>x.t===5&&x.at===56?{...x,notes:[69]}:x),
  quiz:['¿Grado 3 significa siempre Mi?',['Sí, en cualquier tonalidad.','No: depende de la escala elegida.'],1,'Mi es grado 3 en Do mayor; el número describe una relación.'],
  takeaway:'Pieza 2 en proceso: melodía nueva de cuatro compases en pista 5, con apoyo grave opcional en 3 y una llegada provisional.'},
 {title:'Darle dos colores con tríadas',bars:4,tempo:75,main:4,form:['C','Am','Am','C'],
  goal:'Continuar la pieza 2 probando dos distribuciones de acordes bajo la misma melodía.',
  recall:'Recuperá la melodía del capítulo 4 y su final. Conservá sus notas y ritmo durante la primera comparación de acordes.',
  question:'¿Qué cambia cuando sólo el segundo compás pasa de Am a C?',
  answer:'A acompaña con C–Am–Am–C; B usa C–C–Am–C. La melodía es idéntica y sus notas Mi/Sol del segundo compás se relacionan de otra manera con cada acorde. Elegí después de escuchar el recorrido completo.',
  ideas:[['Tríada y raíz','Una tríada reúne raíz, tercera y quinta, contadas desde la raíz del acorde. En C: Do (1), Re (2), Mi (3), Fa (4), Sol (5); elegimos Do–Mi–Sol. En Am contamos desde La: La (1), Si (2), Do (3), Re (4), Mi (5); elegimos La–Do–Mi. Mi no cambió: cambió desde dónde contamos.'],['Mayor y menor','La raíz empieza en 0 al medir semitonos. Mayor usa 0, 4 y 7; menor 0, 3 y 7. La tercera se llama así por los tres nombres incluidos; puede medir cuatro semitonos (mayor) o tres (menor). C→Cm conserva Do como raíz y cambia Mi por Mib. C→Am cambia la raíz y conserva Do y Mi.'],['Acordes para tu frase','Elegí una nota larga o destacada y mantenela al comparar C y Am. Primero escuchá ese compás; después la frase entera. Buscá si el acompañamiento le da el apoyo, roce o continuidad que querés. Puede servirte una nota ajena al acorde. Si no distinguís todavía, usá la comparación breve de ayuda y dejá una elección provisional.']],
  map:[['acorde','raíz','tercera','quinta'],['C','Do','Mi','Sol'],['Am','La','Do','Mi'],['F opcional','Fa','La','Do']],
  task:'Construí C y Am. Distribuilos sobre los cuatro compases de tu melodía de dos maneras; cambiá un solo compás en la primera prueba. Si había un Do grave de ensayo, quitálo o adaptalo al acorde.',
  challenge:'Conservá una distribución de acordes para los cuatro compases de la pieza 2. Escribí sus notas, guardá la alternativa y dejá la melodía reconocible.',
  check:'Puedo construir las tríadas desde su raíz y señalar en qué compás cambié el color sin modificar la melodía.',
  transfer:'Sin copiar una tríada resuelta, construí Re menor: raíz Re, tercera a 3 semitonos y quinta a 7. Comprobá tus notas en la ayuda. Después decidí si querés probarlo en tu canción; el logro es poder construirlo.',
  hint:'Elegí una nota importante y escuchala sola. Conservá esa altura y compará los dos acordes debajo. Si aún no distinguís, probá el ensayo breve con Sol; anotá la duda y mantené una elección provisional.',
  events:[...harmony(['C','Am','Am','C']),...[[64,67],[64,67],[69,64],[62,60]].flatMap((ns,b)=>ns.map((m,k)=>event(5,b,k?9:1,[m],6)))],
  compare:'B / C en el segundo compás',variation:e=>e.map(x=>x.t===4&&x.at===16?{...x,notes:CHORDS.C}:x),
  quiz:['Desde una misma raíz, ¿qué cambia entre tríada mayor y menor?',['La tercera: 4 o 3 semitonos.','La quinta: 7 o 6 semitonos.'],0,'Ambas conservan la quinta justa a 7 semitonos.'],
  takeaway:'Pieza 2 en proceso: tu melodía de cuatro compases en pista 5 y acordes elegidos en 4. Conservá una alternativa para revisar en el capítulo 6.'},
 {title:'Ajustar melodía y acordes, y cerrar',bars:4,tempo:75,main:5,form:['presentar','nota importante','respuesta','cierre'],
  goal:'Terminar la pieza 2 eligiendo una relación entre melodía y acompañamiento.',
  recall:'Escuchá tu pieza sin editar. Localizá una nota larga o acentuada que quieras revisar y nombrá el acorde que suena debajo.',
  question:'¿Qué cambia al sostener Mi o Fa sobre Am en el segundo compás?',
  answer:'A sostiene Mi, quinta de Am. B cambia sólo esa nota por Fa, que no pertenece a la tríada y añade tensión. La comparación permite elegir esa tensión o un apoyo más estable; una nota ajena al acorde no es automáticamente un error.',
  ideas:[['Nota del acorde','Si seguimos en Do mayor, Mi sigue siendo grado 3 de esa escala. Sobre C es la tercera del acorde: Do–Re–Mi, cuatro semitonos desde Do. Sobre Am es su quinta: La–Si–Do–Re–Mi, siete semitonos desde La. Nombrá siempre la referencia: grado de qué escala, o intervalo desde qué raíz.'],['Notas que conectan','Sobre C, Do–Re–Mi puede usar Re como nota de paso cuando conecta por grado conjunto dos notas del acorde. Mi–Fa–Mi es un bordado. La figura completa, su duración y posición explican la función; una nota aislada no basta.'],['Revisar y terminar','Elegí una nota importante y probá una alternativa manteniendo el acorde, o cambiá el acorde manteniendo la nota. Describí si oís apoyo, roce o continuidad; «no lo distingo todavía» también localiza qué practicar. Después escuchá el final y reducí el acompañamiento si oculta tu motivo. Una comparación por vez permite entender la causa.']],
  map:[['nota','sobre C','sobre Am'],['Mi','tercera','quinta'],['Do','raíz','tercera'],['Fa','fuera de tríada','fuera de tríada']],
  task:'Probá una alternativa para la nota importante de tu melodía sin cambiar el acorde. Elegí, compará dos finales y escuchá los cuatro compases sin repetición.',
  challenge:'Terminá la pieza 2 con melodía audible, acompañamiento y llegada elegida. Guardá antes/después y una frase: qué escuchabas, qué cambiaste y qué efecto tuvo.',
  check:'Puedo nombrar la relación de una nota importante con su acorde y mostrar un ajuste que ayuda al cierre o a la claridad.',
  transfer:'Sin abrir el modelo, probá otro acompañamiento para un compás de esta melodía. Decidí qué cambia antes de empezar una pieza nueva.',
  hint:'Concentrate en una nota y un acorde. Si no distinguís el cambio, sostené la nota y alterná ambos ensayos a volumen parecido.',
  events:[...harmony(['C','Am','Am','C']),event(5,0,1,[64],6),event(5,0,9,[67],6),event(5,1,1,[64],10),event(5,2,1,[69],6),event(5,2,9,[64],6),event(5,3,1,[62],2),event(5,3,5,[60],8)],
  compare:'B / Fa largo sobre Am',variation:e=>e.map(x=>x.t===5&&x.at===16?{...x,notes:[65]}:x),
  quiz:['Sobre Am = La–Do–Mi, Mi es…',['La raíz.','La quinta.'],1,'Desde la raíz La: La (1), Si (2), Do (3), Re (4), Mi (5). Son siete semitonos; en la escala de Do mayor, Mi sigue siendo grado 3.'],
  takeaway:'Pieza 2 terminada: cuatro compases con melodía y armonía propias, un cierre y una comparación guardada. La pieza 3 empieza con material nuevo.'},
 {title:'Empezar un tema desde una llegada',bars:4,tempo:75,main:4,form:['I · C','IV · F','V · G','I · C'],
  goal:'Empezar la pieza 3 desde un recorrido armónico y un gesto melódico nuevo.',
  recall:'Abrí una composición nueva. Recuperá cómo elegiste una nota final y construí C, F y G sin copiar el motivo anterior.',
  question:'¿Qué cambia si el último acorde es C o G y la melodía queda igual?',
  answer:'A hace C–F–G–C y B termina en G. La última nota melódica, Sol, pertenece a ambos acordes. En este contexto de Do, volver a C suele afirmar la llegada; sostener G mantiene otra expectativa.',
  ideas:[['Grados de acordes','En Do mayor: I = C, IV = F, V = G y vi = Am. Los romanos sitúan la raíz en la escala; aquí mayúsculas indican acordes mayores y minúsculas menores. No son números de pista.'],['Función en contexto','En este recorrido I establece referencia, IV se aleja y V prepara un posible regreso a I. Es una relación entre acordes y continuación, no una emoción fija ni una obligación de resolver siempre.'],['Ritmo armónico','Describe cada cuánto cambia la armonía. Un acorde por compás deja un espacio distinto que uno cada dos compases. El ritmo de bajo o melodía puede cambiar sin alterar esa frecuencia.']],
  map:[['grado','I','IV','V','vi'],['en Do mayor','C','F','G','Am']],
  task:'Probá C–F–G–C e inventá un gesto melódico propio. Compará el último acorde C con G sin tocar el resto. Elegí qué tipo de llegada quiere tu pieza.',
  challenge:'Dejá un borrador nuevo de cuatro compases que presente una idea, se aleje y llegue. Podés partir del recorrido sugerido o adaptarlo con acordes conocidos.',
  check:'Puedo reconocer mi gesto nuevo, nombrar I/IV/V en Do y explicar qué cambia al elegir el último acorde.',
  transfer:'En una copia, sostené un acorde durante dos compases. Conservá el motivo y escuchá si la espera cambia de función.',
  hint:'Si los finales parecen equivalentes, escuchá los dos últimos compases varias veces; después recuperá el recorrido entero.',
  events:[...harmony(['C','F','G','C'],true),...[64,65,62,67].map((m,b)=>event(5,b,9,[m],5))],
  compare:'B / último acorde en G',variation:e=>e.map(x=>x.at===48&&x.t!==5?{...x,notes:x.t===3?[43]:CHORDS.G}:x),
  quiz:['¿Qué cambia al sostener cada acorde dos compases en vez de uno?',['El ritmo armónico.','Necesariamente la tonalidad.'],0,'Podés cambiar la duración de las armonías sin cambiar sus notas ni el centro.'],
  takeaway:'Pieza 3 en proceso: cuatro compases nuevos con recorrido armónico, gesto melódico y llegada provisional; bajo opcional en pista 3.'},
 {title:'Conectar los acordes como líneas',bars:4,tempo:75,main:4,form:['C','F','G','C'],
  goal:'Continuar la pieza 3 revisando cómo se mueve cada voz sin cambiar los acordes.',
  recall:'Recuperá tu recorrido del capítulo 7. Escuchá sólo la nota superior del acompañamiento y localizá un salto que quieras probar de otra manera.',
  question:'¿Pueden seguir siendo los mismos acordes aunque cambie su posición?',
  answer:'Sí. A coloca las voces de C–F–G–C próximas entre sí; B usa posiciones fundamentales. El bajo y la melodía quedan iguales. Cambian el registro y los desplazamientos de las voces, no las clases de nota de los acordes.',
  ideas:[['Disposición','Do–Mi–Sol y Mi–Sol–Do contienen las mismas clases de nota en distinto orden y registro. Esa elección puede aclarar una melodía o producir un salto intencional.'],['Raíz y bajo','La raíz da nombre al acorde. Si el bajo total es otra nota del acorde, hay una inversión. Do–Fa–La en pista 4 con Fa más grave en pista 3 sigue teniendo Fa como bajo del conjunto.'],['Conducción de voces','Seguí cada línea entre acordes: Do–Mi–Sol → Do–Fa–La conserva Do, mueve Mi a Fa y Sol a La. Mantener notas comunes y mover otras poco es un recurso; no una obligación de evitar todo salto.']],
  map:[['voz','C','F','G','C'],['inferior','Do','Do','Si','Do'],['media','Mi','Fa','Re','Mi'],['superior','Sol','La','Sol','Sol']],
  task:'Reacomodá los acordes de tu pieza en posiciones cercanas. Mantené el bajo y tu motivo iguales para comparar. Tocá una voz por vez y elegí qué movimiento querés conservar.',
  challenge:'Guardá una disposición revisada de los cuatro compases y la anterior. Señalá una línea interna que ahora puedas seguir; si preferís un salto, elegilo con una razón audible.',
  check:'Puedo seguir una voz, distinguir raíz de bajo y explicar qué cambió sin confundir posición con identidad del acorde.',
  transfer:'Probá otra posición de un acorde sin mirar el mapa. Comprobá sus notas y elegí por cómo conecta con el compás siguiente.',
  hint:'Primero mantené una nota común entre dos acordes. Ajustá las otras de a una; escuchá la melodía antes de aceptar el resultado.',
  events:[...harmony(['C','F','G','C'],true).filter(e=>e.t===3),...[[60,64,67],[60,65,69],[59,62,67],[60,64,67]].map((ns,b)=>event(4,b,1,ns,16)),...[76,77,74,72].map((m,b)=>event(5,b,9,[m],5))],
  compare:'B / posiciones fundamentales',variation:e=>e.map(x=>x.t===4?{...x,notes:CHORDS[['C','F','G','C'][x.at/16]]}:x),
  quiz:['Do–Fa–La arriba y Fa en una pista más grave: ¿cuál es el bajo total?',['Do.','Fa.'],1,'La nota más grave del conjunto está en la pista de bajo; mirá todas las capas.'],
  takeaway:'Pieza 3 en proceso: el mismo recorrido y motivo, con disposición de voces elegida y una versión anterior conservada.'},
 {title:'Elegir el color de séptima y terminar',bars:4,tempo:75,main:4,form:['C','F','G7 o G','C'],
  goal:'Terminar la pieza 3 probando un color nuevo que podés conservar o descartar.',
  recall:'Continuá tu pieza con sus voces revisadas. Localizá el acorde que prepara el regreso antes de sumar otra nota.',
  question:'¿Qué agrega Fa al acorde de Sol antes de volver a Do?',
  answer:'A usa G7 = Sol–Si–Re–Fa; B quita sólo Fa y deja G. En A, Fa puede bajar a Mi al llegar C. La séptima añade color y una línea de resolución; elegí según tu pieza, sin obligación de usarla.',
  ideas:[['Séptima','Añadir otra tercera a una tríada da una séptima respecto de la raíz. G7 lleva Fa, a diez semitonos de Sol. Cmaj7 lleva Si, a once de Do; C7 lleva Sib, a diez. Los símbolos distinguen esos colores.'],['Una línea que llega','En G7→C, Fa puede bajar un semitono a Mi mientras Si puede subir a Do. En una disposición concreta algunas voces pueden mantenerse o ir a otro destino: escuchá la línea que estás escribiendo.'],['Ampliación opcional','Dm7–G7–Cmaj7 es ii–V–I en Do. Construí primero Re–Fa–La–Do, Sol–Si–Re–Fa y Do–Mi–Sol–Si. Después probá raíces Re–Sol–Do con voces guía Fa–Do → Fa–Si → Mi–Si. No necesitás esa ampliación para terminar hoy.']],
  map:[['acorde','raíz','tercera','quinta','séptima'],['G7','Sol','Si','Re','Fa'],['Cmaj7','Do','Mi','Sol','Si'],['C7','Do','Mi','Sol','Sib']],
  task:'En tu pieza, compará G y G7 antes de C conservando el resto. Si elegiste otro recorrido, probá una séptima que puedas construir y nombrar. Elegí un color y ajustá la respuesta final.',
  challenge:'Terminá la pieza 3 de cuatro compases. Debe oírse una llegada y una decisión sobre las voces. Guardá la versión con séptima y la alternativa; la tríada también puede ser tu elección final.',
  check:'Puedo construir el color que comparé, seguir una voz hacia el final y explicar qué versión terminé.',
  transfer:'Sin copiar un final del modelo, escribí otra respuesta para tu motivo. Como extensión podés trasladarlo a ii–V–I ajustando sólo las alturas necesarias.',
  hint:'Escuchá Fa→Mi sola, después con bajo Sol→Do, y finalmente dentro de tu pieza. Si la nota añadida tapa el motivo, probá otra octava o la tríada.',
  events:[...harmony(['C','F','G','C'],true).filter(e=>e.t===3),...[[60,64,67],[60,65,69],[59,62,65,67],[60,64,67]].map((ns,b)=>event(4,b,1,ns,16)),...[76,77,74,72].map((m,b)=>event(5,b,9,[m],5))],
  compare:'B / G sin séptima',variation:e=>e.map(x=>x.t===4&&x.at===32?{...x,notes:x.notes.filter(m=>m!==65)}:x),
  quiz:['¿Qué distingue Cmaj7 de C7?',['Si frente a Sib.','Mi frente a Mib.'],0,'Ambos conservan Do–Mi–Sol. Cambia la séptima.'],
  takeaway:'Pieza 3 terminada: cuatro compases con gesto propio, llegada y voces elegidas. La comparación de color queda guardada; ii–V–I es una extensión opcional.'},
 {title:'Empezar un groove con aire',bars:4,tempo:85,main:5,swing:2/3,form:['riff','respuesta','riff','aire'],
  goal:'Empezar la pieza 4 con un riff nuevo, respuesta y espacio en cuatro compases.',
  recall:'Abrí una pieza nueva y recuperá dos recursos conocidos: un motivo reconocible y un silencio deliberado. Inventá tu riff antes de abrir A/B.',
  question:'¿Qué cambia entre corcheas largas/cortas y corcheas parejas con las mismas notas?',
  answer:'A retrasa la segunda corchea de cada pulso con una proporción didáctica 2:1; B reparte el pulso en dos mitades iguales. Notas, compases y BPM se conservan. Cambia la distribución temporal dentro del pulso; el swing real incluye además articulación y acentos y no tiene una proporción universal.',
  ideas:[['Riff y respuesta','Un riff es una figura que vuelve y sostiene la identidad del groove. Dos o tres ataques pueden alcanzar. Una respuesta corta seguida de silencio deja que la base también se escuche.'],['Color de blues','Sobre C7 = Do–Mi–Sol–Sib, probá un Mib breve que llegue a Mi. Mib roza la tercera mayor del acorde; su efecto depende de cómo entra y continúa. Un groove de cuatro u ocho compases con ese color no es la forma de blues de doce.'],['Feel y tempo','Podés tocar recto o explorar swing sin cambiar los BPM. Como aproximación de escucha, swing puede retrasar la segunda corchea de cada par; la relación varía según estilo, tempo e intérprete. La duración de las notas también es una decisión.']],
  map:[['función','presentar','responder','retomar','dejar aire'],['compás','1','2','3','4']],
  task:'Inventá un riff de dos o tres ataques sobre un acompañamiento simple y completá cuatro compases con respuesta. Elegí un feel cómodo; podés comparar recto y swing conservando notas y tempo, o desplazar sólo una entrada.',
  challenge:'Guardá un groove nuevo de cuatro compases con un rasgo reconocible y un hueco audible. Elegí tus notas; C7 y Mib→Mi son recursos disponibles, no una frase para copiar.',
  check:'Puedo señalar el rasgo que identifica el riff, dónde respira y qué decisión de fraseo elegí sin confundirla con el tempo.',
  transfer:'Tocá o programá otra respuesta sin consultar A/B. Como extensión compará corcheas parejas y larga/corta en el OP–XY, manteniendo las notas.',
  hint:'Reducí a una nota de riff y dos ataques. Añadí una respuesta antes de decidir si necesitás más alturas o batería.',
  events:[...harmony(['C7','C7','C7','C7'],true),...[0,2].flatMap(b=>[event(5,b,1,[60],2),event(5,b,7,[63],2),event(5,b,9,[64],3)]),event(5,1,1,[67],3),event(5,1,7,[64],3),event(5,3,1,[60],4)],
  compare:'B / corcheas parejas',variation:e=>e,
  quiz:['¿Un groove de ocho compases con Mib→Mi ya es un blues de doce?',['No: el color y la forma son decisiones distintas.','Sí: esa figura determina la forma.'],0,'La forma de doce organiza doce compases; usar un gesto de blues no fija su duración.'],
  takeaway:'Pieza 4 en proceso: groove original de cuatro compases, con riff y respuesta. Conserválo para desarrollarlo a ocho en el capítulo 11.'},
 {title:'Desarrollar sin perder el riff',bars:8,tempo:85,main:5,form:['A riff','A respuesta','A riff','A aire','A′ riff','A′ respuesta','A′ riff','A′ aire'],
  goal:'Continuar la pieza 4: ampliar tu groove de cuatro a ocho compases con una variación.',
  recall:'Recuperá el groove del capítulo 10. Antes de cambiarlo, nombrá qué rasgo del riff debe seguir siendo reconocible.',
  question:'¿Qué cambia al subir sólo el riff de la segunda mitad una octava?',
  answer:'A conserva la base y sube la melodía de los compases 5–8 una octava. B la deja en el registro inicial. Los ataques, duraciones y acordes son iguales: la comparación aísla el registro.',
  ideas:[['A y A′','A presenta cuatro compases; A′ retoma esos cuatro con una transformación. El símbolo prima indica variación, no una obligación de inventar otra progresión.'],['Registro','Una octava conserva las clases de nota y cambia la altura. El motivo puede reconocerse por ritmo y contorno mientras cambia su lugar en la textura. Evaluá el resultado con las demás pistas.'],['Textura y duración','Retirar una capa durante una respuesta o acortar notas también desarrolla una idea. Probá una transformación principal por comparación. Más pistas no equivalen a una forma más clara.']],
  map:[['decisión','qué conservás','qué transformás'],['registro','ritmo y clases de nota','octava'],['textura','motivo','capas presentes'],['duración','ataques y alturas','cuánto suenan']],
  task:'Copiá tus cuatro compases a 5–8 y elegí una transformación principal: registro, duración o densidad. Escuchá ambas mitades juntas antes de agregar otra decisión.',
  challenge:'Guardá ocho compases A–A′. Deben oírse el parentesco y una variación deliberada. Conservá la primera mitad y prepará la segunda para recibir un cierre en el capítulo 12.',
  check:'Puedo reconocer el riff en ambas mitades y nombrar la variable que transformé y el efecto que buscaba.',
  transfer:'Improvisá o programá tres respuestas de dos compases sobre tu base. Rescatá una sin copiar la respuesta del modelo.',
  hint:'Si A′ pierde identidad, recuperá el ritmo inicial del riff. Si todavía no contrasta, retirale una capa durante un compás.',
  events:[...harmony(Array(8).fill('C7'),true),...[0,2,4,6].flatMap(b=>[event(5,b,1,[b<4?60:72],2),event(5,b,7,[b<4?63:75],2),event(5,b,9,[b<4?64:76],3)]),...[1,5].flatMap(b=>[event(5,b,1,[b<4?67:79],3),event(5,b,7,[b<4?64:76],3)]),...[3,7].map(b=>event(5,b,1,[b<4?60:72],4))],
  compare:'B / mismo registro en las dos mitades',variation:e=>e.map(x=>x.t===5&&x.at>=64?{...x,notes:x.notes.map(m=>m-12)}:x),
  quiz:['¿Variar el registro obliga a cambiar los acordes?',['Sí.','No: puedo conservarlos.'],1,'La altura relativa de una capa puede cambiar manteniendo la armonía.'],
  takeaway:'Pieza 4 en proceso: ocho compases A–A′ con riff y transformación elegida. En el OP–XY, usá patrones independientes en las pistas que varían.'},
 {title:'Dar forma al groove y terminar',bars:8,tempo:85,main:5,form:['A riff','A respuesta','A riff','A aire','A′ riff','A′ respuesta','preparar','final'],
  goal:'Terminar la pieza 4 de ocho compases con entrada, variación y final elegidos.',
  recall:'Escuchá A–A′ sin mover controles. Elegí si el problema principal está en el paso entre mitades o en el último compás.',
  question:'¿Cómo cambia el final al sostener más la misma última nota?',
  answer:'A sostiene el Do final ocho pasos y B sólo dos. No cambian su altura ni el momento de entrada. Ambas dejan silencio después; compará cuánto peso querés darle al cierre.',
  ideas:[['Forma pequeña','Ocho compases pueden presentar, responder, variar y concluir. Las funciones se oyen por lo que vuelve, cambia o desaparece; no dependen de llenar cada compás de notas nuevas.'],['Final y repetición','Para evaluar el cierre escuchá una pasada con el loop apagado. Una nota más larga, menos ataques o una respuesta seguida de silencio pueden distinguir el final de otra vuelta.'],['Blues de doce como extensión','Si querés ampliar en el OP–XY, probá C7×4, F7×2, C7×2, G7, F7, C7×2. Adaptá el riff a los cambios y al conteo de doce: no alcanza con añadir cuatro compases al final del groove actual.']],
  map:[['pasada','qué escuchás'],['1','identidad del riff'],['2','paso de A a A′'],['3','última respuesta y silencio']],
  task:'Elegí un ajuste para la entrada de A′ y escuchá. Después, en otra comparación, probá dos cierres: una llegada con menos ataques o una respuesta corta seguida de silencio.',
  challenge:'Terminá la pieza 4 de ocho compases. Guardá dos versiones de una decisión de fraseo y conservá la que mejor complete una pasada. No necesitás ampliar la forma para terminar.',
  check:'Puedo seguir el riff, oír una variación y señalar una decisión que hace funcionar el final.',
  transfer:'Sin consultar el modelo, inventá otro cierre para tu groove. La forma de blues de doce es una extensión opcional en el instrumento.',
  hint:'Dejá la última respuesta más corta que la anterior y escuchá el silencio. Si parece un corte arbitrario, probá cambiar la última altura o su duración.',
  events:[...harmony(Array(8).fill('C7'),true),...[0,2,4,6].flatMap(b=>[event(5,b,1,[b<4?60:72],2),event(5,b,7,[b<4?63:75],2),event(5,b,9,[b<4?64:76],3)]),...[1,5].flatMap(b=>[event(5,b,1,[b<4?67:79],3),event(5,b,7,[b<4?64:76],3)]),event(5,3,1,[60],4),event(5,7,1,[72],8)],
  compare:'B / nota final más corta',variation:e=>e.map(x=>x.t===5&&x.at===112?{...x,len:2}:x),
  quiz:['¿Para terminar la pieza debo usar todos los recursos aprendidos?',['Sí.','No: elijo los que sirven a mi intención.'],1,'Componer incluye conservar, transformar y quitar. El cierre se evalúa por escucha.'],
  takeaway:'Pieza 4 terminada: groove propio de ocho compases, A–A′, con fraseo y final elegidos. Guardá una comparación antes de abrir la pieza 5.'},
 {title:'Escribir tu encargo y construir una base',bars:8,tempo:82,main:5,form:['presentar','responder','afirmar','aire','retomar','responder','preparar','final provisional'],
  goal:'Empezar la pieza 5 con una intención propia y material nuevo; decidir antes de consultar ejemplos.',
  recall:'Abrí una composición nueva. Elegí dos herramientas que ya pudiste usar y escribí una intención audible, como empezar calmo y abrir la segunda mitad.',
  question:'En este laboratorio, ¿qué cambia al añadir ataques de hi-hat?',
  answer:'B agrega hi-hats en los pasos pares. Bombo, caja, bajo, melodía y tempo quedan iguales. Esa mayor densidad puede sostener energía o competir con el motivo: el criterio es la intención de tu pieza.',
  ideas:[['Tu encargo','Elegí tema instrumental o groove, ocho compases y hasta cuatro pistas. Inventá otro motivo; no hace falta copiar la progresión ni la batería del laboratorio. Podés consultar notas y operaciones del manual.'],['Roles','Una pista puede sostener el pulso, otra orientar el bajo y otra presentar el motivo. No tenés que usar todos los papeles. Quitá una capa y escuchá qué función se pierde antes de devolverla.'],['Bajo y batería','El bajo puede declarar una raíz y moverse hacia otra nota; no necesita duplicar cada golpe de bombo. En el modelo coinciden en 1 y 9, pero son decisiones separadas que podés variar. Los sonidos de batería dependen del kit que elegís en el OP–XY.']],
  map:[['pista sugerida','1','3','4','5'],['papel posible','batería','bajo','armonía','motivo']],
  task:'Inventá dos ideas breves, comparalas y elegí una. Extendéla a ocho compases con repetición y una base provisional. Asigná una función audible a cada pista.',
  challenge:'Guardá el borrador nuevo de la pieza 5: ocho compases, hasta cuatro pistas y una razón para conservar la idea. Armonía y batería son opcionales si tu música funciona.',
  check:'Puedo mostrar material nuevo, explicar mi intención y señalar el aporte de cada pista al quitarla y reponerla.',
  transfer:'Probá otra armonía o timbre manteniendo el motivo. Elegí una sola comparación y conservá su versión previa.',
  hint:'Si te trabás, decidí primero qué querés recordar: una melodía, un riff o una respuesta de bajo. Empezá con dos compases y repetilos antes de añadir capas.',
  events:[...Array.from({length:8},(_,b)=>[event(1,b,1,[53],2),event(1,b,9,[53],2),event(1,b,5,[55],2),event(1,b,13,[55],2),...[3,7,11,15].map(s=>event(1,b,s,[57],1))]).flat(),...['C','Am','F','G','C','Am','F','G'].flatMap((n,b)=>[event(3,b,1,[roots[n]],8),event(3,b,9,[roots[n]+7],6)]),...[64,64,65,62,64,64,65,60].map((m,b)=>event(5,b,13,[m],3))],
  compare:'B / más ataques de hi-hat',variation:e=>[...e,...Array.from({length:8},(_,b)=>[2,4,6,8,10,12,14,16].map(s=>event(1,b,s,[57],1))).flat()],
  quiz:['¿Una base necesita batería, bajo y acordes a la vez?',['Sí, siempre.','No: elijo las capas que aportan una función.'],1,'El encargo pide una intención y roles audibles, no llenar todas las pistas.'],
  takeaway:'Pieza 5 en proceso: borrador original de ocho compases, intención escrita y roles elegidos. Continualo en los capítulos 14–16.'},
 {title:'Elegir qué cambia en la segunda mitad',bars:8,tempo:82,main:5,form:['A','A','A','A','B o A′','B o A′','B o A′','regreso preparado'],
  goal:'Continuar la pieza 5 creando un contraste deliberado que conserve identidad.',
  recall:'Recuperá tu borrador. Escuchá los compases 1–4 y nombrá un rasgo que deba seguir reconocible en 5–8.',
  question:'¿Se oye contraste si sólo cambia el registro de la melodía?',
  answer:'A sube la melodía una octava en 5–8. B mantiene el registro inicial; acompañamiento, ritmo y duraciones son iguales. Esta comparación demuestra una opción, no impone cómo tiene que ser tu segunda mitad.',
  ideas:[['Identidad y diferencia','B puede contrastar por armonía, ritmo, registro o textura. A′ suele conservar más rasgos de A. El nombre ayuda a describir la relación; el criterio es qué se reconoce y qué función cumple el cambio.'],['Proteger los patrones','En ARRANGE, M2 copia el patrón seleccionado; M1 crea uno nuevo y M3 pega. Antes de editar B, confirmá que su escena selecciona el patrón nuevo de cada pista que vas a variar. Duplicar sólo la escena puede conservar referencias compartidas.'],['Comparar una variable','Probá primero registro, densidad, ritmo o armonía. Si cambiás todo junto cuesta saber qué aportó cada decisión. Después podés combinar dos cambios que ya escuchaste por separado.']],
  map:[['mitad','1–4','5–8'],['decisión','identidad inicial','contraste y relación']],
  task:'Protegé los patrones de la primera mitad. Transformá 5–8 con una decisión principal elegida por vos; escuchá ambas mitades juntas y recuperá un rasgo si se perdió la relación.',
  challenge:'Guardá ocho compases con contraste audible y A recuperable. Explicá qué se mantiene y qué cambiaste; no hace falta usar otro acorde para crear B.',
  check:'Puedo volver a A sin cambios, reconocer una relación entre mitades y explicar la función del contraste.',
  transfer:'Diseñá otra segunda mitad con una estrategia diferente. Compará ambas desde el compás 3 para oír también cómo llegan.',
  hint:'Si falta contraste, retirale una capa a B durante un compás. Si pierde identidad, conservá el ritmo inicial del motivo.',
  events:[...harmony(['C','Am','F','G','C','Am','F','G'],true),...[64,60,65,62,76,72,77,74].map((m,b)=>event(5,b,9,[m],5))],
  compare:'B / registro original',variation:e=>e.map(x=>x.t===5&&x.at>=64?{...x,notes:x.notes.map(m=>m-12)}:x),
  quiz:['Para proteger A antes de editar B…',['Copio los patrones que voy a cambiar y selecciono las copias en B.','Duplico una escena y edito cualquier patrón.'],0,'Las escenas reúnen referencias a patrones; elegí copias independientes antes de variarlas.'],
  takeaway:'Pieza 5 en proceso: ocho compases con identidad y contraste propios. La primera mitad conserva sus patrones y su versión anterior.'},
 {title:'Conectar las mitades y preparar el final',bars:8,tempo:82,main:1,form:['A','A','A','preparar','B','B','responder','cerrar'],
  goal:'Continuar la pieza 5 decidiendo cómo entra la segunda mitad y cómo termina una pasada.',
  recall:'Escuchá el límite entre compases 4 y 5 sin editar. Describí qué necesita el cambio: aire, continuidad o una señal de entrada.',
  question:'¿Qué cambia si falta sólo la caja del último pulso del compás 4?',
  answer:'A omite la caja del paso 13 de ese compás; B la restaura. Las otras pistas siguen iguales. El hueco parcial puede despejar la entrada de la segunda mitad; no es un silencio total, porque quedan otros sonidos.',
  ideas:[['Transición','Una transición relaciona lo que termina con lo que empieza. Quitar un ataque, sostener una nota o cambiar una textura son alternativas. Comenzá con una y evaluá su función escuchando ambos lados del límite.'],['Anticipar','Una anticipación presenta antes una nota o gesto de lo que viene. Si B empieza en Am, La puede probarse antes de su llegada; escuchá también cómo roza el acorde anterior. Una nota cualquiera cerca del límite no anticipa automáticamente la armonía siguiente.'],['Movimiento de sonido','Si una automatización aporta, grabá sólo un movimiento y compará con la versión seca. En OP–XY se puede grabar manteniendo RECORD mientras movés un control durante reproducción; se registra por pasos. Es opcional y se hace en el instrumento.']],
  map:[['zona','compás 4','compás 5','compás 8'],['función','preparar','hacer entrar B','concluir']],
  task:'Compará retirar una capa o un ataque antes de B con conservarlo. Elegí escuchando desde el compás 3 al 6. Después prepará un final propio en el último compás.',
  challenge:'Guardá la pieza 5 completa en borrador, con transición y cierre preparados. Conservá una versión previa y describí qué señal hace legible la entrada.',
  check:'Puedo señalar qué se retira o aparece, dónde entra B y qué hace el último compás para terminar.',
  transfer:'Probá otra transición que use una estrategia distinta. Automatización y anticipación sólo se conservan si mejoran una función que podés describir.',
  hint:'Si no sabés qué cambiar, omití un ataque de acompañamiento antes de B. Escuchá antes de sumar fill, nota o automatización.',
  events:[...harmony(['C','Am','F','G','Am','F','C','C'],true),...Array.from({length:8},(_,b)=>[event(1,b,1,[53],2),event(1,b,9,[53],2),event(1,b,5,[55],2),...(b===3?[]:[event(1,b,13,[55],2)])]).flat(),...[64,60,65,62,69,65,67,60].map((m,b)=>event(5,b,9,[m],5))],
  compare:'B / restaurar la caja anterior a B',variation:e=>[...e,event(1,3,13,[55],2)],
  quiz:['Si quito una caja pero siguen acordes y bajo, ¿hay silencio total?',['Sí.','No: retiré un ataque de una capa.'],1,'Distinguí un hueco en una pista de un silencio de todo el conjunto.'],
  takeaway:'Pieza 5 en proceso: ocho compases completos con contraste, transición y final preparados. Conservá una versión anterior para revisar en el capítulo 16.'},
 {title:'Revisar, terminar y empezar sin copiar',bars:8,tempo:82,main:5,form:['A','A','A','preparar','B','B','respuesta','final'],
  goal:'Terminar la pieza 5 y comprobar qué procedimiento podés aplicar a un germen nuevo.',
  recall:'Escuchá tu pieza entera sin tocar controles. Elegí el problema que más afecta la intención que escribiste al empezar.',
  question:'¿Qué cambia al quitar una sola voz del acorde en el compás 5?',
  answer:'A tiene Do–Mi–La en el acompañamiento de ese compás. B quita Mi y conserva Do–La; las otras notas, ataques y pistas no cambian. Compará si esa menor densidad permite oír mejor el motivo sin perder el color que querés.',
  ideas:[['Diagnóstico concreto','Anotá un lugar y un efecto: en compás 5 el acorde tapa la melodía, o el último compás parece otra vuelta. Un problema localizado permite probar una corrección y escuchar si funcionó.'],['Una comparación útil','Conservá antes/después. Cambiá una variable —nota, registro, duración, capa o nivel en el instrumento— y reescuchá el mismo tramo a volumen parecido. Después comprobá la pieza completa; un arreglo local puede afectar el recorrido.'],['Transferencia','En un patrón vacío inventá dos compases de pregunta y respuesta con final, empezando por otro elemento: ritmo o bajo si antes empezaste por melodía, y viceversa. Usá material nuevo; cambiar sólo preset, BPM o transportar la misma idea no prueba una nueva composición. El manual técnico puede seguir abierto.']],
  map:[['paso','observar','probar','reescuchar','elegir'],['evidencia','problema localizado','una variable','mismo tramo y pieza','razón audible']],
  task:'Elegí un criterio de escucha, localizá un problema y corregí una variable. Compará antes/después, elegí y escuchá los ocho compases sin repetición.',
  challenge:'Guardá la pieza 5 terminada, su versión anterior y una razón para tu elección. Reservá diez minutos para un boceto nuevo de dos compases sin copiar patrones; anotá qué ayuda musical necesitaste, si alguna.',
  check:'Puedo justificar una corrección por escucha, terminar una versión y reutilizar un procedimiento con otro ritmo o contorno y otra respuesta.',
  transfer:'Ampliá el boceto nuevo o repetí el encargo otro día con menos ayuda. Si una decisión todavía cuesta, volvé al recurso preciso y probala sobre material nuevo.',
  hint:'Si todo parece un problema, elegí una sola prioridad: motivo audible, relación entre mitades o cierre. Silenciá una capa para localizar la causa antes de editar notas.',
  events:[...harmony(['C','Am','F','G','Am','F','C','C'],true).map(x=>x.t===4&&x.at===64?{...x,notes:[60,64,69]}:x),...[64,60,65,62,69,65,67,60].map((m,b)=>event(5,b,9,[m],5))],
  compare:'B / una voz menos en compás 5',variation:e=>e.map(x=>x.t===4&&x.at===64?{...x,notes:x.notes.filter(m=>m!==64)}:x),
  quiz:['¿Qué demuestra mejor que puedo usar un recurso con autonomía?',['Inventar otra respuesta con material nuevo y explicar mi decisión.','Cambiar sólo el preset de la misma frase.'],0,'La transferencia pide volver a decidir con material nuevo. Consultar operaciones del instrumento sigue permitido.'],
  takeaway:'Pieza 5 terminada: ocho compases propios, comparación antes/después y un boceto nuevo de dos compases. Guardá el trabajo local y, por separado, los proyectos reales del OP–XY.'}
];
const noteNames=['Do','Do#','Re','Mib','Mi','Fa','Fa#','Sol','Sol#','La','Sib','Si'];
const naturalMidi=[53,55,57,59,60,62,64,65,67,69,71,72,74,76],upperMidi=[54,56,58,61,63,66,68,70,73,75];
const noteName=m=>noteNames[((m%12)+12)%12],pitchLabel=m=>noteName(m)+(Math.floor(m/12)-1);
function keyForMidi(m){let p=m,oct=0;while(p<53){p+=12;oct--;}while(p>76){p-=12;oct++;}const i=naturalMidi.indexOf(p);return {id:i>=0?'n'+i:'u'+upperMidi.indexOf(p),oct};}
function eventsAt(es,t,b,s){return es.filter(e=>e.t===t&&e.at===b*16+s);}
function soundingAt(es,t,k){return es.filter(e=>e.t===t&&e.at<=k&&e.at+e.len>k);}
function scenePlan(p){return Array.from({length:Math.ceil(p.bars/4)},(_,i)=>({scene:i+1,from:i*4,bars:Math.min(4,p.bars-i*4)}));}
function stepTime(step,bpm,swing=.5){const beat=Math.floor(step/4),part=step%4;return (beat+[0,swing/2,swing,(1+swing)/2][part])*60/bpm;}
