// Twelve workshops, six stages. A/B are fixed studies; C belongs to the learner.
const cloneEvents=events=>events.map(e=>({...e,notes:[...e.notes]}));
function event(t,b,s,notes,len=4){return {t,at:b*16+s-1,notes:[...notes],len};}
const CHORDS={C:[60,64,67],Am:[57,60,64],F:[53,57,60],G:[55,59,62],Dm7:[60,62,65,69],G7:[59,62,65,67],Cmaj7:[60,64,67,71],C7:[60,64,70],F7:[53,57,63],V7:[55,59,65]};
const roots={C:48,Am:45,F:41,G:43,Dm7:50,G7:43,Cmaj7:48,C7:48,F7:41,V7:43};
function harmony(names,bass=false){return names.flatMap((n,b)=>[event(4,b,1,CHORDS[n],16),...(bass?[event(3,b,1,[roots[n]],16)]:[])]);}
const BLUES=['C7','C7','C7','C7','F7','F7','C7','C7','V7','F7','C7','C7'];
const STAGES=['ritmo y espacio','melodía','armonía','dirección','lenguaje jazz','desarrollo y forma','base y contraste','arreglo y revisión'];
const lessonPlans=[
 {title:'El pulso sigue aunque no toques',bars:1,tempo:75,main:4,form:['un pulso, cuatro lugares'],
  goal:'Distinguir el pulso de los ataques. Tu primera composición usa una sola nota.',recall:'Sin mirar ninguna grilla: marcá cuatro pulsos con el pie. Tocá una tecla sólo en dos de ellos. No hace falta recordar teoría ni cantar.',
  question:'¿B va más lento, o deja más espacio?',answer:'Los dos ejemplos tienen el mismo tempo y duran lo mismo. B omite ataques: el pulso continúa. Menos notas no significa menor velocidad. Elegí cuál te invita más a repetirlo; no hay un ganador.',
  ideas:[['Pulso y tempo','El pulso es la referencia regular que podés seguir con el pie. El tempo dice cuántos pulsos pasan por minuto. A 75 BPM, una vuelta de cuatro pulsos dura 3,2 segundos, aunque toques una sola vez.'],['Compás y ataque','Usaremos 4/4: cuatro pulsos forman un compás. Un ataque es el comienzo de un sonido. Puede coincidir con un pulso o aparecer entre dos pulsos; no define por sí solo dónde está el pulso.'],['El mapa temporal','En esta configuración, un compás tiene 16 pasos: cuatro por pulso. Los comienzos de pulso son 1, 5, 9 y 13. Hoy sólo elegimos entre esos cuatro lugares; las subdivisiones intermedias pueden esperar. Do es nuestra tecla de prueba, no un acorde que tengas que entender todavía.']],
  map:[['pulso','1','2','3','4'],['paso inicial','1','5','9','13']],
  task:'Escuchá A y B. Después elegí dos o tres de los pasos 1, 5, 9 y 13 para tu propio ritmo. Usá sólo Do y sonidos cortos. Dejá al menos un pulso sin ataque.',
  challenge:'En «C / mi idea», empezá vacío y escribí tu ritmo. Repetilo cuatro vueltas. Cambiá un solo ataque y elegí qué versión conservar. Poné un nombre a la que te guste.',
  check:'Puedo mantener el pulso mientras hay silencios y señalar qué ataque cambié sin decir que cambié el tempo.',transfer:'En otra sesión, inventá otro ritmo con una tecla distinta, sin copiar la grilla anterior.',
  hint:'Si te perdés, usá sólo los pasos 1 y 9. Agregá un ataque en 13 y escuchá qué hace al reiniciar.',
  events:[1,5,9,13].map(s=>event(4,0,s,[60],2)),compare:'B / más espacio',variation:e=>e.filter(x=>x.at===0||x.at===8),quiz:['¿Quitar el ataque del paso 5 cambia los BPM?',['No: cambia el ritmo.','Sí: el tempo baja.'],0,'Los BPM sostienen el pulso. Los ataques deciden qué ocurre sobre ese pulso.'],
  takeaway:'Un patrón propio de un compás en pista 4, escena 1. Conservá tu elección, no es obligatorio guardar el modelo A.'},
 {title:'Una idea rítmica y su respuesta',bars:2,tempo:75,main:4,form:['pregunta','respuesta'],
  goal:'Reconocer un motivo y transformarlo sin perder su identidad.',recall:'Recreá tu ritmo del taller 1 antes de abrir el ejemplo. Si no sale exacto, conservá una versión que puedas repetir.',
  question:'¿Qué versión cambia la respuesta sin agregar otra altura?',answer:'A repite exactamente el ritmo. B mueve el último ataque de la respuesta. Las dos pueden funcionar: la repetición afirma una idea; el cambio hace que el segundo compás conteste.',
  ideas:[['Motivo','Un motivo es una idea breve reconocible. Puede ser sólo rítmica. Si cambiás todas sus características de golpe, cuesta escuchar qué relación tiene con el inicio.'],['Subdivisión','Entre dos pulsos caben ataques. El paso 7 está a mitad del segundo pulso: 5 inicia ese pulso, 7 lo divide en dos. No se acelera el tempo por tocar allí.'],['Duración y silencio','El ataque decide cuándo empieza la nota; la duración decide hasta cuándo sigue. Un paso sin ataque no siempre es silencio: puede sostener una nota anterior. En el ejemplo las notas cortas dejan huecos audibles.']],
  map:[['un pulso','inicio','¼','½','¾'],['pulso 2','5','6','7','8']],
  task:'Con una sola tecla, construí tres ataques en un compás. Repetilos en el segundo y mové solamente el último. Compará antes de agregar más notas.',
  challenge:'Terminá una frase rítmica de dos compases: pregunta y respuesta. Después probá alargar una nota sin mover su inicio. Elegí el espacio que querés dejar.',
  check:'Mi respuesta conserva algo reconocible de la pregunta. Puedo distinguir entre mover un ataque, alargarlo y quitarlo.',transfer:'Volvé mañana: reconstruí el motivo de oído, sin mirar los pasos. Después hacé una respuesta nueva.',hint:'Copiá A a C. En el segundo compás, trasladá el Do del paso 11 al 13. Para una creación más libre, cambiá luego los dos primeros ataques.',
  events:[0,1].flatMap(b=>[event(4,b,1,[60],2),event(4,b,7,[60],2),event(4,b,11,[60],3)]),compare:'B / respuesta desplazada',variation:e=>e.map(x=>x.at===26?{...x,at:28}:x),quiz:['Un paso sin ataque, ¿siempre está en silencio?',['Sí.','No: puede seguir sonando una nota anterior.'],1,'Mirá la duración de la nota que empezó antes. El simulador distingue ataque de sonido sostenido.'],
  takeaway:'Pista 4, patrón de dos compases; escena 1. Esta miniatura rítmica es tu primer material para desarrollar.'},
 {title:'Dibujar una melodía con distancias',bars:2,tempo:75,main:5,form:['subir','volver'],
  goal:'Pensar una melodía como un recorrido, no como botones aislados.',recall:'Elegí el ritmo que compusiste en el taller 2. Hoy puede convertirse en melodía sin cambiar sus ataques.',
  question:'¿Qué cambia si la misma figura empieza más arriba?',answer:'B mueve todas las alturas dos semitonos: conserva las distancias y el ritmo. Eso es transponer. Reconocer una figura no depende únicamente del nombre de su primera nota.',
  ideas:[['Semitono y tono','Un semitono es la distancia entre alturas consecutivas: Do→Do# o Mi→Fa. Dos semitonos forman un tono: Do→Re. Hay que contar también la fila superior del teclado; dos botones vecinos de la fila inferior no siempre están a la misma distancia.'],['Intervalo','Un intervalo compara dos alturas. Do→Re es una segunda; Do→Mi, una tercera; Do→Sol, una quinta. El número cuenta nombres de nota incluyendo ambos extremos. Más adelante distinguiremos intervalos mayores y menores.'],['Contorno','Subir, bajar y repetir son movimientos que el oído puede seguir. Un salto grande puede destacar un momento; moverse por notas cercanas conecta el recorrido. Ninguno es obligatorio: elegí un gesto que puedas reconocer.']],
  map:[['recorrido','Do→Do#','Do→Re','Do→Mi','Do→Sol'],['semitonos','1','2','4','7']],
  task:'Conservá un ritmo sencillo. Probá Do–Re–Mi–Sol y luego Sol–Mi–Re–Do. Escuchá la dirección antes de memorizar los nombres.',
  challenge:'Creá dos compases con tres o cuatro alturas. Elegí un punto más alto y una dirección de regreso. No hace falta usar el recorrido del ejemplo.',
  check:'Puedo describir dónde sube, baja o repite mi melodía y reconocerla cuando empieza en otra altura.',transfer:'Mové tu figura dos semitonos conservando las distancias. Si cambia demasiado su identidad, revisá qué intervalo alteraste.',hint:'Primero cambiá sólo la altura del último ataque de tu ritmo anterior. Después mové otro: así escuchás qué aporta cada decisión.',
  events:[...[60,62,64,67].map((m,k)=>event(5,0,1+k*4,[m],3)),...[67,64,62,60].map((m,k)=>event(5,1,1+k*4,[m],3))],compare:'B / misma figura, otra altura',variation:e=>e.map(x=>({...x,notes:x.notes.map(m=>m+2)})),quiz:['Mi→Fa tiene…',['Un semitono.','Un tono.'],0,'Mi y Fa son alturas consecutivas. No hay una tecla intermedia entre ellas.'],takeaway:'Pista 5, patrón melódico de dos compases; escena 1. Conservá el ritmo que te guste del bloque anterior.'},
 {title:'Un lugar al que volver',bars:4,tempo:75,main:5,form:['presentar','explorar','volver','final'],
  goal:'Entender escala, grado y centro tonal para elegir finales con intención.',recall:'Tocá dos notas cercanas y un salto. Buscá sus distancias sin usar las etiquetas como única ayuda.',
  question:'¿Te suena más cerrado el final en Do o en Re?',answer:'Sobre el Do grave sostenido, A termina en Do y B en Re. Do suele afirmar el centro; Re puede dejar continuidad. Son efectos en este contexto, no una ley que obligue a cerrar siempre en la raíz.',
  ideas:[['Escala mayor','Una escala organiza alturas por un patrón de distancias. La mayor usa tono–tono–semitono–tono–tono–tono–semitono. Desde Do produce Do, Re, Mi, Fa, Sol, La, Si y Do. Las notas no son una lista que debas recorrer entera.'],['Grado','Numeramos la escala desde su centro: Do es 1, Re 2, Mi 3… Si 7. Un grado describe una relación; al cambiar de tonalidad cambian las notas, no esos números.'],['Centro tonal','Es la nota que el contexto hace sentir como referencia o llegada. Repetición, bajo y finales ayudan a establecerla. Usar las notas de Do mayor no garantiza por sí solo que Do se sienta como centro. En esta prueba el bajo lo vuelve explícito.']],
  map:[['nota','Do','Re','Mi','Fa','Sol','La','Si','Do'],['grado','1','2','3','4','5','6','7','1']],
  task:'Dejá un Do grave de referencia. Inventá una frase con Do, Re, Mi, Sol y La. Hacé dos finales distintos manteniendo igual todo lo anterior.',
  challenge:'Componé una melodía de cuatro compases. Elegí si el final invita a continuar o a detenerse y explicá qué cambio te ayudó. El acompañamiento puede ser sólo un Do grave.',
  check:'Puedo explicar qué significa grado 1 y elegir entre dos finales después de escucharlos, sin afirmar que uno es universalmente correcto.',transfer:'Probá tu melodía sin el Do grave. ¿Sigue sintiéndose el mismo centro? Cambiá sólo el final si querés reforzarlo.',hint:'Si cuatro compases cuestan, repetí los primeros dos y cambiá el último sonido. La repetición también construye forma.',
  events:[...Array.from({length:4},(_,b)=>event(3,b,1,[48],16)),...[60,64,67,69,67,64,62,60].map((m,k)=>event(5,Math.floor(k/2),k%2?9:1,[m],6))],compare:'B / dejar el final en Re',variation:e=>e.map(x=>x.t===5&&x.at===56?{...x,notes:[62]}:x),quiz:['¿Grado 3 significa siempre Mi?',['Sí, en cualquier tonalidad.','No: es la tercera nota de la escala elegida.'],1,'Mi es grado 3 en Do mayor. El grado nombra una relación, no una tecla fija.'],takeaway:'Pistas 3 y 5, patrones de cuatro compases; escena 1. Guardá tu final elegido.'},
 {title:'Construir un acorde, no memorizarlo',bars:2,tempo:70,main:4,form:['Do mayor','La menor'],
  goal:'Construir tríadas mayores y menores desde una raíz.',recall:'Ubicá Do, Mi y Sol por su distancia. Recordá que cuatro semitonos no son cuatro botones de la fila inferior.',
  question:'¿Qué cambia cuando el segundo compás pasa a La menor?',answer:'A cambia de acorde; B conserva Do mayor. No hay un sentimiento obligatorio para mayor o menor. Escuchá la diferencia y decidí si querés cambio o permanencia.',
  ideas:[['Tríada y raíz','Una tríada contiene tres notas. La raíz es la nota desde la que construimos el acorde; no tiene que ser siempre la más grave de cualquier disposición, aunque por ahora la pondremos abajo.'],['Mayor y menor','Desde la raíz, una tríada mayor coloca notas a 0, 4 y 7 semitonos; una menor a 0, 3 y 7. La tercera cambia un semitono; la quinta queda a la misma distancia. C = Do–Mi–Sol; Am = La–Do–Mi.'],['Construcción desde una escala','En Do mayor, elegí una nota, salteá una, tomá otra, salteá una y tomá otra: Do–Mi–Sol. Hacerlo desde Re da Re–Fa–La, un acorde menor. El resultado depende de las distancias, no de que todas las teclas sean de la fila inferior.']],
  map:[['tipo','raíz','tercera','quinta'],['mayor','0','4','7'],['menor','0','3','7']],
  task:'Escuchá C y Am. Construí además F = Fa–La–Do y G = Sol–Si–Re contando sus distancias. Tocá las notas juntas y luego separadas para reconocer el mismo material.',
  challenge:'Elegí dos de esos acordes para una miniatura de dos compases. Cambiá su orden y elegí cuál querés conservar. Escribí qué notas componen cada uno, no sólo su símbolo.',
  check:'Puedo construir una tríada mayor y una menor desde una raíz diferente a Do, comprobando las distancias.',transfer:'Sin mirar la fórmula, construí Re menor. Después comprobá: Re–Fa–La, 0–3–7 semitonos.',hint:'Si no suena como esperabas, inspeccioná cada nota por separado. No corrijas tres notas simultáneamente: revisá primero la tercera.',
  events:harmony(['C','Am']),compare:'B / repetir Do mayor',variation:e=>e.map(x=>x.at===16?{...x,notes:CHORDS.C}:x),quiz:['¿Qué distancia distingue una tríada mayor de una menor?',['La tercera: 4 frente a 3 semitonos.','La quinta: 7 frente a 6 semitonos.'],0,'Ambas tienen quinta justa a 7 semitonos. La tercera mayor mide 4; la menor, 3.'],takeaway:'Pista 4, patrón de dos compases con tus dos acordes; escena 1.'},
 {title:'La misma melodía, dos acompañamientos',bars:4,tempo:70,main:4,form:['C','Am','F','C'],
  goal:'Relacionar las notas de tu melodía con los acordes que elegís.',recall:'Construí C, Am y F antes de abrir el modelo. Si necesitás la fórmula, repasá el taller 5.',
  question:'¿La nota Mi obliga a usar Do mayor?',answer:'No. Mi pertenece tanto a C (Do–Mi–Sol) como a Am (La–Do–Mi). A cambia a Am en el segundo compás; B mantiene C, con la misma melodía. La melodía admite más de una armonización.',
  ideas:[['Nota del acorde','Es una altura que forma parte del acorde que suena en ese momento. Mi es la tercera de C y la quinta de Am. La misma tecla puede cumplir funciones diferentes.'],['Nota de paso','Una melodía también puede usar alturas ajenas al acorde. Una nota breve que conecta otras puede aportar movimiento. Su duración, posición y resolución importan: no hay que borrar automáticamente toda nota que no esté en la tríada.'],['Armonizar','Es elegir un acompañamiento para una melodía. Mirá primero las notas largas o destacadas y probá acordes que las contengan. Después escuchá el recorrido completo: acertar cada nota por separado no garantiza una frase coherente.']],
  map:[['nota melódica','acorde posible','relación'],['Mi','C','tercera'],['Mi','Am','quinta'],['Fa','F','raíz']],
  task:'Escuchá la melodía del ejemplo sin modificarla y compará los dos acompañamientos. Después elegí una melodía tuya de cuatro compases y probá dos armonizaciones.',
  challenge:'Conservá iguales las notas y el ritmo de tu melodía. Cambiá al menos un acorde entre tus dos pruebas. Elegí según lo que querés escuchar, no según cuál tiene más cambios.',
  check:'Puedo nombrar al menos una nota común entre mi melodía y cada acorde de apoyo, y explicar por qué conservé una de las versiones.',transfer:'Usá otra melodía, no una copia del ejemplo. Si la receta anterior no encaja, cambiá el acompañamiento.',hint:'Empezá con una nota larga Mi. Probá C y Am debajo. Cuando oigas el cambio, agregá otra nota melódica.',
  events:[...harmony(['C','Am','F','C']),...[64,64,65,64].map((m,b)=>event(5,b,1,[m],12))],compare:'B / Mi sobre C',variation:e=>e.map(x=>x.t===4&&x.at===16?{...x,notes:CHORDS.C}:x),quiz:['Sobre Am, Mi es…',['La raíz.','La quinta.'],1,'Am = La–Do–Mi. Mi sigue siendo la misma altura, pero cumple otra función que sobre C.'],takeaway:'Pistas 4 y 5, patrones de cuatro compases; escena 1. Guardá la armonización que elegiste para tu melodía.'},
 {title:'Preparar una llegada',bars:4,tempo:70,main:4,form:['I · C','IV · F','V · G','I · C'],
  goal:'Usar el recorrido armónico para crear continuidad o cierre.',recall:'Recordá qué era el centro tonal y construí las tríadas de Do, Fa y Sol.',
  question:'¿La última armonía parece llegar o seguir esperando?',answer:'A vuelve a C; B termina en G. En este contexto de Do mayor, el regreso a C suele resolver la expectativa. Dejar G puede ser útil si querés entrar en otra sección.',
  ideas:[['Acordes y grados','Los números romanos indican la raíz dentro de la escala. En Do mayor: I = C, IV = F, V = G, vi = Am. Las mayúsculas señalan aquí acordes mayores y las minúsculas menores. No son números de pistas.'],['Función armónica','En este recorrido tonal, I establece referencia, IV se aleja y V prepara el regreso. Son relaciones de un contexto musical, no emociones fijas que cada acorde lleve siempre consigo.'],['Ritmo armónico','Es la frecuencia con que cambian los acordes. Una nota por pulso y un acorde por compás son ritmos de capas distintas. Mantener un acorde dos compases deja otro espacio para la melodía que cambiarlo a cada pulso.']],
  map:[['grado','I','IV','V','vi'],['en Do mayor','C','F','G','Am']],
  task:'Probá C–F–G–C y comparalo con C–F–G–G. Después armá dos recorridos propios usando C, F, G y Am; decidí dónde querés una llegada.',
  challenge:'Componé cuatro compases que puedan servir como comienzo o como final de una pieza. Elegí cuál de esos dos papeles querés que cumplan.',
  check:'Puedo identificar el centro del ejemplo, explicar qué significan I/IV/V y cambiar el final de mi progresión con una intención audible.',transfer:'Duplicá tu progresión en el OP-XY y sostené cada acorde el doble. Escuchá qué cambia sin modificar el orden.',hint:'Si todos los acordes parecen equivalentes, escuchá sólo G→C varias veces. Después recuperá los compases anteriores.',
  events:harmony(['C','F','G','C'],true),compare:'B / dejar la llegada pendiente',variation:e=>e.map(x=>x.at===48?{...x,notes:x.t===3?[43]:CHORDS.G}:x),quiz:['¿Qué cambia al sostener cada acorde dos compases en lugar de uno?',['El ritmo armónico.','Necesariamente la tonalidad.'],0,'Cambia cuánto tiempo ocupa cada armonía. Podés conservar los mismos acordes y el mismo centro tonal.'],takeaway:'Pistas 3 y 4, patrones de cuatro compases; escena 1. Conservá el comienzo o final que diseñaste.'},
 {title:'Mover menos, conectar mejor',bars:4,tempo:70,main:4,form:['C','Am','F','C'],
  goal:'Conectar los acordes como líneas y separar raíz de posición de las voces.',recall:'Probá tu progresión anterior. Escuchá sólo el sonido más agudo: ¿salta mucho o se mueve cerca?',
  question:'¿Pueden mantenerse los acordes aunque cambie su disposición?',answer:'Sí. A acerca las voces superiores; B usa las tríadas en posición fundamental. El bajo conserva las raíces. La armonía sigue siendo C–Am–F–C, pero cambian registro y movimiento.',
  ideas:[['Disposición de voces','Un acorde no tiene una única forma de acomodarse. Do–Mi–Sol y Mi–Sol–Do contienen las mismas clases de nota. Elegir registro y orden modifica la textura sin necesariamente cambiar la identidad armónica.'],['Inversión','Si la nota más grave del acorde no es la raíz, hablamos de inversión: Am/C coloca Do en el bajo. Pero si otra pista toca La más grave, el conjunto vuelve a tener La abajo. No confundas la disposición de la pista 4 con el bajo de toda la música.'],['Conducción de voces','Seguimos cada línea entre acordes. De Do–Mi–Sol a Do–Mi–La se conservan dos alturas y sólo una se mueve. Los movimientos pequeños conectan; los saltos pueden destacar un contraste. Elegí, no conviertas el mínimo movimiento en una obligación.']],
  map:[['voz','C','Am','F','C'],['inferior','Do','Do','Do','Do'],['media','Mi','Mi','Fa','Mi'],['superior','Sol','La','La','Sol']],
  task:'Escuchá primero los acordes sin mirar. Después seguí una sola voz en el mapa. Reacomodá una progresión tuya manteniendo sus raíces en la pista 3.',
  challenge:'Hacé dos disposiciones del mismo acompañamiento: una conectada y otra con un salto intencional. Elegí dónde te sirve cada una.',
  check:'Puedo seguir una voz entre acordes y explicar por qué cambiar su posición no equivale automáticamente a cambiar de acorde.',transfer:'Aplicá el procedimiento a otra progresión de tus talleres 6 o 7. No copies las posiciones de esta tabla.',hint:'Primero mantené una nota común entre dos acordes. Después buscá la posición cercana de las restantes.',
  events:[...harmony(['C','Am','F','C'],true).filter(e=>e.t===3),...[[60,64,67],[60,64,69],[60,65,69],[60,64,67]].map((n,b)=>event(4,b,1,n,16))],compare:'B / otras posiciones',variation:e=>e.map(x=>x.t===4?{...x,notes:CHORDS[['C','Am','F','C'][x.at/16]]}:x),quiz:['Do–Mi–La en pista 4 y La grave en pista 3: ¿cuál es el bajo del conjunto?',['Do.','La.'],1,'La pista 3 está más grave: el bajo total es La. Mirá todas las capas, no sólo la posición de la mano.'],takeaway:'Pistas 3 y 4 de cuatro compases; escena 1. Guardá tu disposición y mantené otra versión para comparar.'},
 {title:'Agregar color y elegir un destino',bars:4,tempo:70,main:4,form:['ii · Dm7','V · G7','I · Cmaj7','I · Cmaj7'],
  goal:'Entender las séptimas y aplicarlas a una progresión que podés reconocer.',recall:'Construí Re–Fa–La, Sol–Si–Re y Do–Mi–Sol. Recontá sus terceras si no recordás cuál es menor.',
  question:'¿Cómo cambia el recorrido al quitar las séptimas?',answer:'A agrega Do a Dm, Fa a G y Si a C. B deja tríadas. Las raíces y el orden siguen iguales. La séptima amplía el color y las relaciones de tensión; no hace automáticamente mejor al acorde.',
  ideas:[['Una cuarta nota','Sobre una tríada, otra tercera añade una séptima respecto de la raíz. Cmaj7 lleva Si, a 11 semitonos de Do; C7 llevaría Sib, a 10. Dm7 combina tríada menor y séptima menor. Conviene construir cada acorde antes de reducirlo a dos voces.'],['ii–V–I','En Do mayor, ii = Dm, V = G, I = C. Ahora usamos Dm7–G7–Cmaj7. Es otra manera de preparar una llegada tonal. Primero escuchá el bajo Re–Sol–Do; después las notas que se acercan al acorde final.'],['Destino melódico','Fa pertenece a Dm7, Si a G7 y Mi a Cmaj7. Podés elegirlas como llegadas de una frase. Decidir el destino antes de llenar el camino da dirección; no hace falta tocar todas las notas de una escala.']],
  map:[['acorde','raíz','tercera','quinta','séptima'],['Dm7','Re','Fa','La','Do'],['G7','Sol','Si','Re','Fa'],['Cmaj7','Do','Mi','Sol','Si']],
  task:'Construí primero las tríadas, luego agregá sus séptimas. Cuando reconozcas la llegada, inventá una frase corta en pista 5 que termine en una nota del acorde final.',
  challenge:'Componé cuatro compases con una llegada elegida. Puede ser este ii–V–I o una progresión anterior enriquecida con séptimas. Conservá espacios para escuchar el acompañamiento.',
  check:'Puedo construir y diferenciar Cmaj7 y C7. Mi frase tiene un destino elegido; puedo mostrar a qué acorde pertenece.',transfer:'Reutilizá el ritmo de un motivo anterior sobre esta armonía. Ajustá sólo las alturas que necesites.',hint:'Empezá la melodía con una sola llegada Mi sobre Cmaj7. Recién después agregá dos notas antes de ella.',
  events:harmony(['Dm7','G7','Cmaj7','Cmaj7'],true),compare:'B / las tríadas',variation:e=>e.map(x=>x.t===4?{...x,notes:x.notes.filter(m=>m!==[60,65,71,71][x.at/16])}:x),quiz:['¿Qué nota distingue Cmaj7 de C7?',['Si frente a Sib.','Mi frente a Mib.'],0,'Ambos conservan Do–Mi–Sol. Cambia la séptima: Si en Cmaj7, Sib en C7.'],takeaway:'Pistas 3/4 con cuatro compases y tu melodía en 5 si la agregaste; escena 1. Conservá la versión que elegiste.'},
 {title:'Conversar dentro de un blues',bars:12,tempo:85,main:5,swing:2/3,form:BLUES,
  goal:'Orientarte en una forma, dejar espacio y explorar fraseo con swing.',recall:'Escuchá tu motivo del taller 2. ¿Qué parte repetirías como pregunta y cuál cambiarías para responder?',
  question:'¿Qué cambia entre A y B si las notas y los compases son iguales?',answer:'A retrasa la segunda corchea de cada pulso usando una proporción didáctica 2:1. B usa corcheas iguales. El swing real cambia según tempo e intérprete: no es una fórmula fija ni se reduce a mover notas.',
  ideas:[['La forma del blues','Usamos doce compases: C7×4 / F7–F7–C7–C7 / G7–F7–C7–C7. Los números de compás siguen avanzando aunque un acorde se repita. En el OP-XY separamos tres secciones de cuatro compases.'],['Pregunta, respuesta y color','Un motivo que reaparece permite reconocer una conversación. Para explorar usamos Do–Mib–Fa–Sol–Sib, pentatónica menor de Do. Mib contra Mi del C7 crea un roce característico: escuchá su efecto, no lo clasifiques automáticamente como error.'],['Fraseo','Importan dónde entrás, cuánto sostenés, qué acentuás y dónde callás. El ejemplo compara dos distribuciones temporales; no imita a un músico real. Escuchá también jazz grabado e intentá reproducir un fragmento muy corto en el teclado, sin cantar.']],
  map:[['sección','compases','recorrido'],['1','1–4','C7 · C7 · C7 · C7'],['2','5–8','F7 · F7 · C7 · C7'],['3','9–12','G7 · F7 · C7 · C7']],
  task:'Escuchá una vuelta siguiendo los compases. Después prepará una pregunta de dos compases, dejá dos de silencio y respondé cambiando su final. Elegí entre fraseo recto o con swing para tu propia versión.',
  challenge:'Terminá una vuelta de blues con un motivo propio y al menos dos compases completos de silencio melódico. Anotá qué fragmento de música real escuchaste y qué detalle de su fraseo te interesó.',
  check:'Puedo encontrar los compases 5 y 9 sin reiniciar el conteo cuando se repite un acorde. Mi respuesta conserva una relación audible con la pregunta.',transfer:'Volvé a una pieza recta anterior. Probá el mismo motivo sin swing: ¿qué conservarías de su articulación?',hint:'Mantené la base del ejemplo y escribí sólo la pista 5. Usá tres alturas antes de intentar las cinco de la pentatónica.',
  events:[...harmony(BLUES,true),...[0,4,8].flatMap(b=>[event(5,b,1,[60],2),event(5,b,3,[63],2),event(5,b,5,[65],2),event(5,b,7,[67],2),event(5,b+1,1,[b===4?65:60],6)])],compare:'B / corcheas iguales',variation:e=>e,quiz:['¿El compás 4 pasa a ser compás 1 porque sigue sonando C7?',['No: el conteo de la forma continúa.','Sí: cada repetición de acorde reinicia la forma.'],0,'Los acordes y el conteo de compases son capas distintas. El primer F7 llega en el compás global 5.'],takeaway:'Tres escenas de cuatro compases. Pistas 3/4 sostienen el blues; 5 lleva tu pregunta y respuesta. Canción: 1→2→3.'},
 {title:'Desarrollar sin empezar de nuevo',bars:8,tempo:75,main:5,form:['idea','idea','idea','pausa','más arriba','menos capas','menos capas','cierre'],
  goal:'Usar registro y textura para transformar una idea conocida.',recall:'Elegí una miniatura tuya. Antes de agregar nada, señalá qué parte querés que siga siendo reconocible.',
  question:'¿Se necesita otra progresión para que cambie la segunda sección?',answer:'No. A eleva el motivo una octava y retira parte del acompañamiento. B repite la primera sección. El material puede desarrollarse cambiando registro y densidad, no sólo inventando nuevos acordes.',
  ideas:[['Registro','La misma nota en otra octava conserva su nombre y cambia su altura. Subir un motivo puede despejar el bajo o darle otro protagonismo. Escuchá el efecto en la mezcla, no aislado.'],['Textura y densidad','Textura es cómo se relacionan las capas; densidad, cuánto material ocupa el espacio. Sacar acordes puede hacer visible una melodía. Cada pista debe tener un papel, no estar presente sólo porque está disponible.'],['Timbre y articulación','El sonido elegido modifica cómo se perciben duración y ataque. En tu OP-XY probá el mismo patrón con un sonido sostenido y otro corto, a volumen parecido. No cambies también las notas si querés escuchar qué aporta el timbre.']],
  map:[['decisión','qué conservás','qué transformás'],['registro','motivo','octava'],['textura','armonía de referencia','capas presentes'],['timbre','notas y ritmo','sonido']],
  task:'Usá una idea propia de cuatro compases. Construí otra sección cambiando dos aspectos como máximo: registro, cantidad de pistas, duración o timbre.',
  challenge:'Terminá una pieza de ocho compases con dos secciones relacionadas. Sacá una capa y decidí si realmente necesitás devolverla.',
  check:'Puedo señalar qué hace reconocible la segunda sección y qué cambió. Puedo justificar el papel de cada pista que dejé.',transfer:'Elegí un detalle de una grabación —una pausa, una entrada o una textura— y probá esa estrategia con tus notas, sin copiar toda la pieza.',hint:'Duplicá una sección. En la copia, quitá los acordes de dos compases y mantené el motivo. Después decidí si hace falta un cambio de registro.',
  events:[...harmony(['C','Am','F','C','C','Am','F','C'],true).filter(e=>!(e.t===4&&e.at>=80)),...[0,1,2,4,5,6].flatMap(b=>[event(5,b,1,[b<4?60:72],3),event(5,b,9,[b<4?64:76],3)]),event(5,7,1,[72],8)],compare:'B / repetir sin desarrollar',variation:e=>[...cloneEvents(e.filter(x=>x.at<64)),...e.filter(x=>x.at<64).map(x=>({...x,at:x.at+64,notes:[...x.notes]}))],quiz:['¿Quitar una pista obliga a cambiar los acordes de las otras?',['Sí.','No: puede cambiar la textura manteniendo la armonía.'],1,'Las capas pueden cambiar sin modificar el recorrido de acordes. Comprobalo escuchando el conjunto.'],takeaway:'Dos escenas de cuatro compases; canción 1→2. En cada pista guardá patrones independientes para poder variar sin alterar la primera sección.'},
 {title:'Tu primera pieza, tus decisiones',bars:16,tempo:75,main:5,form:['A','A','A','A','A variada','A variada','A variada','A variada','B','B','B','B','final','final','final','final'],
  goal:'Componer, revisar y terminar una pieza breve sin depender de una receta de notas.',recall:'Elegí dos trabajos tuyos que te gusten. Explicá qué conservarías de cada uno antes de mirar el modelo final.',
  question:'¿Qué diferencia escuchás entre una forma desarrollada y cuatro repeticiones idénticas?',answer:'El ejemplo A tiene contraste de melodía y armonía; B repite cuatro veces su primera sección. Una repetición larga también puede funcionar. La pregunta es si sostiene la intención que elegiste, no si cumple una cantidad obligatoria de cambios.',
  ideas:[['Intención','Antes de programar, elegí una dirección: una pieza tranquila que se abre, un groove que gana energía, una melodía que vuelve a casa. No necesitás una historia compleja; sí un criterio para decidir qué conservar.'],['Forma','La forma organiza lo que vuelve y lo que contrasta. A–A′–B–final es una posibilidad, no un molde obligatorio. Podés diseñar otra distribución en los dieciséis compases del espacio de trabajo.'],['Revisión','Escuchá una pasada completa sin tocar controles. Elegí un problema concreto: entrada demasiado larga, melodía tapada, contraste abrupto o final confuso. Cambiá una cosa, compará y guardá una versión. Saber terminar incluye decidir qué no agregar.']],
  map:[['pasada','pregunta'],['1 · identidad','¿Reconozco una idea que vuelve?'],['2 · contraste','¿Los cambios ayudan a mi intención?'],['3 · cierre','¿Quiero que continúe o que termine aquí?']],
  task:'Empezá en C, no copiando A. Recuperá motivos tuyos, elegí una armonía y diseñá el recorrido. El modelo es una referencia que podés escuchar después, no una solución que debas reproducir.',
  challenge:'Terminá una pieza propia de dieciséis compases y dos versiones de una decisión importante. Elegí una versión final y anotá por qué la preferís. No es obligatorio usar ii–V–I, swing ni todos los recursos del curso.',
  check:'Puedo empezar sin la grilla del ejemplo, desarrollar un motivo propio, explicar dos decisiones musicales y revisar un problema por escucha. La pieza tiene un cierre intencional y una versión guardada.',transfer:'En otra sesión, empezá una miniatura nueva con otra restricción. Si necesitás copiar nuevamente todo el modelo, volvé al bloque cuya decisión todavía no podés tomar.',hint:'Si te bloqueás, elegí un ritmo del bloque 1, una melodía del 2 y dos acordes del 3. Construí cuatro compases; después desarrollalos. Usar material propio anterior también es componer.',
  events:[...harmony(['C','Am','F','G','C','Am','F','G','Am','F','C','G','F','G','C','C'],true),...Array.from({length:16},(_,b)=>event(5,b,1,[b===15?60:[64,60,65,62][b%4]],8))],compare:'B / repetir una sección',variation:e=>[0,1,2,3].flatMap(n=>e.filter(x=>x.at<64).map(x=>({...x,at:x.at+n*64,notes:[...x.notes]}))),quiz:['¿La versión final tiene que usar todos los recursos aprendidos?',['Sí, para demostrar que los sé.','No: elijo los que sirven a mi intención.'],1,'Componer también es seleccionar y quitar. Los recursos son opciones, no una lista que debas agotar.'],takeaway:'Cuatro escenas de cuatro compases con tu material; canción con el orden que decidiste. Guardá la pieza y una versión anterior para comparar.'},
 {title:'Dar cuerpo: batería y bajo con espacio',bars:8,tempo:82,main:1,form:['A pulso','A respuesta','A variada','aire','B pulso','B respuesta','B variada','entrada'],goal:'Construir una base que apoye tu motivo sin taparlo.',recall:'Escuchá el motivo de tu canción sin acompañamiento y marcá dónde respira.',question:'¿Cuál base deja que el motivo entre sin competir?',answer:'A pone bombo en 1 y 9, caja en 5 y 13, y deja hueco antes de la respuesta. B llena cada subdivisión: puede servir para otra intención, pero reduce el espacio de la melodía.',ideas:[['Roles y huecos','La batería no es un metrónomo decorativo: bombo afirma apoyo, caja organiza respuesta y hi-hat puede indicar subdivisión. El bajo elige raíz y dirección; no necesita duplicar cada ataque del bombo.'],['Ejemplo trabajado','En C: pista 1 bombo pasos 1/9, caja 5/13, hi-hat 3/7/11/15. Pista 3 toca Do en 1 durante 8 pasos y Sol en 9 durante 6. La pista 5 espera hasta el paso 13: el hueco hace legible la entrada.'],['Diagnóstico','Si todo suena pesado, silenciá primero hi-hat, luego quitá un ataque de bajo. Si pierde dirección, devolvé la raíz al comienzo del compás antes de agregar notas.']],map:[['pista','1 batería','3 bajo','5 melodía'],['función','pulso/hueco','raíz/dirección','motivo/aire']],task:'Programá el ejemplo un compás. Desplazá el hi-hat del paso 3 al 4 sin mover el bombo; escuchá que cambia el empuje, no el tempo. Luego dejá vacío el paso anterior a tu entrada melódica.',challenge:'Incorporá batería y bajo a CANCIÓN-03. Guardá una versión con menos capas y otra con más; elegí por escucha cuál deja respirar el motivo.',check:'Puedo señalar qué pista sostiene pulso, cuál dirección y qué hueco protege la melodía.',transfer:'Probá la misma base sobre otra armonía sin cambiar el patrón de batería; decidí qué sí debe cambiar en el bajo.',hint:'Empezá sólo con bombo 1/9 y bajo Do en 1. Agregá caja después de que el motivo sea audible.',events:[...Array.from({length:8},(_,b)=>[event(1,b,1,[53],2),event(1,b,5,[55],2),event(1,b,9,[53],2),event(1,b,13,[55],2),event(1,b,3,[57],1),event(1,b,7,[57],1),event(1,b,11,[57],1),event(1,b,15,[57],1)]).flat(),...['C','Am','F','G','C','Am','F','G'].flatMap((n,b)=>[event(3,b,1,[roots[n]],8),event(3,b,9,[roots[n]+7],6)]),...Array.from({length:8},(_,b)=>event(5,b,13,[b<4?64:67],3))],compare:'B / llenar subdivisiones',variation:e=>[...e,...Array.from({length:8},(_,b)=>[2,4,6,8,10,12,14,16].map(s=>event(1,b,s,[57],1))).flat()],quiz:['Mover un hi-hat de 3 a 4…',['Cambia el empuje, no los BPM.','Baja el tempo.'],0,'La posición cambia el ritmo; el tempo sigue siendo 82 BPM.'],takeaway:'CANCIÓN-03: 8 compases con batería en 1, bajo en 3 y melodía en 5. Escena 1=A, escena 2=B.'},
 {title:'Sección B: contraste sin perder A',bars:8,tempo:82,main:4,form:['A','A','A','A','B color','B aire','B alto','vuelta'],goal:'Crear una sección B con contraste de armonía, registro o densidad sin borrar la identidad de A.',recall:'Reproducí A y nombrá una característica que debe mantenerse.',question:'¿B contrasta por cambiar todo o por cambiar una decisión clara?',answer:'A conserva el motivo y cambia registro, densidad y un acorde de destino. B repite A. Ninguna es automáticamente mejor: el contraste debe servir a tu forma.',ideas:[['Copiar antes de variar','Una escena puede recordar qué patrones y mix usa, pero duplicarla no vuelve independientes las notas de cada patrón. En ARRANGE copiá el patrón de cada pista que vas a editar y elegí el patrón nuevo en la escena B antes de cambiar melodía o acordes.'],['Ejemplo trabajado','A: C–Am–F–G, voicings Do–Mi–Sol / Do–Mi–La. B: Am–F–C–G, melodía una octava arriba en los compases 7–8 y sin hi-hat en el primer compás de B. La relación se reconoce; la energía cambia.'],['Error común','Si B parece otra canción, mantené el ritmo del motivo o una nota objetivo. Si no se distingue, retir á una capa o mové la melodía de registro antes de añadir acordes.']],map:[['sección','A','B'],['armonía','C–Am–F–G','Am–F–C–G'],['textura','base completa','aire → entrada']],task:'Copiá los patrones que vas a cambiar. Construí B con la progresión indicada, dejando el primer compás sin hi-hat. Probá la melodía en dos registros.',challenge:'Guardá CANCIÓN-04. Debe contener A y B recuperables: describí qué se mantiene y dos contrastes audibles.',check:'Puedo volver a A sin haber modificado sus patrones y explicar el contraste de B.',transfer:'Hacé una B alternativa cambiando sólo densidad, no armonía.',hint:'Si dudás, mantené el mismo bajo rítmico y cambiá sólo la melodía al registro alto.',events:[...harmony(['C','Am','F','G','Am','F','C','G'],true),...Array.from({length:8},(_,b)=>event(1,b,b===4?9:1,[53],2)),...[64,60,65,62,69,65,72,67].map((m,b)=>event(5,b,9,[m],5))],compare:'B / repetir A',variation:e=>e.map(x=>x.at>=64?{...x,at:x.at-64,notes:[...x.notes]}:x),quiz:['Para proteger A antes de editar B…',['Copio el patrón de cada pista que voy a variar.','Duplico la escena y edito cualquier patrón.'],0,'La escena sola puede seguir apuntando al mismo patrón; copiá el patrón y úsalo en B antes de editar.'],takeaway:'CANCIÓN-04: dos escenas de cuatro compases. A usa patrones originales; B usa copias en las pistas que cambian.'},
 {title:'Transiciones: preparar la siguiente escena',bars:8,tempo:82,main:6,form:['A','A','A','preparar','B','B','B','cerrar'],goal:'Usar una transición breve para que el cambio de escena se entienda como intención.',recall:'Escuchá el límite entre A y B sin tocar; ¿qué señal te ayudaría a anticiparlo?',question:'¿Qué cambio anuncia B sin llenar todo el compás?',answer:'A retira batería en el último pulso del compás 4 y deja una nota de textura corta en el paso 15. B entra con bombo y bajo completos. B sin transición puede funcionar; la comparación muestra una herramienta, no una obligación.',ideas:[['Transición es relación','Una transición conecta energía, registro o tiempo entre secciones. Puede ser quitar, sostener, anticipar o cambiar textura. Una nota no reemplaza una forma: su función depende de lo que viene después.'],['Ejemplo trabajado','Compás 4: bombo sólo en 1, caja ausente en 13, pista 6 toca Sol en paso 15 durante 2 pasos. Compás 5: bajo La en 1 y hi-hat vuelve en 3. El oído recibe aire y una dirección hacia B.'],['Automatización con criterio','Si automatizás un parámetro, grabá un movimiento sólo si podés describir qué transición se oye. La guía oficial indica automatización por pasos; compará con y sin ella antes de conservarla.']],map:[['compás','4 preparar','5 B entra'],['batería','quitar último golpe','pulso completo'],['textura','Sol paso 15','silencio o motivo']],task:'Programá el corte de batería y la nota de textura. Escuchá A→B tres veces. Probá luego la misma transición sin la nota y elegí.',challenge:'CANCIÓN-05: prepará al menos una entrada y un cierre. Guardá una versión seca y otra con una sola automatización audible si realmente ayuda.',check:'Puedo señalar qué se retira, qué anticipa y dónde entra B.',transfer:'Probá una transición sólo con silencio: quitá una capa durante un pulso y medí si la forma sigue clara.',hint:'No agregues fill y automatización a la vez. Empezá quitando un golpe.',events:[...harmony(['C','Am','F','G','Am','F','C','G'],true),...Array.from({length:8},(_,b)=>[event(1,b,1,[53],2),...(b!==3?[event(1,b,9,[53],2)]:[])]).flat(),...Array.from({length:8},(_,b)=>event(5,b,9,[64],4)),event(6,3,15,[67],2)],compare:'B / sin preparación',variation:e=>e.filter(x=>!(x.t===6||x.at===48&&x.t===1)),quiz:['Una transición puede empezar por…',['Quitar una capa antes de agregar otra.','Llenar siempre todos los pasos.'],0,'Quitar crea contraste y deja espacio para que se perciba la entrada.'],takeaway:'CANCIÓN-05: dos transiciones intencionales y una decisión documentada por escucha.'},
 {title:'Revisar, balancear y elegir versión',bars:8,tempo:82,main:5,form:['A','A','A','preparar','B','B','B','final'],goal:'Escuchar una pasada completa, diagnosticar un problema y elegir una versión de tu canción.',recall:'Sin tocar controles, escuchá tu canción y anotá sólo un problema observable.',question:'¿Qué versión deja entender mejor motivo, bajo y forma?',answer:'A baja la armonía cuando entra la melodía y conserva bajo/bombo claros. B mantiene todas las capas al mismo nivel. La elección depende de intención, pero debe poder justificarse por escucha.',ideas:[['Mezcla básica es prioridad','Antes de efectos: verificá rol, registro y nivel. Si melodía y acordes compiten, bajá una capa o mové un voicing. No intentes arreglar con compresión un problema de escritura.'],['Pasada de revisión','Escuchá sin editar: identidad del motivo, función de cada pista, contraste A/B, transición y final. Elegí una sola corrección, guardá otra versión y compará en el mismo volumen.'],['Producto y siguiente ciclo','CANCIÓN-06 incluye varias pistas, forma y dos versiones. El simulador guarda localmente; PROJECT guarda el trabajo real en el OP–XY. La ruta profesional continúa con más canciones, análisis y devolución, no con una etiqueta de “pro”.']],map:[['escucha','motivo','bajo+bombo','A/B','final'],['pregunta','¿se reconoce?','¿apoya?','¿contrasta?','¿cierra?']],task:'Hacé una escucha completa. Bajá la pista 4 o quitá una nota de su voicing cuando tapa la melodía; compará A/B. Conservá ambas versiones antes de elegir.',challenge:'Terminá CANCIÓN-06: forma de 8 compases como maqueta o expandila a 32 mediante escenas A-A-B-A (4 compases cada una). No edites A al construir variaciones: copiá patrones primero.',check:'Puedo nombrar un problema, dos versiones y una razón auditiva para mi elección.',transfer:'Volvé al día siguiente y repetí la rúbrica sin mirar tus notas; si elegís otra versión, anotá por qué.',hint:'Si todo compite, silenciá pista 6 y bajá 4 antes de tocar la melodía.',events:[...harmony(['C','Am','F','G','Am','F','C','C'],true),...Array.from({length:8},(_,b)=>[event(1,b,1,[53],2),event(1,b,9,[53],2)]).flat(),...[64,60,65,62,69,65,67,60].map((m,b)=>event(5,b,9,[m],5)),...Array.from({length:8},(_,b)=>event(4,b,1,CHORDS[['C','Am','F','G','Am','F','C','C'][b]],12))],compare:'B / armonía demasiado presente',variation:e=>[...e,...Array.from({length:8},(_,b)=>event(4,b,13,[72],3))],quiz:['Antes de corregir mezcla, conviene…',['Escuchar una pasada y nombrar un problema.','Mover todos los controles a la vez.'],0,'Una corrección aislada deja comparar causa y resultado.'],takeaway:'CANCIÓN-06: maqueta de 8 compases o A-A-B-A de 32; dos versiones guardadas y una elección escrita.'}
];
// Data corrections kept beside the course data: comparisons must preserve form,
// and the review example demonstrates density rather than an unmodelled fader.
lessonPlans[13].variation=e=>[...cloneEvents(e.filter(x=>x.at<64)),...cloneEvents(e.filter(x=>x.at<64)).map(x=>({...x,at:x.at+64}))];
lessonPlans[14].events=[...harmony(['C','Am','F','G','Am','F','C','G'],true),...Array.from({length:8},(_,b)=>[event(1,b,1,[53],2),event(1,b,9,[53],2)]).flat(),...Array.from({length:8},(_,b)=>event(5,b,9,[64],4)),event(6,3,15,[67],2)];
lessonPlans[14].variation=e=>[...e.filter(x=>x.t!==6),event(1,3,13,[55],2)];
lessonPlans[15].challenge='Terminá CANCIÓN-06: forma de 8 compases como maqueta o expandila a 32 como A(8)–A′(8)–B(8)–A″(8), usando ocho escenas de cuatro compases. No edites A al construir variaciones: copiá patrones primero.';
lessonPlans[15].hint='Si todo compite, silenciá pista 6 y quitá una nota del voicing de pista 4 antes de tocar la melodía.';
lessonPlans[15].events=[...harmony(['C','Am','F','G','Am','F','C','C'],true),...Array.from({length:8},(_,b)=>[event(1,b,1,[53],2),event(1,b,9,[53],2)]).flat(),...[64,60,65,62,69,65,67,60].map((m,b)=>event(5,b,9,[m],5))];
lessonPlans[15].compare='B / armonía más liviana';
lessonPlans[15].variation=e=>e.map(x=>x.t===4&&x.at>=64?{...x,notes:x.notes.filter((_,n)=>n!==1)}:x);
lessonPlans[15].takeaway='CANCIÓN-06: maqueta de 8 compases o A(8)–A′(8)–B(8)–A″(8) de 32; dos versiones guardadas y una elección escrita.';
const noteNames=['Do','Do#','Re','Mib','Mi','Fa','Fa#','Sol','Sol#','La','Sib','Si'];
const naturalMidi=[53,55,57,59,60,62,64,65,67,69,71,72,74,76],upperMidi=[54,56,58,61,63,66,68,70,73,75];
const noteName=m=>noteNames[((m%12)+12)%12],pitchLabel=m=>noteName(m)+(Math.floor(m/12)-1);
function keyForMidi(m){let p=m,oct=0;while(p<53){p+=12;oct--;}while(p>76){p-=12;oct++;}const i=naturalMidi.indexOf(p);return {id:i>=0?'n'+i:'u'+upperMidi.indexOf(p),oct};}
function eventsAt(es,t,b,s){return es.filter(e=>e.t===t&&e.at===b*16+s);}
function soundingAt(es,t,k){return es.filter(e=>e.t===t&&e.at<=k&&e.at+e.len>k);}
function scenePlan(p){return Array.from({length:Math.ceil(p.bars/4)},(_,i)=>({scene:i+1,from:i*4,bars:Math.min(4,p.bars-i*4)}));}
function stepTime(step,bpm,swing=.5){const beat=Math.floor(step/4),part=step%4;return (beat+[0,swing/2,swing,(1+swing)/2][part])*60/bpm;}
