// Cinco piezas nuevas; dentro de cada ciclo, cada capítulo desarrolla la misma pieza.
// Seis actividades por capítulo: 30 minutos de núcleo. La extensión es opcional.
const DEEP_CURRICULUM = [
  {
    activities:[
      {minutes:4,action:'Empezá la pieza 1 en «Mi composición (C)» vacía, pista 5 (motivo). Elegí 75–95 BPM, mantenelos y marcá cuatro pulsos por vuelta. Ubicá sus comienzos: pasos 1, 5, 9 y 13.',deliverable:'Proyecto de un compás y un pulso que podés seguir sin notas.'},
      {minutes:5,action:'Poné dos Do cortos de un paso: uno en 1 y otro en un comienzo de pulso que elijas. Escuchá cuatro vueltas, también durante los huecos.',deliverable:'Tu primera idea rítmica con dos ataques y silencios reales.'},
      {minutes:6,action:'Pulsá «conservar mi versión actual». Seleccioná el segundo ataque y usá «← un paso» o «un paso →» hasta otro comienzo de pulso: mantiene notas y duración. Alterná «Mi versión guardada» y «Mi composición (C)» y escuchá al mismo tempo.',deliverable:'Dos versiones cuya única diferencia podés señalar en la grilla.'},
      {minutes:5,action:'Elegí la posición: si preferís el original, usá «recuperar versión guardada». Probá sumar un tercer Do corto y después quitarlo; elegí si ayuda a reconocer el gesto o le quita aire.',deliverable:'Motivo propio de dos o tres ataques, con una decisión de espacio.'},
      {minutes:6,action:'Escuchá sin mirar durante cuatro vueltas. Marcá los cuatro pulsos y recordá tu ritmo; si te perdés, quitá el último ataque añadido y repetí la escucha.',deliverable:'Motivo que podés recuperar y pulso que continúa durante el silencio.'},
      {minutes:4,action:'Guardá C del capítulo 1. Anotá posiciones, tempo y una razón para elegirlas. Dejá escrito: «La próxima vez conservaré este compás y le inventaré una respuesta». En OP–XY, guardá también el proyecto.',deliverable:'Pieza 1 iniciada: un compás guardado y una entrada clara al capítulo 2.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: dedicá 10 a inventar dos variantes del mismo motivo, 10 a compararlas al mismo tempo y 10 a guardar una elección. Podés añadir un golpe de apoyo en otra pista si ayuda a oír el pulso; no hace falta completar una batería.',
    theory:'En 4/4 hay cuatro pulsos por compás. Esta grilla los divide en cuatro pasos cada uno: 16 semicorcheas. Los pulsos empiezan en 1, 5, 9 y 13. Tempo es la velocidad del pulso; ataque es el inicio de una nota; duración es cuánto sigue sonando. Quitar ataques reduce densidad, pero el compás tarda lo mismo si los BPM no cambian. Un silencio audible requiere que no siga sonando la nota anterior. Por eso empezamos con notas cortas: permite escuchar el espacio antes de trabajar su duración.',
    workedExample:'Modelo de comparación, no una composición para copiar: a 80 BPM, Do corto en 1 y 9 divide la vuelta en dos apoyos. Mover sólo 9 a 13 deja más espera y un ataque cerca del reinicio. Escuchá ambas opciones mientras el pie mantiene cuatro pulsos. Ahora usá tus propias posiciones y respondé con una observación concreta: «El segundo ataque llega más tarde» o «El hueco me deja escuchar el pulso». Elegí por el gesto que querés repetir, sin buscar la variante con más notas.',
    misconception:'«Menos notas significa un tempo más lento». Comprobalo manteniendo los BPM y contando cuatro pulsos sobre las dos versiones. Cambió la cantidad o la ubicación de los ataques; el tiempo que dura cada vuelta se mantiene.',
    application:'Este capítulo empieza la primera pieza. Su único material necesario es tu motivo de un compás en pista 5. Los modelos A/B sirven para comparar; tu versión C guarda tus decisiones y será la entrada del capítulo 2.',
    mastery:'Puedo mantener el pulso durante un silencio y elegir un motivo propio explicando qué ataque moví, agregué o quité.',
    sources:[{title:'Open Music Theory — Rhythm and meter',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Antes de mirar la grilla, marcá el motivo que recordás. Usá «continuar mi C» para recuperar todas las pistas del capítulo 1; escuchá y comprobá qué recordaste.',deliverable:'El motivo anterior recuperado, con su fuente conservada.'},
      {minutes:5,action:'Copiá el compás 1 al 2 con el control de copiar compás. Escuchá los dos juntos sin cambiar el primero: por ahora, la respuesta es una repetición exacta.',deliverable:'Frase de dos compases y una referencia de igualdad.'},
      {minutes:6,action:'Pulsá «conservar mi versión actual». En el compás 2 seleccioná el último ataque y movelo con «← un paso» o «un paso →» a un paso libre, manteniendo su duración. Alterná «Mi versión guardada» y «Mi composición (C)» para escuchar la diferencia.',deliverable:'Pregunta y respuesta que comparten el comienzo.'},
      {minutes:6,action:'Sin mover ese último inicio, probá duración de un paso y luego una mayor. Dejá que termine antes del final del compás para oír aire; elegí una duración.',deliverable:'Respuesta cuyo ataque y duración cumplen funciones distintas.'},
      {minutes:6,action:'Escuchá cuatro repeticiones de los dos compases. Elegí entre repetición exacta y respuesta modificada; si la relación no se reconoce, restaurá todo salvo el último cambio.',deliverable:'Dos compases relacionados, con al menos un hueco audible en la respuesta.'},
      {minutes:4,action:'Guardá C del capítulo 2 y anotá qué conserva y qué cambia la respuesta. Dejá el ritmo elegido listo: en el capítulo 3 cambiarás alturas sin reemplazar sus ataques.',deliverable:'Pieza 1: motivo y respuesta guardados para melodizar.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: recuperá tu frase de oído durante 5 minutos; inventá otra respuesta durante 10 sin consultar el modelo; compará durante 10 y guardá la preferida en los últimos 5. Conservá la pregunta para reconocer qué aporta cada respuesta.',
    theory:'Un motivo es una idea breve reconocible. Una respuesta conserva algo de la pregunta y transforma otra cosa; puede cambiar un ataque, una duración o un silencio. Un paso sin inicio de nota puede contener la continuación de un sonido anterior. En la maqueta local, cada nota termina como máximo al final de su compás: si repetís la altura al comienzo del siguiente, habrá un ataque nuevo, no una ligadura. Para este capítulo basta una respuesta que termine antes de la barra.',
    workedExample:'Si una pregunta tiene ataques en 1 y 9, la respuesta exacta vuelve a usar 1 y 9. Una variante conserva 1 y mueve el último a 11. Otra conserva 1 y 9, pero alarga el último sonido hasta el paso 12. La primera cambia cuándo empieza; la segunda, cuánto dura. Estas pruebas no requieren tres notas ni una figura nueva completa. En tu motivo, localizá cuál es el último ataque y hacé esa comparación sobre él.',
    misconception:'«Para responder tengo que cambiar todo». Si cambiás cada ataque, quizá escuches otra idea sin relación. Restaurá el comienzo de la pregunta y transformá sólo el final. Si alcanza para oír respuesta, conservá esa economía.',
    application:'La pieza 1 pasa de uno a dos compases. «Continuar mi C» recupera lo guardado, pero no escribe la respuesta por vos: copiá el compás y editá únicamente el segundo. Guardar C del capítulo 2 deja intacto C del capítulo 1.',
    mastery:'Puedo crear una respuesta reconocible y distinguir un cambio de ataque de uno de duración.',
    sources:[{title:'Open Music Theory — Music Theory for the 21st-Century Classroom',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Recuperá de memoria la pregunta y su respuesta; después continuá C del capítulo 2. Escuchá esos dos compases y elegí tres alturas entre Do, Re, Mi, Sol y La.',deliverable:'El ritmo heredado y una paleta breve de alturas.'},
      {minutes:6,action:'En la ayuda, compará Do→Mi con Mi→Fa: contá nombres y saltos de semitono. Después, en pista 5, cambiá las alturas de los ataques existentes usando tu paleta. Probá subir, bajar o repetir; mantené posiciones y duraciones.',deliverable:'Dos compases melodizados y una distancia que podés medir desde su nota de partida.'},
      {minutes:5,action:'Copiá compás 1 a 3 y compás 2 a 4. Escuchá los cuatro: el gesto vuelve en 3 y el último compás conserva por ahora la respuesta conocida.',deliverable:'Primera forma de cuatro compases, sin rellenar con otra idea.'},
      {minutes:6,action:'Conservá tu versión actual. En el compás 4, cambiá sólo la última altura o quitá el último ataque. Alterná la versión guardada y C desde el compás 3; dejá silencio después de cada final y elegí.',deliverable:'Dos cierres comparables y uno elegido por su efecto.'},
      {minutes:6,action:'Reproducí una pasada de los cuatro compases y detenela antes del reinicio. Señalá qué vuelve y dónde termina. Si parece una vuelta más, acortá la respuesta final o ampliá su silencio y reescuchá.',deliverable:'Pieza 1 cerrada: presentación, respuesta, regreso y final.'},
      {minutes:4,action:'Guardá C del capítulo 3 y poné un nombre a la miniatura. Anotá una decisión que tomaste sin mirar el ejemplo y cómo inventarías otra respuesta. La próxima pieza empieza con material nuevo.',deliverable:'Primera miniatura terminada y un procedimiento listo para reutilizar.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: probá el mismo motivo una octava arriba durante 10 minutos, compará identidad y registro durante 10 y guardá tu elección durante 10. También podés desarrollar ocho compases en el OP–XY; la miniatura de cuatro ya cumple el encargo.',
    theory:'Altura es qué nota suena; contorno es si la melodía sube, baja o repite. Un intervalo se nombra contando nombres e incluyendo los extremos: Do (1), Re (2), Mi (3) es una tercera. Para medir su tamaño en semitonos contamos saltos entre teclas consecutivas: Do (0), Do♯ (1), Re (2), Mi♭ (3), Mi (4). Esta tercera es mayor porque mide cuatro semitonos. Mi→Fa tiene dos nombres, pero un solo semitono: es una segunda menor. No son cuentas contradictorias. Cambiar alturas manteniendo ataques conserva la identidad rítmica. Cuatro compases pueden presentar, responder, retomar y concluir; el final depende del contexto, la duración y el silencio posterior.',
    workedExample:'Con un ritmo de dos ataques por compás, un modelo podría presentar Do–Mi, responder Re–Do, repetir Do–Mi y concluir Mi–Do dejando aire. Lo reconocible es la relación entre las frases. Tu ritmo puede tener otra cantidad de ataques: asignale alturas a los que ya existen. Si terminás en Sol, comparalo con Do sobre los mismos compases anteriores; elegí el final que complete tu gesto. No agregues notas para que tu pieza se parezca al modelo.',
    misconception:'«Poner alturas significa escribir un ritmo nuevo». Probá comparar la melodía con el motivo inicial: sus comienzos deberían seguir reconocibles. Si la perdiste, restaurá los ataques y decidí las alturas por separado.',
    application:'Cerrás la pieza 1 en cuatro compases, sin necesitar acordes ni batería. Escuchala con final, no sólo en bucle. El capítulo 4 inicia otra composición y reutiliza tu manera de inventar y responder.',
    mastery:'Puedo terminar una miniatura propia, reconocer su motivo y elegir un cierre escuchando la frase completa.',
    sources:[{title:'Open Music Theory — Melodic intervals and motives',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Empezá la pieza 2 en C vacío. Sin copiar la anterior, recordá el procedimiento de pregunta y respuesta; elegí un tempo cómodo y pista 5 para una melodía nueva.',deliverable:'Nuevo comienzo con una habilidad recuperada, sin importar patrones.'},
      {minutes:6,action:'Inventá un compás con dos o tres ataques y notas de Do, Re, Mi, Sol o La. Cambiá su ritmo inicial respecto de la pieza 1. Copialo al 2 y transformá su última nota.',deliverable:'Pregunta y respuesta nuevas de dos compases.'},
      {minutes:5,action:'Copiá 1 a 3 y 2 a 4. En 4 prepará un final dejando aire después de la última nota; escuchá el recorrido completo sin añadir pistas.',deliverable:'Melodía nueva de cuatro compases con final provisional.'},
      {minutes:6,action:'Probá terminar en Do y después en La, con el mismo ritmo y contexto previo. Si necesitás referencia grave, usá Do debajo de ambos finales; no cambies el bajo entre versiones. Después retiralo y reescuchá.',deliverable:'Dos llegadas comparadas cambiando sólo la última altura.'},
      {minutes:6,action:'Elegí qué llegada sirve a tu frase. Reescuchá los cuatro compases; ajustá sólo la nota anterior al final si necesitás preparar mejor la dirección.',deliverable:'Melodía de cuatro compases con un centro o llegada provisional explicable.'},
      {minutes:4,action:'Guardá C del capítulo 4 y anotá la nota final elegida y una nota larga. Ubicá el grado de esa nota en Do mayor: Do es 1. En la ayuda cambiá la partida del intervalo y comprobá que el grado en la escala no cambia por eso.',deliverable:'Pieza 2 iniciada y una nota importante ubicada respecto de la escala.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: durante 10 construí Do mayor con T–T–ST–T–T–T–ST; durante 10 ubicá sus grados en tu melodía; durante 10 probá otro comienzo manteniendo el final y guardá la opción preferida. Si usás una referencia grave varios compases en el editor, repetí su ataque en cada compás: no se sostiene a través de la barra.',
    theory:'Do mayor contiene Do–Re–Mi–Fa–Sol–La–Si. Su patrón de distancias es tono–tono–semitono–tono–tono–tono–semitono; Mi–Fa y Si–Do están a un semitono. El grado indica una posición en la escala elegida: Do=1, Mi=3 y La=6. Ese 3 incluye Do, Re y Mi; no significa tres semitonos. Do→Mi mide cuatro saltos de semitono. Medir otro intervalo desde La no cambia automáticamente la escala de la pieza. Repetición, notas de apoyo y llegadas ayudan a establecer el centro; usar las notas de Do mayor o acabar en La no demuestra por sí solo una tonalidad.',
    workedExample:'Si tu respuesta termina Mi–Re, conservá Mi y probá sustituir sólo Re por Do; después por La. Escuchá cada final desde el comienzo. Si añadís referencia grave, usá el mismo Do en ambos ensayos: así cambia sólo la última nota de la melodía. Retirá el grave y comprobá qué hace la frase sola. Cambiar también el bajo a La sería un segundo experimento, con otra pregunta. Anotá si oís llegada, continuación, ambigüedad o si todavía no distinguís; mantené el final como una elección provisional antes de elegir acordes.',
    misconception:'«Si usé Do mayor, todas las frases deben terminar en Do». Los mismos materiales pueden apoyar intenciones distintas. Compará Do y La con todo el contexto anterior; elegí por la función que escuchás, sin deducirla sólo de la escala.',
    application:'La pieza 2 empieza con melodía nueva de cuatro compases. La habilidad transferida es organizar pregunta, respuesta y cierre. Su armonía recién se decide en los capítulos 5 y 6.',
    mastery:'Puedo inventar material nuevo con un procedimiento conocido y comparar dos llegadas sin confundir escala con centro tonal.',
    sources:[{title:'Open Music Theory — Scales and key signatures',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Continuá C del capítulo 4 y escuchá tu melodía antes del ejemplo. Recordá la llegada elegida; dejá intacta pista 5 mientras trabajás pista 4 (armonía).',deliverable:'La melodía y sus cuatro compases preservados.'},
      {minutes:6,action:'En la ayuda, mantené Mi y cambiá la partida de Do a La: compará tercera y quinta. En pista 4, compás 1, ingresá Do–Mi–Sol en el mismo paso. Escuchálo y probá La–Do–Mi en su lugar, conservando la melodía.',deliverable:'Dos tríadas probadas y la referencia de sus intervalos identificada.'},
      {minutes:5,action:'Localizá una nota larga o final de tu melodía. Escuchála con C y con Am: ¿buscás apoyo, roce o continuidad? Usá el ensayo breve si necesitás una comparación más simple. Elegí un acompañamiento provisional y escribí un acorde al inicio de cada compás; podés repetirlo.',deliverable:'Cuatro compases acompañados y una primera elección vinculada a una nota importante.'},
      {minutes:6,action:'Pulsá «conservar mi versión actual». Cambiá sólo el acorde del compás 2 o 3 por el otro color; alterná «Mi versión guardada» y C con la misma melodía, tempo y duraciones. Atendé a la nota importante y a cómo sigue la frase.',deliverable:'Dos distribuciones comparables y una diferencia localizada, o una duda honesta de escucha.'},
      {minutes:6,action:'Elegí por el recorrido completo. Si no distinguís, dejá el original como provisional y anotá dónde volver a escuchar. Si el acorde tapa la frase, acortá sus notas y comprobá el espacio. Usá los últimos dos minutos para construir Re menor sin copiar sus notas, con la comprobación de la ayuda.',deliverable:'Acompañamiento elegido y una construcción desde otra raíz, con la ayuda que hayas necesitado.'},
      {minutes:4,action:'Guardá C del capítulo 5. Anotá los cuatro símbolos y una observación: «en el compás…, la nota… tiene apoyo / roza / todavía no distingo». Registrá si construiste Re menor solo o después de corregir. El capítulo 6 retoma tu duda musical.',deliverable:'Pieza 2 con armonía provisional, revisión localizada y evidencia de transferencia.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: dedicá 10 a construir Fa–La–Do y verificar las distancias, 10 a probar F en un único compás de tu pieza y 10 a comparar y guardar. Conservá el acompañamiento previo si F no aporta al recorrido.',
    theory:'Una tríada reúne raíz, tercera y quinta. Contá nombres desde la raíz e incluí los extremos: Do–Re–Mi da una tercera; Do–Re–Mi–Fa–Sol, una quinta. Después medí semitonos desde la raíz = 0: la tríada mayor usa 0/4/7 y la menor 0/3/7. En C = Do–Mi–Sol, Mi está a cuatro semitonos de Do. En Am = La–Do–Mi, Do está a tres de La y Mi a siete. Mayor y menor no tienen una emoción obligatoria. C y Am comparten Do y Mi, pero cambia la raíz y la relación de cada nota. Un acorde puede durar varios compases: en el editor repetimos su ataque en cada barra porque las notas no atraviesan ese límite.',
    workedExample:'Elegí una nota importante antes de elegir toda la armonía. Si es Mi, sostenela y escuchá C debajo; repetí con Am sin mover Mi. Pertenece a ambos: puede haber apoyo en los dos, con otro color del conjunto. Si no distinguís, simplificá: Sol sostenido pertenece a C y está fuera de la tríada Am; su color sobre cada acorde puede ser más fácil de comparar. Describí lo que escuchás sin buscar una emoción correcta. Después volvé a tu nota y escuchá el compás, seguido de la frase completa. Conservá el acorde que sirva al recorrido; si aún dudás, dejá la elección provisional. Dos distribuciones posibles son C–Am–Am–C y C–C–Am–C: comparan sólo el segundo compás, sin resolver tu melodía por vos.',
    misconception:'«Para que suene menor basta bajar una nota cualquiera». La tríada menor se mide desde su raíz. Antes de editar, nombrá la raíz y verificá 0/3/7; C→Am cambia de acorde, mientras C→Cm conserva Do como raíz y baja Mi a Mib.',
    application:'La pieza 2 mantiene sus cuatro compases y suma armonía en pista 4. El guardado del capítulo 4 conserva tu melodía sin acordes; el del 5 prepara una revisión por escucha, sin dar por definitiva la primera distribución.',
    mastery:'Puedo contar nombres y semitonos desde la raíz, construir una tríada desde otra partida y comparar un acorde bajo una nota importante. Sé distinguir una elección de una duda de escucha pendiente.',
    sources:[{title:'Open Music Theory — Triads',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'},{title:'Berklee Online — Harmony 2',url:'https://online.berklee.edu/courses/harmony-2'}]
  },
  {
    activities:[
      {minutes:3,action:'Continuá C del capítulo 5 y escuchá la duda que anotaste. Elegí una nota larga, acentuada o final de tu melodía; nombrá la nota y el acorde que suena debajo.',deliverable:'Una relación melodía–acorde localizada para revisar.'},
      {minutes:5,action:'Comprobá si esa nota está en el acorde y nombrá la raíz desde la que contás. Escuchá el fragmento original y una variante que la mueva a una nota cercana del acorde, sin cambiar inicio ni duración. Primero atendé a apoyo o roce; después a la frase que continúa.',deliverable:'Comparación de una sola nota importante y su efecto dentro del mismo contexto.'},
      {minutes:6,action:'Restaurá la melodía original y probá, en cambio, el otro acorde conocido en ese compás. Compará las dos soluciones con el original y elegí una, incluida conservar lo anterior.',deliverable:'Una decisión sobre cambiar melodía, cambiar acorde o mantener la tensión.'},
      {minutes:6,action:'Escuchá los cuatro compases. Si el acompañamiento tapa la llegada, quitá una voz o acortá el acorde en ese lugar; reescuchá antes de tocar otra pista.',deliverable:'Melodía reconocible y acompañamiento que deja oír su dirección.'},
      {minutes:6,action:'Sin consultar un final resuelto, probá otra última nota o una respuesta final más corta. Compará una pasada de cada versión, deteniendo antes del reinicio, y elegí el cierre.',deliverable:'Pieza 2 terminada con dos decisiones audibles: relación armónica y final.'},
      {minutes:4,action:'Guardá C del capítulo 6 con un nombre. Anotá «qué escuché → qué cambié → qué pasó» y si decidiste solo o con ayuda. La próxima pieza usará otro material y una llegada armónica.',deliverable:'Segunda miniatura cerrada, con una revisión que podés explicar.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: probá durante 10 un bajo simple en pista 3 con la raíz de cada acorde; escuchá durante 10 si aclara o recarga la pieza; dedicá los últimos 10 a elegir y guardar. Otra opción es desarrollar ocho compases en el OP–XY, conservando tu versión de cuatro.',
    theory:'Una nota objetivo es una llegada que destacás por duración, acento o posición. Puede pertenecer al acorde o producir una tensión elegida. En Do mayor, Mi sigue siendo grado 3 de la escala aunque cambie el acorde: es tercera de C (Do–Re–Mi; cuatro semitonos) y quinta de Am (La–Si–Do–Re–Mi; siete). La referencia de escala y la raíz del acorde responden preguntas distintas. Las notas breves también tienen función: sobre C, Do–Re–Mi puede usar Re como nota de paso, porque conecta dos notas del acorde por movimiento conjunto en la misma dirección. Fa→Mi aislado no demuestra una nota de paso: hacen falta contexto y acentos. Armonizar consiste en escuchar esas relaciones, no en convertir todas las notas en notas de tríada.',
    workedExample:'Si tu nota importante es Mi, C la contiene como tercera y Am como quinta: podés cambiar el acompañamiento sin cambiar Mi. Si tenés Do–Re–Mi sobre C, no borres Re sólo por estar fuera de la tríada; escuchá si su brevedad y dirección conectan las llegadas. Si una nota larga roza y no querés ese efecto, compará acercarla al acorde con cambiar el acorde debajo. La mejor versión es la que cumple tu intención y mantiene la frase reconocible.',
    misconception:'«Todas las notas deben pertenecer al acorde». Esa regla elimina movimientos útiles. Escuchá la nota con lo que viene antes y después; distinguí una conexión breve de una llegada que querés destacar. Conservá una tensión si elegiste su efecto.',
    application:'Cerrás la pieza 2 con melodía, armonía y final. Elegir no añadir bajo también es válido. En la pieza 3 reutilizarás este procedimiento para componer otro recorrido, con más libertad y menos notas resueltas por la guía.',
    mastery:'Puedo localizar una relación armónica, comparar una corrección de melodía con una de acorde y cerrar la pieza sin cambiar todo a la vez.',
    sources:[{title:'Open Music Theory — Non-chord tones and harmony',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Empezá la pieza 3 en C vacío. Recordá una decisión de llegada de la pieza anterior y escribí una intención nueva: presentar, alejarte y volver en cuatro compases.',deliverable:'Nuevo encargo breve y un criterio de dirección.'},
      {minutes:6,action:'En pista 4 escribí C–F–G–C, un acorde al inicio de cada compás: Do–Mi–Sol; Fa–La–Do; Sol–Si–Re; Do–Mi–Sol. Usá una duración simple dentro de cada barra.',deliverable:'Recorrido armónico nuevo de cuatro compases.'},
      {minutes:6,action:'En pista 5 inventá un gesto nuevo de dos o tres ataques para el compás 1. Reescribí sólo ese gesto en pista 5 de los compases 2 y 3, variando una llegada; en 4 respondé con menos ataques y dejá aire. No uses aquí «copiar todas sus pistas»: reemplazaría los acordes que ya elegiste.',deliverable:'Material melódico propio que permite escuchar el recorrido.'},
      {minutes:5,action:'Conservá tu versión actual. Compará el último acorde C con G, manteniendo por ahora la melodía; alterná la versión guardada y C, escuchá desde el compás 3 y describí cuál queda más abierto.',deliverable:'Dos finales armónicos comparados con el mismo contexto.'},
      {minutes:6,action:'Elegí el acorde final según tu intención. Si querés reforzar la llegada, probá una última nota de ese acorde y compará con tu nota original; conservá sólo lo que ayude.',deliverable:'Borrador de cuatro compases con un final que podés reconocer.'},
      {minutes:4,action:'Guardá C del capítulo 7. Anotá el recorrido y qué escuchás en los últimos dos compases; en el capítulo 8 conservarás acordes y melodía para revisar su registro.',deliverable:'Pieza 3 iniciada, con dirección elegida y armonía recuperable.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: anotá tu ritmo armónico durante 5 minutos, probá sostener un mismo acorde dos compases durante 10, compará la espera durante 10 y guardá durante 5. En el editor, repetí su ataque al cambiar de barra; no confundas esa representación con un sostén ligado.',
    theory:'En Do mayor, I=C, IV=F y V=G: los números romanos nombran acordes construidos sobre grados, no pistas. En este contexto I puede establecer la referencia, IV alejarse y V preparar la vuelta a I. Una cadencia articula un final o una pausa mediante armonía, melodía y ritmo. Terminar en V puede dejar continuidad; volver a I puede afirmar una llegada. Ningún símbolo garantiza por sí solo que una frase esté cerrada: hay que escuchar también su melodía y el silencio posterior.',
    workedExample:'El esquema C–F–G–C ofrece un lugar de regreso; C–F–G–G prolonga la espera. No resuelve tu melodía: inventá el gesto y probá los dos recorridos con él. Si la nota final es Do sobre G, quizá oigas una tensión que desaparece al volver a C; si es Sol, ambos acordes la contienen y la diferencia depende más del acompañamiento. Nombrá lo que pasa en tu caso, sin trasladar automáticamente la conclusión del ejemplo.',
    misconception:'«V siempre debe resolver enseguida». Una frase abierta puede servir al recorrido. Compará el final con y sin regreso a I; elegí según el encargo y prepará después un cierre de la pieza completa.',
    application:'La pieza 3 empieza desde una intención armónica, con motivo nuevo. El capítulo 8 revisa cómo se mueven estos mismos acordes y el 9 decide color y cierre; no hace falta iniciar una escena diferente para cada recurso.',
    mastery:'Puedo relacionar I, IV y V con notas concretas y comparar una llegada abierta con una vuelta al centro en material propio.',
    sources:[{title:'Open Music Theory — Harmonic function and cadences',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Continuá C del capítulo 7 y escuchá sin editar. Elegí un cambio de acorde cuyo salto de registro te distraiga; conservá tu versión actual antes de modificarlo.',deliverable:'Un punto de revisión y una referencia para volver atrás.'},
      {minutes:5,action:'En pista 4, probá otra disposición de ese mismo acorde moviendo una o dos notas de octava. Conservá sus nombres y el lugar donde cambia: revisás posición, no función.',deliverable:'Dos disposiciones del mismo acorde sobre la misma melodía.'},
      {minutes:6,action:'Escuchá la nota más baja de cada disposición y después las superiores. Buscá una nota común con el acorde anterior o un movimiento corto; elegí si esa continuidad sirve a tu frase.',deliverable:'Una línea interna que podés seguir y una posición elegida.'},
      {minutes:6,action:'Aplicá ese criterio a un segundo cambio de tu recorrido. Si necesitás apoyo, consultá la disposición del ejemplo; después decidí por escucha, sin cambiar la melodía.',deliverable:'Acompañamiento de cuatro compases con dos enlaces revisados.'},
      {minutes:6,action:'Compará la versión heredada con la actual, escuchando los cuatro compases. Si un acorde sigue tapando la melodía, probá desplazar su registro y restauralo si pierde claridad.',deliverable:'Versión elegida por continuidad y espacio para la melodía.'},
      {minutes:4,action:'Guardá C del capítulo 8. Escribí una línea real de tu arreglo, por ejemplo «Do permanece y Mi sube a Fa», y dejá señalada la llegada que revisarás con séptimas.',deliverable:'Pieza 3 con voces revisadas y una decisión comprobable.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: durante 10 agregá raíces graves en pista 3; durante 10 escuchá si permiten quitar una duplicación de pista 4; durante 10 compará y guardá. Si preferís dos pistas, usá ese tiempo para otra disposición sin añadir bajo.',
    theory:'Conducción de voces describe cómo una nota de un acorde pasa a otra del siguiente. Conservar notas comunes y mover poco las demás puede crear continuidad; los saltos también pueden ser deliberados. Cambiar una nota de octava mantiene su clase de altura, pero modifica registro y relación con la melodía. Una inversión tiene una nota distinta de la raíz en el bajo del acorde. Si otra pista toca la raíz más grave, el conjunto puede quedar en posición fundamental aunque la pista superior use otra disposición.',
    workedExample:'Una posibilidad para C–F–G–C es Do–Mi–Sol → Do–Fa–La → Si–Re–Sol → Do–Mi–Sol, manteniendo un registro comparable. Seguí una línea por vez: abajo Do–Do–Si–Do; en medio Mi–Fa–Re–Mi; arriba Sol–La–Sol–Sol. Ninguna nota necesita saltar a otra octava. Es una opción para comparar con tu arreglo, no la disposición obligatoria. Si tu último acorde es G, aplicá el mismo criterio sin reemplazar la llegada que elegiste.',
    misconception:'«La disposición con menos movimiento siempre es mejor». Puede ser fluida y, aun así, tapar la melodía o quitar un salto expresivo. Compará el recorrido completo y conservá la posición que cumpla la función musical que buscás.',
    application:'Se conservan duración, melodía y función armónica de la pieza 3; cambia la manera de distribuir sus notas. La fuente C del capítulo 7 queda disponible para comparar el efecto real del arreglo.',
    mastery:'Puedo seguir una voz entre acordes, distinguir raíz de disposición y elegir registro por su efecto sobre mi pieza.',
    sources:[{title:'Open Music Theory — Voice Leading',url:'https://musictheory.pugetsound.edu/mt21c/VoiceLeading.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Continuá C del capítulo 8 y recuperá de oído su llegada. Elegí el G que prepara el final; conservá tu melodía y las posiciones de los otros acordes.',deliverable:'Una transición de la pieza elegida para probar color.'},
      {minutes:5,action:'Añadí Fa a ese G para formar G7=Sol–Si–Re–Fa. Compará con la tríada quitando y reponiendo sólo Fa; mantené el resto igual.',deliverable:'Comparación G/G7 situada en tu propia pieza.'},
      {minutes:6,action:'Si sigue C, escuchá Fa→Mi: probá colocar Mi en el acorde de llegada en un registro cercano. Si tu final seguía en G, probá una llegada a C y comparala con el final abierto anterior.',deliverable:'Color y resolución escuchados en contexto, con alternativa recuperable.'},
      {minutes:6,action:'Elegí tríada o séptima y el final que sirva al encargo. Ajustá sólo la última respuesta melódica o su silencio para que la pieza termine; evitá sumar otro recurso a la vez.',deliverable:'Pieza 3 con color elegido y cierre preparado.'},
      {minutes:6,action:'Escuchá una pasada completa y detenela antes del reinicio. Comprobá dirección y una línea interna; si la séptima distrae, retirala y verificá que conservás el recorrido.',deliverable:'Tercera miniatura cerrada por elección, con séptimas o sin ellas.'},
      {minutes:4,action:'Guardá C del capítulo 9. Anotá qué hizo Fa y por qué lo conservaste o descartaste. Antes del próximo ciclo, describí cómo probarías un color nuevo sin reescribir toda la pieza.',deliverable:'Pieza 3 terminada y un método de comparación transferible.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: dedicá 10 a probar Dm7–G7–Cmaj7–Cmaj7 sobre una copia de tu pieza, 10 a escuchar las líneas Fa–Fa–Mi y Do–Si–Si, y 10 a adaptar una llegada y elegir. Dm7=Re–Fa–La–Do; G7=Sol–Si–Re–Fa; Cmaj7=Do–Mi–Sol–Si. Conservá el final del núcleo si el ii–V–I no mejora tu intención.',
    theory:'Una séptima añade una cuarta nota a la tríada. G7 tiene séptima menor Fa; Cmaj7 tiene séptima mayor Si. En G7→C, Fa puede bajar a Mi y Si subir a Do; no hace falta que ambas resoluciones estén en una sola pista. En ii–V–I de Do, Dm7–G7–Cmaj7, las terceras y séptimas son Fa/Do, Si/Fa y Mi/Si. Escucharlas revela dirección sin tocar todas las notas. Este recorrido es una opción de lenguaje, no una condición para que tu pieza tenga calidad o pertenezca al curso.',
    workedExample:'Si tu G ocupa el compás 3 y C el 4, añadí Fa sólo en 3. Escuchá el cambio G→G7 y después el enlace hacia Mi de C. Si usás Si en el último acorde, obtenés Cmaj7: su color puede dejar una apertura que te guste o que compita con el cierre. Probá una decisión por vez y conservá la melodía mientras evaluás. El ejemplo muestra qué escuchar; la elección depende de la intención que escribiste para esta pieza.',
    misconception:'«Una séptima hace automáticamente mejor un acorde». Agrega un color y una relación que deben servir al contexto. Si quitarla deja más clara la llegada, elegir la tríada demuestra criterio, no falta de avance.',
    application:'Cerrás la pieza 3 en cuatro compases. El núcleo compara G y G7 y termina la composición; el ii–V–I queda disponible en la extensión. La pieza 4 empezará desde un riff nuevo y otra manera de organizar el espacio.',
    mastery:'Puedo comparar tríada y séptima, reconocer una resolución de voz y terminar mi pieza sin imponer un recurso que no la mejora.',
    sources:[{title:'Open Music Theory — Introduction to Jazz Theory',url:'https://musictheory.pugetsound.edu/mt21c/IntroductionToJazzTheory.html'},{title:'Berklee Online — Harmony 2',url:'https://online.berklee.edu/courses/harmony-2'}]
  },
  {
    activities:[
      {minutes:3,action:'Empezá la pieza 4 en C vacío. Recuperá una manera de dejar aire y elegí un tempo cómodo. Tu encargo es un groove nuevo; escribí qué ataque o gesto querés que se recuerde.',deliverable:'Intención de fraseo para un material nuevo.'},
      {minutes:6,action:'En pista 5 inventá un riff de dos o tres ataques en un compás, con Do, Mi, Sol o La. Escribí una respuesta en 2 conservando un rasgo; no copies el ritmo de las piezas anteriores.',deliverable:'Riff y respuesta nuevos, con espacio después de la frase.'},
      {minutes:5,action:'Copiá 1 a 3 y 2 a 4. Añadí un apoyo simple: una nota grave en pista 3 o un acorde conocido en pista 4. Repetilo sin llenar los huecos del riff.',deliverable:'Groove original de cuatro compases con un soporte mínimo.'},
      {minutes:6,action:'Sobre tu versión, compará la entrada del riff donde está y un paso después, sin exceder la barra. Si querés probar color de blues y usás C7, compará Mi con un breve Mib→Mi en esa misma frase.',deliverable:'Una prueba elegida de colocación o color, con el original conservado.'},
      {minutes:6,action:'Elegí la variante y escuchá cuatro compases. Quitá un ataque de acompañamiento si invade la respuesta; comprobá que el riff sigue reconocible y el pulso continúa durante el aire.',deliverable:'Groove con fraseo elegido, sin exigir swing ni más capas.'},
      {minutes:4,action:'Guardá C del capítulo 10. Anotá el rasgo que conservarás al desarrollar: ritmo inicial, contorno o silencio. En el capítulo 11 crecerá a ocho compases desde esta misma idea.',deliverable:'Pieza 4 iniciada y una identidad concreta para desarrollar.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: dedicá 10 a comparar feel recto y swing, 10 a tocar tu riff sobre ambos sin cambiar BPM y 10 a elegir y guardar. En C podés activar «usar swing 2:1 en mi idea»: es una aproximación didáctica fija que se conserva al continuar el ciclo. En el OP–XY explorá los controles de tu unidad; su feel no tiene por qué coincidir con esta proporción.',
    theory:'Un riff es una figura que gana identidad al repetirse. Frasear es decidir ataques, duraciones, acentos y respiraciones alrededor del pulso. El blues puede aportar una inflexión sin obligarte a usar su forma de doce compases: sobre C7=Do–Mi–Sol–Sib, Mib→Mi puede crear y resolver un roce entre tercera menor y mayor. Probalo como gesto situado, no como una nota que deba agregarse a todo. El swing cambia la distribución temporal de subdivisiones; no equivale a cambiar el tempo y su proporción varía con contexto y estilo.',
    workedExample:'Problema de escucha: la respuesta queda pegada al regreso del riff. Primera prueba: quitá su último ataque. Segunda prueba, desde el original: acortá su última nota. Compará ambas sobre tu acompañamiento y elegí dónde aparece mejor el aire. Si además querés Mib→Mi, probalo después y sobre C7; esa aproximación no exige reemplazar tu riff ni cambiar a una forma de doce compases. El ejemplo ofrece una manera de revisar, no una frase terminada.',
    misconception:'«Para que suene a blues debo poner swing y doce compases». Forma, material y feel son decisiones diferentes. Este encargo desarrolla ocho compases con recursos de fraseo; un groove recto también puede incorporar una inflexión de blues.',
    application:'La pieza 4 comienza con cuatro compases propios y hasta cuatro pistas, aunque dos alcanzan. Su identidad sale del riff y sus huecos. La extensión permite comparar recto y swing 2:1 en C o explorar el feel en el instrumento; el núcleo puede completarse con ataques y duraciones de la grilla.',
    mastery:'Puedo inventar un groove nuevo, comparar una decisión de fraseo y conservar el espacio que hace reconocible mi riff.',
    sources:[{title:'Open Music Theory — Introduction to Jazz Theory',url:'https://musictheory.pugetsound.edu/mt21c/IntroductionToJazzTheory.html'},{title:'Teenage Engineering — OP–XY guides',url:'https://teenage.engineering/guides/op-xy'}]
  },
  {
    activities:[
      {minutes:3,action:'Recordá el riff antes de abrirlo y continuá C del capítulo 10. Escuchá sus cuatro compases; elegí el rasgo que conservarás al variar y nombrá qué aporta cada pista activa.',deliverable:'A de cuatro compases recuperada y un criterio de identidad.'},
      {minutes:5,action:'Copiá todas las pistas de los compases 1→5, 2→6, 3→7 y 4→8 con el control de copiar compás. Escuchá los ocho: A y su repetición exacta.',deliverable:'Ocho compases reales, con la primera mitad preservada.'},
      {minutes:6,action:'Transformá sólo la segunda mitad: elegí subir o bajar el riff una octava, acortar sus respuestas o retirar un ataque de acompañamiento. Aplicá una sola transformación principal.',deliverable:'A′ de cuatro compases derivada de tu A.'},
      {minutes:6,action:'Escuchá el paso de 4 a 5 y después 5–8. Si la variación borra el riff, restaurá su comienzo en 5 y 7; si no se oye cambio, hacé más clara la transformación elegida.',deliverable:'Variación reconocible por relación con el material original.'},
      {minutes:6,action:'Compará una pasada de A+A y otra de A+A′. Elegí por identidad y aire; verificá que no cambiaste por accidente los compases 1–4.',deliverable:'Forma de ocho compases con una variación deliberada.'},
      {minutes:4,action:'Guardá C del capítulo 11. Anotá qué conserva A′, qué cambia y un lugar donde falta terminar la frase. Ese será el trabajo del capítulo 12.',deliverable:'Pieza 4 expandida a ocho compases y lista para cerrar.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: tocá o programá tres respuestas de dos compases durante 15 minutos, compará durante 10 cuál conserva el riff y guardá una durante 5. En el OP–XY podés probar otro timbre a nivel parecido; en la maqueta local usá registro, duración o cantidad de notas para una comparación controlable.',
    theory:'A′ significa una variante reconocible de A. Cambiar registro mueve la idea a otra zona; cambiar duración altera su articulación; quitar material modifica densidad y textura. Esas decisiones pueden desarrollar una pieza sin acordes nuevos. En este capítulo A ocupa 1–4 y A′ ocupa 5–8: juntas suman ocho compases. La copia de compás incluye todas las pistas; revisá cada rol antes de variar para que una capa heredada no ocupe un hueco que querés abrir.',
    workedExample:'Si el rasgo recordable es el ritmo inicial, conservá sus posiciones en 5 y 7. Elegí una única prueba, por ejemplo acortar la respuesta de 6 y 8. Compará con la repetición exacta. Si preferís registro, restaurá duraciones y desplazá la frase una octava en la segunda mitad. Escuchá qué cambia en cada caso sobre tu material; no es necesario combinar las dos transformaciones para que exista desarrollo.',
    misconception:'«Desarrollar exige escribir una idea distinta en cada compás». Una variación puede ampliar el recorrido precisamente porque permite reconocer lo anterior. Conservá un rasgo audible y preguntate si el cambio le da una función a la segunda mitad.',
    application:'La pieza 4 crece de cuatro a ocho compases. Continuar C recupera sus cuatro compases; vos escribís la expansión copiándolos y transformando la segunda mitad. El capítulo 12 conserva esta forma y prepara su final.',
    mastery:'Puedo desarrollar A en A′ cambiando un rasgo y comprobar que la primera mitad conserva su identidad.',
    sources:[{title:'Open Music Theory — Motives and melodic development',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Continuá C del capítulo 11 y escuchá una pasada de ocho compases sin editar. Señalá la entrada de A′ y el momento donde esperás que termine la pieza.',deliverable:'Mapa oído de presentación, variación y final.'},
      {minutes:5,action:'En el límite 4→5, probá quitar un ataque de acompañamiento al final del compás 4. Si no hay un ataque allí, acortá el apoyo sostenido para dejar un pulso de aire. Compará con la versión original y elegí si ese espacio hace más clara la entrada de A′.',deliverable:'Entrada de segunda mitad revisada con una sola variable.'},
      {minutes:6,action:'En 8, probá un cierre con menos ataques y una nota final de llegada. Escuchá desde 7, dejá silencio posterior y anotá esa versión.',deliverable:'Primer cierre situado en los últimos dos compases.'},
      {minutes:6,action:'Desde la respuesta anterior, probá un segundo cierre: frase corta y más silencio. Compará con el primero sin cambiar los compases 1–7; elegí por el efecto que buscás.',deliverable:'Dos finales comparables y uno elegido sin una receta de notas.'},
      {minutes:6,action:'Escuchá la pieza una vez y detenela antes de repetir. Comprobá identidad del riff y aire entre frases; corregí un único ataque si todavía estorba al cierre.',deliverable:'Pieza 4 completa: groove, variación y final audibles.'},
      {minutes:4,action:'Guardá C del capítulo 12 con nombre. Indicá un tramo donde podrías improvisar dejando volver el riff, y una decisión que resolviste sin ejemplo. La próxima composición nace de tu propio encargo.',deliverable:'Cuarta miniatura cerrada y un espacio de improvisación reconocido.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: en el OP–XY, dedicá 10 a dibujar un blues de doce compases —C7×4, F7×2, C7×2, G7, F7, C7×2—, 15 a adaptar tu riff a sus cambios y 5 a guardar. No alcanza con añadir cuatro compases al final del groove: escuchá las funciones del recorrido. También podés usar los 30 para improvisar sobre tu pieza de ocho, ya terminada.',
    theory:'La forma organiza lo que vuelve, lo que cambia y lo que concluye. Un bucle puede funcionar como base de improvisación, mientras una miniatura necesita también una versión con final elegido. El silencio y la reducción de ataques ayudan a distinguir ese final de una interrupción arbitraria. A+A′ suma ocho compases; una forma de blues de doce tiene otra distribución y requiere adaptar las frases. No hace falta ampliar el número de compases para cerrar bien la forma que ya compusiste.',
    workedExample:'Diagnóstico posible: se reconoce el cambio en 5, pero 8 parece idéntico a otra respuesta. Guardá ese punto de partida. Probá quitar el último ataque del acompañamiento; escuchá. Restauralo y probá una respuesta melódica más corta; escuchá. Elegí la que haga claro el final conservando el groove. Para tocar encima después, identificá dónde el riff deja espacio y volvé a su entrada como referencia; no hace falta escribir un solo nuevo para terminar esta pieza.',
    misconception:'«Si el loop funciona, el final ya está resuelto». Repetir puede ocultar que no hay conclusión. Escuchá una sola pasada y dejá silencio después: si el final parece un corte accidental, probá una retirada o una respuesta más corta.',
    application:'Cerrás la pieza 4 en ocho compases y reconocés un lugar para improvisar. Su expansión a doce o más queda para el instrumento y la práctica adicional. La pieza 5 recupera herramientas elegidas por vos con material nuevo.',
    mastery:'Puedo organizar ocho compases, elegir un cierre en contexto y distinguir una base que repite de una pieza que termina.',
    sources:[{title:'Open Music Theory — Phrase and form',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'},{title:'Teenage Engineering — OP–XY Arrange',url:'https://teenage.engineering/guides/op-xy/arrange'}]
  },
  {
    activities:[
      {minutes:3,action:'Empezá la pieza 5 en C vacío. Escribí tu encargo: tema instrumental o groove, una intención audible y dos herramientas conocidas que querés usar. Elegí tempo y hasta cuatro roles; no tenés que ocuparlos todos.',deliverable:'Un encargo propio de ocho compases que podés evaluar por oído.'},
      {minutes:6,action:'Inventá dos ideas de un compás empezando por melodía en pista 5 o bajo/riff en pista 3. Conservá la primera antes de probar la segunda; usá ritmo o contorno nuevos, alterná la versión guardada y C, escuchá y elegí una.',deliverable:'Germen original elegido por una razón vinculada al encargo.'},
      {minutes:5,action:'Copiá la idea elegida al compás 2 y escribí una respuesta. Copiá 1→3 y 2→4; después 1→5, 2→6, 3→7 y 4→8, incluyendo las pistas activas.',deliverable:'Borrador real de ocho compases a partir de material propio.'},
      {minutes:6,action:'Añadí sólo el soporte necesario: acorde en pista 4, bajo en 3 o batería en 1. Escribilo en 1–2 y repetilo en los otros pares con copiar compás. Nombrá qué aporta cada pista; dejá libre el rol innecesario.',deliverable:'Base provisional que sostiene la idea sin exigir todas las capas.'},
      {minutes:6,action:'Escuchá los ocho compases. Probá quitar un ataque de la capa nueva y reponerlo; elegí por claridad de la idea. Señalá qué querés cambiar en 5–8 para desarrollar el encargo.',deliverable:'Base propia elegida y un objetivo concreto para la segunda mitad.'},
      {minutes:4,action:'Guardá C del capítulo 13 junto al encargo y los roles. Anotá tu próximo paso con un verbo y un lugar: «En 5–8 voy a…». Conservá el borrador para poder comparar después.',deliverable:'Pieza 5 iniciada con autonomía y continuidad preparada.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: durante 10 probá otra armonía sobre el mismo germen, durante 10 compará si sirve al encargo y durante 10 guardá la elección. Si elegís comparar sonidos, hacelo en el OP–XY a nivel parecido; la maqueta local no reproduce sus motores ni su mezcla.',
    theory:'Un encargo útil describe un efecto que podés escuchar, como «calmo al empezar, más abierto al volver». Los roles explican qué hace cada capa: motivo, respuesta, bajo, armonía o pulso. En esta guía pista 1=batería, 3=bajo, 4=armonía, 5=motivo y 6=respuesta opcional; son convenciones, no obligaciones universales. El bajo puede relacionar raíces y dirección, y la batería puede organizar apoyos; ninguno necesita duplicar cada ataque del otro. Una base con dos pistas puede cumplir mejor un encargo que otra con cuatro.',
    workedExample:'Usá el ejemplo sólo si no sabés cómo decidir: «Quiero que el riff se reconozca aun sin batería» permite una prueba concreta. Escuchá el riff solo; añadí un apoyo; retiralo y comprobá qué aportaba. Si la intención era dar dirección al final, una nota de bajo puede ayudar más que otra capa rítmica. Elegí vos notas, posiciones y recorrido. El ejemplo enseña a relacionar intención y prueba, sin resolver la composición.',
    misconception:'«Una pieza completa necesita todas las pistas». La cantidad no demuestra función. Retirá temporalmente el material de una capa y reponelo; si no podés describir qué mejora al volver, quizá todavía no haga falta.',
    application:'Esta es una composición nueva de ocho compases, creada desde tu encargo. Los capítulos 14–16 desarrollan su contraste, transición y revisión. Los ejemplos quedan como consulta; el núcleo empieza por tus decisiones.',
    mastery:'Puedo formular un encargo audible, elegir material nuevo y construir una base donde cada pista tiene una función.',
    sources:[{title:'Teenage Engineering — OP–XY guides',url:'https://teenage.engineering/guides/op-xy'},{title:'Open Music Theory — Composition and musical organization',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Continuá C del capítulo 13, recuperá tu encargo y escuchá las dos mitades. Nombrá un rasgo de 1–4 que conservarás y una sola variable que transformarás en 5–8.',deliverable:'Criterio propio de identidad y contraste.'},
      {minutes:5,action:'Protegé el original: en la guía, comprobá que estás editando C del capítulo 14 y que C13 sigue disponible. En OP–XY, copiá los patrones que cambiarás y seleccioná esas copias antes de editar la segunda mitad.',deliverable:'Versión anterior recuperable y material de variación independiente.'},
      {minutes:6,action:'Aplicá a 5–8 el cambio elegido de registro, textura, ritmo o armonía. Conservá 1–4 y el rasgo de identidad que anotaste; no agregues otra transformación todavía.',deliverable:'Segunda mitad contrastante derivada de tu base.'},
      {minutes:6,action:'Escuchá 1–8 y compará con el borrador. Si el parentesco se perdió, recuperá en 5 o 7 el ritmo inicial o una respuesta reconocible; reescuchá el mismo recorrido.',deliverable:'Contraste que conserva una relación audible entre mitades.'},
      {minutes:6,action:'Decidí si el cambio cumple tu encargo. Conservá la versión nueva o restaurá la anterior; verificá volviendo a 1–4 que esa primera mitad sigue como la elegiste.',deliverable:'Forma de ocho compases elegida por intención, con primera mitad protegida.'},
      {minutes:4,action:'Guardá C del capítulo 14. Escribí «se conserva…; cambia…» y señalá qué escuchás al pasar de 4 a 5. En el capítulo 15 decidirás si ese límite necesita preparación.',deliverable:'Pieza 5 con contraste deliberado y transición localizada.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: dedicá 15 a una segunda estrategia de contraste en una versión recuperable, 10 a comparar ambas mitades juntas y 5 a guardar la elegida. No combines automáticamente las estrategias: escuchá cuál cumple mejor el encargo con menos decisiones simultáneas.',
    theory:'El contraste organiza la forma cuando se relaciona con lo ya escuchado. Una segunda mitad puede cambiar registro, densidad, ritmo o armonía y seguir perteneciendo a la misma pieza. Proteger una versión permite decidir por comparación, no por memoria imprecisa. En el OP–XY una escena puede compartir referencias a patrones con otra: copiar la escena no garantiza independencia de sus notas. En ARRANGE, M2 copia el patrón, M1 crea otro y M3 pega; comprobá qué patrón usa cada sección antes de variarlo.',
    workedExample:'Criterio de revisión, sin una B resuelta: si elegiste «más abierto al volver», probá que el riff suba de registro en 5–8 conservando su ritmo. Escuchá contra el borrador. Si el resultado sólo parece más agudo, restaurá el registro y probá retirar acompañamiento durante la respuesta. Una intención puede admitir varias soluciones; elegí la que puedas reconocer al escuchar las dos mitades juntas.',
    misconception:'«Copié una escena y por eso puedo editar sin afectar la otra». Si ambas usan el mismo patrón, una edición puede cambiar las dos. Verificá la referencia y volvé a escuchar la primera mitad después de editar; en la guía, comprobá también el capítulo cuyo C estás modificando.',
    application:'La pieza 5 conserva ocho compases: 1–4 presentan y 5–8 contrastan. No se exige una progresión modelo ni una cantidad fija de cambios. El objetivo es que puedas explicar qué relación escuchás entre ambas mitades.',
    mastery:'Puedo proteger una versión, transformar una sección por intención y verificar que su relación con la primera sigue audible.',
    sources:[{title:'Teenage Engineering — OP–XY Arrange',url:'https://teenage.engineering/guides/op-xy/arrange'}]
  },
  {
    activities:[
      {minutes:3,action:'Continuá C del capítulo 14 y escuchá 3–6. Escribí qué esperás percibir al llegar a 5: entrada más clara, más aire o continuidad. Si ya funciona, tomalo como referencia.',deliverable:'Una función concreta para la transición.'},
      {minutes:5,action:'Anotá el compás 4 y probá quitar un ataque de acompañamiento en su último pulso; si la pieza tiene una sola voz, acortá allí su última nota. Conservá el comienzo de 5.',deliverable:'Transición por retirada con el original recuperable.'},
      {minutes:6,action:'Compará 3–6 con y sin esa retirada. Elegí una y explicá qué cambia al entrar en 5; restaurar el original también es una decisión válida.',deliverable:'Transición elegida por su efecto en el cambio de mitad.'},
      {minutes:6,action:'Prepará un final en 8: elegí una llegada conocida, una última respuesta más corta o un silencio posterior. Probá una alternativa desde 7 y conservá la que complete tu encargo.',deliverable:'Cierre propio comparado en contexto.'},
      {minutes:6,action:'Escuchá una pasada de 1–8 y detenela antes del reinicio. Comprobá que la preparación no tapa la entrada y que el final se entiende; corregí sólo el problema más claro.',deliverable:'Borrador completo de la pieza 5 con transición y final.'},
      {minutes:4,action:'Guardá C del capítulo 15 y anotá un punto que quieras revisar con distancia. Conservá esta versión: será la referencia antes/después del último capítulo.',deliverable:'Pieza completa recuperable y una revisión final preparada.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: durante 10 probá otra estrategia, como una nota de destino anticipada al final de 4; durante 10 compará con la retirada; durante 10 guardá. Una anticipación debe pertenecer o relacionarse claramente con lo que entra en 5. Si probás automatización, hacelo en el OP–XY con un único parámetro y una función audible; no es necesaria para terminar.',
    theory:'Una transición hace legible una relación entre secciones mediante retirada, continuidad, anticipación o reentrada. La anticipación presenta antes una nota del acorde o material que llega después; cualquier nota cercana al límite no recibe automáticamente ese nombre. Si la nota se repite al inicio del siguiente compás en la maqueta local, se escucha otro ataque: el editor no liga notas a través de la barra. Un cierre organiza la última frase y lo que ocurre después de ella. Automatización y efectos son recursos opcionales del instrumento, no pasos obligatorios del núcleo.',
    workedExample:'Supongamos que el límite se entiende mejor con un pulso de aire. Compará retirar un ataque con conservarlo, sin añadir a la vez fill ni efecto. Si después probás anticipar un acorde Am, La o Mi pueden anunciar notas que estarán allí; comprobá que esa relación se escucha con tu material. Elegí una estrategia por su efecto. Para el cierre usá la misma lógica: aislá una decisión y escuchá desde el compás anterior.',
    misconception:'«Una transición necesita llenar el último compás». Más ataques pueden ocultar la entrada que querés preparar. Probá primero retirar uno y escuchá el límite completo; añadí material sólo si podés identificar qué función falta.',
    application:'La pieza 5 queda completa en ocho compases. Su núcleo usa las notas, duraciones y espacios que ya dominás. El capítulo 16 revisará esta versión, la cerrará y reservará tiempo para iniciar otra idea sin guía musical.',
    mastery:'Puedo decidir si un límite necesita preparación, comparar una transición y dar a mi pieza un final propio.',
    sources:[{title:'Teenage Engineering — OP–XY guides',url:'https://teenage.engineering/guides/op-xy'},{title:'Open Music Theory — Musical form',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  },
  {
    activities:[
      {minutes:3,action:'Continuá C del capítulo 15 y escuchá una pasada sin editar. Volvé a tu encargo y elegí un problema observable de identidad, aire, llegada, roles, forma o cierre; localizalo en un compás.',deliverable:'Un diagnóstico concreto y una versión anterior conservada.'},
      {minutes:4,action:'Proponé una causa y cambiá una sola variable en ese lugar: ataque, duración, altura, registro o presencia de una voz. Consultá el recurso preciso sólo si necesitás destrabarte.',deliverable:'Una corrección propia que se puede comparar con el original.'},
      {minutes:4,action:'Escuchá el mismo tramo antes y después. Elegí la corrección si mejora tu intención; restaurá la referencia si empeora o no podés reconocer una mejora.',deliverable:'Decisión de revisión con evidencia audible.'},
      {minutes:4,action:'Escuchá los ocho compases una sola vez y dejá el final en silencio. Comprobá el problema elegido y un criterio anterior; si falta una corrección evidente, hacela sin ampliar la pieza.',deliverable:'Quinta miniatura cerrada y revisada como una unidad.'},
      {minutes:5,action:'Guardá C del capítulo 16 y el proyecto del OP–XY si lo usaste. Anotá nombre, intención y «qué escuché → qué cambié → qué pasó». Registrá qué pudiste decidir solo y prepará un espacio vacío aparte.',deliverable:'Pieza 5 entregable, referencia anterior conservada y cierre documentado.'},
      {minutes:10,action:'En un patrón nuevo del OP–XY o una hoja de grilla aparte, inventá dos compases de pregunta, respuesta y final. Si antes empezaste por melodía, ahora por ritmo o bajo; si por groove, ahora por melodía. No copies patrones ni notas resueltas. Alcanza una grilla legible si programar demora; anotá la ayuda musical que necesitaste.',deliverable:'Germen nuevo de dos compases, sin sobrescribir la pieza final, y evidencia de transferencia.'}
    ],
    optionalPractice:'Otros 30 minutos, opcionales: desarrollá el germen nuevo durante 15 minutos, escuchá qué herramienta usaste sin ayuda durante 10 y guardá durante 5. También podés repetir un fragmento que todavía necesite apoyo. Aumentá una sola dificultad; no hace falta agregar una técnica para demostrar progreso.',
    theory:'Revisar es relacionar una observación con una causa y comprobar una corrección. «No se entiende el motivo en 6» permite una prueba; «todo suena mal» todavía no localiza el problema. Cambiar una variable hace más clara la comparación. La autonomía se observa al elegir y comprobar sin una solución musical resuelta; consultar botones, nombres de acordes o el manual sigue permitido. Transferir exige material nuevo y decisiones propias: cambiar sólo preset, tempo o transponer el mismo patrón no demuestra que puedas iniciar otra composición.',
    workedExample:'Si en 6 el acorde tapa el motivo, podés quitar una voz del acorde mientras conservás el resto. Escuchá el mismo tramo y decidí si la melodía aparece sin perder el soporte que querías. Si no mejora, restaurá y revisá la causa otro día. Para el germen final no hay frase modelo: elegí otro punto de partida, escribí una pregunta breve, inventá su respuesta y prepará un final. Conservá la pieza terminada antes de abrir ese espacio de trabajo nuevo.',
    misconception:'«Ser autónomo significa no consultar nada». Autonomía musical es decidir qué querés, probar y escuchar; el manual técnico no reemplaza esas decisiones. Registrá si necesitaste una pista musical y cuál, para practicar después justo esa capacidad.',
    application:'Cerrás la pieza 5 y la ruta con cinco miniaturas propias. La pieza final queda guardada en C16; el germen de transferencia se escribe aparte y no la reemplaza. Elegí dos herramientas para tu próxima miniatura y material nuevo, con una extensión que puedas terminar.',
    mastery:'Puedo diagnosticar, comparar y cerrar una pieza propia, y comenzar otra con un procedimiento conocido sin copiar su material.',
    sources:[{title:'Teenage Engineering — OP–XY Project',url:'https://teenage.engineering/guides/op-xy/project'},{title:'Open Music Theory — Music Theory for the 21st-Century Classroom',url:'https://musictheory.pugetsound.edu/mt21c/MusicTheory.html'}]
  }
];

function courseMinutes(){
  return DEEP_CURRICULUM.reduce((sum, session) => sum + session.activities.reduce((n, activity) => n + activity.minutes, 0), 0);
}
