const PATH=[
 ['1 / construir un loop','Empezás con un patrón vacío en la pista 4.','Separar una nota de su posición en el tiempo.','Un compás Do-Mi-Sol-Mi que podés editar.','En el ejercicio 2 vas a convertir esas notas en bloques y cambiar un solo botón.'],
 ['1 / construir un loop','Reutilizá las posiciones Do, Mi y Sol del ejercicio 1.','Cambiar de acorde con el mínimo movimiento.','Un acompañamiento de dos compases: C y Am.','Guardá este loop: será la base de los ejercicios 3 y 4.'],
 ['1 / construir un loop','Dejá sonar el loop C-Am del ejercicio 2. Seleccioná la pista 5.','Recordar y repetir una frase corta de oído.','Una respuesta de hasta cuatro notas sobre tu acompañamiento.','En el ejercicio 4 conservarás las notas y cambiarás su ritmo.'],
 ['2 / transformar la idea','Conservá la base C-Am. Elegí Mi-Sol-La para comparar el ritmo.','Desplazar ataques sin perder el pulso.','Dos versiones del mismo motivo, con diferentes silencios.','Antes de improvisar más, el ejercicio 5 amplía el color de los acordes.'],
 ['2 / transformar la idea','Volvé al acorde C: Do-Mi-Sol.','Escuchar qué agrega una séptima.','Una comparación clara entre C y Cmaj7.','La tercera y la séptima serán las dos voces del próximo acompañamiento.'],
 ['2 / transformar la idea','Creá un patrón de cuatro compases en pistas 3 y 4.','Oír una progresión como dos líneas que se mueven.','Un loop Dm7-G7-Cmaj7-Cmaj7, con bajo y dos voces.','Conservá este loop para los ejercicios 7 y 8.'],
 ['3 / improvisar con dirección','Reproducí el ii-V-I del ejercicio 6 y seleccioná la pista 5.','Elegir dónde termina cada frase.','Tres llegadas: Fa sobre Dm7, Si sobre G7 y Mi sobre Cmaj7.','El ejercicio 8 agrega una nota de aproximación antes de cada destino.'],
 ['3 / improvisar con dirección','Conservá el acompañamiento y los destinos del ejercicio 7.','Crear tensión breve y resolverla a propósito.','Tres parejas de notas: Mi-Fa, Sib-Si y Mib-Mi.','Después llevaremos el fraseo a una forma nueva: el blues.'],
 ['4 / tocar una forma','Abrí tres patrones de cuatro compases; dejá el ii-V-I guardado.','Saber en qué compás estás aunque el acorde se repita.','Un blues de doce compases con tres acordes.','Este blues será el acompañamiento para la pregunta y respuesta del ejercicio 10.'],
 ['4 / tocar una forma','Poné en loop el blues del ejercicio 9.','Dar continuidad a un solo mediante repetición y respuesta.','Una vuelta de blues con un motivo reconocible y espacio.','El ejercicio 11 toma un ritmo de una grabación para ampliar tu fraseo.'],
 ['4 / tocar una forma','Elegí una frase de unos dos segundos que te guste.','Escuchar duración, acentos y ubicación en el pulso.','Un ritmo aprendido de oído y una variación propia.','Usá ese recurso, o uno de los anteriores, para cerrar una pieza en el ejercicio 12.'],
 ['5 / terminar una pieza','Recuperá el ii-V-I, el loop C-Am y un motivo que te guste.','Organizar material conocido en una forma con contraste.','Una pieza de 16 compases: A, A variada, B y A final.','Escuchá la pieza completa y elegí una sola mejora para tu siguiente versión.']
];
const SYMBOLS=['cuatro puntos','mano','división','rampa','escalera ascendente','escalera descendente','rnd','línea con puntos','luna / vela','hélice','flecha con punto','obturador','sol radial','círculo radial'];
let diagramSerial=0;
function keyInfo(k){const u=Array.isArray(k),i=u?k[1]:k;return {id:(u?'u':'n')+i,name:(u?UN:N)[i],pos:u?`fila superior · número ${(i+1)%10}`:`fila inferior · botón ${i+1}`,symbol:u?'número impreso':SYMBOLS[i]};}
function modeFor(n){return [2,5,6,9,12].includes(n)?'chord':'phrase';}
function learningBridge(n){const [phase,before,goal,after,next]=PATH[n-1];return `<div class="learning-path"><span class="path-phase">${phase}</span><div class="path-steps"><div><small>partís de</small><p>${before}</p></div><div><small>hoy aprendés</small><p>${goal}</p></div><div><small>te llevás</small><p>${after}</p></div></div><p class="path-next">${next}</p></div>`;}
function mapLegend(keys,mode,id){return `<div class="key-locator" data-for="${id}"><div class="key-mode">${mode==='chord'?'● JUNTAS: estos botones forman un acorde.':'→ POR SEPARADO: son las notas disponibles; seguí el orden del ejercicio.'}</div><div class="key-buttons">${keys.map(k=>{const q=keyInfo(k);return `<button data-locate="${q.id}" data-target="${id}" aria-pressed="false"><b>${q.name}</b><span>${q.pos}</span><small>${q.symbol}</small></button>`}).join('')}</div><div class="locator-foot"><span class="locator-status" aria-live="polite">Pulsá una etiqueta para destacar su tecla.</span><button data-zoom="${id}" aria-pressed="false">acercar teclado</button><button data-all="${id}">ver todas</button></div></div>`;}
function firstWalkthrough(){return `<div class="walkthrough"><h3>escribilo conmigo / una operación por vez</h3><div class="walk-buttons">${['1. Do → paso 1','2. Mi → paso 5','3. Sol → paso 9','4. Mi → paso 13'].map((x,i)=>`<button data-walk="${i}" aria-pressed="false">${x}</button>`).join('')}</div><p id="walk-detail" aria-live="polite">Elegí una operación: la foto señalará la nota y el paso correspondiente. El blanco marca la tecla; el rojo, el paso que hay que pulsar después.</p></div>`;}
